### ISSUE TITLE
Run with CloudFlare ArgoTunnel

### ISSUE THREAD

**Issue by amanjuman** [ShadowsocksR-Live/shadowsocksr-native#103]
Please answer these questions before submitting your issue. Thanks!

### What version of shadowsocks-native are you using?
Latest

### What operating system are you using?
Ubuntu 18.04 x64 - Server
Windows 10 x64 - Client with Firefox Fox Proxy Addons

### What did you do?
Server and client running perfectly. But I'm trying to build a proxy where firewall port open is not possible. For testing, I created a Google Cloud instance with all port disabled. From shell I configured the server, for temporary I opened firewall and it seems SSR works perfectly. Then I closed all ports from the cloud console. 

Now, I'm trying to establish an Argo tunnel with Nginx. I installed `[cloudflred](https://developers.cloudflare.com/argo-tunnel/downloads/)`. After installing I created a records in `/etc/hosts`
127.0.1.1 subdomain.domain.tls
then I started the tunnel issuing `cloudflared tunnel --url https://subdomain.domain.tld` which opened a private tunnel bypassing the firewall. I got a URL just like this, https://matt-rs-replacement-affected.trycloudflare.com later I created a CNAME record in DNS for zone subdomain.domain.tld > matt-rs-replacement-affected.trycloudflare.com > Auto

### What did you expect to see?
As the server works fine if I open port 443 and 80, I'm expecting this should work a well. But don't know what kind of modification needed in the config file. I tried this.
```
{
	"password": "goodpassword",
	"method": "chacha20",
	"protocol": "auth_sha1_v4",
	"protocol_param": "",
	"obfs": "http_simple",
	"obfs_param": "",
	"udp": false,
	"timeout": 300,
	"server_settings": {
		"listen_address": "0.0.0.0",
		"listen_port": 3636
	},
	"client_settings": {
		"server": "subdomain.domain.tld",
		"server_port": 443,
		"listen_address": "0.0.0.0",
		"listen_port": 1080
	},
	"over_tls_settings": {
		"enable": true,
		"server_domain": "subdomain.domain.tld",
		"path": "/50854b49-319d-4388-8977-d520bdd1ff16/",
		"root_cert_file": ""
	}
}
```
### What did you see instead?
I started proxy but no connection goes with the tunnel.

**Comment by ssrlive** [comment]
I don't know Argo tunnel. can't help you.
