### ISSUE TITLE
能问一下有没有windows下的SSRoT 的编译教程。

### ISSUE THREAD

**Issue by fuchanghao** [ShadowsocksR-Live/shadowsocksr-native#104]
个人测试在VS2019下无法正常使用sln编译，cmake也没有写对于MSVC相关的内容。

**Comment by ssrlive** [comment]
你水平敢再low一点吗？！
![image](https://user-images.githubusercontent.com/30760636/72680632-19a81380-3af7-11ea-8775-de0b6a80489a.png)

**Comment by fuchanghao** [comment]
我更新到了最新git：f00847a

子模块也更新了，也清理之后重新编译了。

可就是VS2019下会报错编译通不过。

严重性 代码 说明 项目 文件 行 禁止显示状态
错误 LNK2001 无法解析的外部符号 assert ssr-server E:\Source Code\shadowsocksr-native\win32\ssr-server\ssr_executive.obj 1
错误 LNK1120 1 个无法解析的外部命令 ssr-server E:\Source Code\shadowsocksr-native\win32\x64\Release\ssr-server.exe 1
错误 LNK2001 无法解析的外部符号 assert ssr-client E:\Source Code\shadowsocksr-native\win32\ssr-client\ssr_executive.obj 1
错误 LNK1120 1 个无法解析的外部命令 ssr-client E:\Source Code\shadowsocksr-native\win32\x64\Release\ssr-client.exe 1
错误 LNK2001 无法解析的外部符号 assert ssr-local E:\Source Code\shadowsocksr-native\win32\ssr-local\ssr_executive.obj 1
错误 LNK1120 1 个无法解析的外部命令 ssr-local E:\Source Code\shadowsocksr-native\win32\x64\Release\ssr-local.exe 1

**Comment by fuchanghao** [comment]
目前测试是需要在 ssr_executive.c 下添加 #include <assert.h>才能编译通过，当然我没做可行性测试。
