### ISSUE TITLE
关于客户端和自动化脚本问题

### ISSUE THREAD

**Issue by flowercoder** [ShadowsocksR-Live/shadowsocksr-native#106]
以前我的ssr安装方式已被完全看穿，端口几乎秒封。
只用你们的ssr，大概能坚持5min左右。
在debian9下使用你们的全自动脚本，经常会出现ca证书报错。
换成ubuntu，有时也要执行全自动脚本2-3次才能顺利装上。
客户端配置文件写错希望能增加更明确的提示（我加密方式多打了一个a，连结没影响到，查源码才知道报错是这个）
希望尽早能把全平台的问题解决掉，顺便说一声，速度比v2要快多了，谢啦~

**Comment by ssrlive** [comment]
那, 如果配置文件有任何错误, 直接拒绝执行, 报错退出, 怎样?

**Comment by flowercoder** [comment]
只要报错提示清楚，我觉得都可以：比如please check your configure file/请检查你的配置文件 诸如此类的

**Comment by flowercoder** [comment]
顺便说下，protocol 和obs的参数似乎目前没法设置，我直接去服务器的config.conf改设置，似乎也不会对客户端有什么影响，或许我对于有些只能说一知半解吧

**Comment by flowercoder** [comment]
顺便说一下protocol和obfs的参数似乎都无法设置，我直接去服务器里的config.conf去改，但似乎对于client端来说似乎不起什么作用

**Comment by ssrlive** [comment]
这里有个宏定义

https://github.com/ShadowsocksR-Live/shadowsocksr-native/blob/f6a01cafac29c7d25f61747b44b487c20f1cdca9/src/ssr_executive.c#L615

将加密部分去掉了. 你可以帮忙测试一下. 目前有个问题, 某些混淆方式有好几次数据来回, 以模拟HTTPS协议欺骗GFW, 但 SSRoT 已经是HTTPS了, 这种欺骗毫无意义. 所以你测试时将混淆设置成 plain 值, 否则会出错. 既然这个是鸡肋,几个往返又无必要.停掉好了. 

目前还没想好怎么处理这个复杂情况.

**Comment by flowercoder** [comment]
说实话，我只能看懂java，c只能看懂最基础的。你的意思是要改完后用wireshark测？然后筛选https的包来看？其实混淆的话，我大概说一下我的观察，我这几天订阅了几个免费机场的ssr，他们基本都是****.apple.com 或是****.mircosoft.com作为混淆值的，所以我才会想加参数的，具体的作用我也不懂

**Comment by ssrlive** [comment]
分别删掉这个宏定义后, 分别编译服务器和客户端. 然后以想要的配置测试看通不通.

**Comment by flowercoder** [comment]
好吧，不管怎么说，还是多谢了

**Comment by HelloAtMe** [comment]
ERROR: enc_key_init(): Illegal method. happened. I dont know how to fix it! look forward to u reply , thanks...

**Comment by flowercoder** [comment]
> ERROR: enc_key_init(): Illegal method. happened. I dont know how to fix it! look forward to u reply , thanks...

Just check your config.json, and you need double check 3rd line:     "method": "******",.If the property doesn't match your server config, just fix it,and restart your client

**Comment by WJC-POG** [comment]
我在Ubuntu18.04上面执行自动化脚本，但是提示获取网站证书失败，这是什么原因？？我有绑定域名

**Comment by flowercoder** [comment]
> 我在Ubuntu18.04上面执行自动化脚本，但是提示获取网站证书失败，这是什么原因？？我有绑定域名

多跑两次，如果是freenom的话可以不用cf，直接用freenom默认的，还有就是检查下环境，仔细看看运行后的记录，实在不行就重装镜像，我也是跑了两遍才成功

**Comment by WJC-POG** [comment]
什么是cf？？

**Comment by WJC-POG** [comment]
> > 我在Ubuntu18.04上面执行自动化脚本，但是提示获取网站证书失败，这是什么原因？？我有绑定域名
> 
> 多跑两次，如果是freenom的话可以不用cf，直接用freenom默认的，还有就是检查下环境，仔细看看运行后的记录，实在不行就重装镜像，我也是跑了两遍才成功

是不是要等解析完成才能跑？？我看到网上说要等1个小时解析完才行，服务器是vultr的

**Comment by flowercoder** [comment]
> > > 我在Ubuntu18.04上面执行自动化脚本，但是提示获取网站证书失败，这是什么原因？？我有绑定域名
> > 
> > 
> > 多跑两次，如果是freenom的话可以不用cf，直接用freenom默认的，还有就是检查下环境，仔细看看运行后的记录，实在不行就重装镜像，我也是跑了两遍才成功
> 
> 是不是要等解析完成才能跑？？我看到网上说要等1个小时解析完才行，服务器是vultr的

没错，解析不对的话也会报错，清空一下服务器的dns？或是重启一下？确定解析好了再试，这个方式很不错，就是目前的客户端少了点

**Comment by WJC-POG** [comment]
我已经都配置好了，但是在windows上运行是直接运行ssr-client这个程序吗？？

**Comment by flowercoder** [comment]
> 我已经都配置好了，但是在windows上运行是直接运行ssr-client这个程序吗？？

我在那个文件加下创建了个bat文件
@echo off
cmd /k ssr-client -c config.json
——————————————————————————————————————————
你也可以用cmd在那个放程序的目录下运行ssr-client -c config.json

**Comment by WJC-POG** [comment]
> > 我已经都配置好了，但是在windows上运行是直接运行ssr-client这个程序吗？？
> 
> 我在那个文件加下创建了个bat文件
> @echo off
> cmd /k ssr-client -c config.json
> ——————————————————————————————————————————
> 你也可以用cmd在那个放程序的目录下运行ssr-client -c config.json

这样就可以科学上网了？？还是说要配置其他东西？？

**Comment by WJC-POG** [comment]
> > 我已经都配置好了，但是在windows上运行是直接运行ssr-client这个程序吗？？
> 
> 我在那个文件加下创建了个bat文件
> @echo off
> cmd /k ssr-client -c config.json
> ——————————————————————————————————————————
> 你也可以用cmd在那个放程序的目录下运行ssr-client -c config.json

我运行后出现error  junk in handshake这样的输出信息，是不是没有成功？？

**Comment by flowercoder** [comment]
> > > 我已经都配置好了，但是在windows上运行是直接运行ssr-client这个程序吗？？
> > 
> > 
> > 我在那个文件加下创建了个bat文件
> > @echo off
> > cmd /k ssr-client -c config.json
> > ——————————————————————————————————————————
> > 你也可以用cmd在那个放程序的目录下运行ssr-client -c config.json
> 
> 这样就可以科学上网了？？还是说要配置其他东西？？



> > > 我已经都配置好了，但是在windows上运行是直接运行ssr-client这个程序吗？？
> > 
> > 
> > 我在那个文件加下创建了个bat文件
> > @echo off
> > cmd /k ssr-client -c config.json
> > ——————————————————————————————————————————
> > 你也可以用cmd在那个放程序的目录下运行ssr-client -c config.json
> 
> 我运行后出现error junk in handshake这样的输出信息，是不是没有成功？？

https://github.com/ShadowsocksR-Live/shadowsocksr-native/wiki/%E5%AE%A2%E6%88%B7%E7%AB%AF%E7%94%A8%E6%B3%95
仔细看看这个吧

**Comment by WJC-POG** [comment]
> > > > 我已经都配置好了，但是在windows上运行是直接运行ssr-client这个程序吗？？
> > > 
> > > 
> > > 我在那个文件加下创建了个bat文件
> > > @echo off
> > > cmd /k ssr-client -c config.json
> > > ——————————————————————————————————————————
> > > 你也可以用cmd在那个放程序的目录下运行ssr-client -c config.json
> > 
> > 
> > 这样就可以科学上网了？？还是说要配置其他东西？？
> 
> > > > 我已经都配置好了，但是在windows上运行是直接运行ssr-client这个程序吗？？
> > > 
> > > 
> > > 我在那个文件加下创建了个bat文件
> > > @echo off
> > > cmd /k ssr-client -c config.json
> > > ——————————————————————————————————————————
> > > 你也可以用cmd在那个放程序的目录下运行ssr-client -c config.json
> > 
> > 
> > 我运行后出现error junk in handshake这样的输出信息，是不是没有成功？？
> 
> https://github.com/ShadowsocksR-Live/shadowsocksr-native/wiki/%E5%AE%A2%E6%88%B7%E7%AB%AF%E7%94%A8%E6%B3%95
> 仔细看看这个吧

我可以用SSR去替代吗？？

**Comment by flowercoder** [comment]
> > > > > 我已经都配置好了，但是在windows上运行是直接运行ssr-client这个程序吗？？
> > > > 
> > > > 
> > > > 我在那个文件加下创建了个bat文件
> > > > @echo off
> > > > cmd /k ssr-client -c config.json
> > > > ——————————————————————————————————————————
> > > > 你也可以用cmd在那个放程序的目录下运行ssr-client -c config.json
> > > 
> > > 
> > > 这样就可以科学上网了？？还是说要配置其他东西？？
> > 
> > 
> > > > > 我已经都配置好了，但是在windows上运行是直接运行ssr-client这个程序吗？？
> > > > 
> > > > 
> > > > 我在那个文件加下创建了个bat文件
> > > > @echo off
> > > > cmd /k ssr-client -c config.json
> > > > ——————————————————————————————————————————
> > > > 你也可以用cmd在那个放程序的目录下运行ssr-client -c config.json
> > > 
> > > 
> > > 我运行后出现error junk in handshake这样的输出信息，是不是没有成功？？
> > 
> > 
> > https://github.com/ShadowsocksR-Live/shadowsocksr-native/wiki/%E5%AE%A2%E6%88%B7%E7%AB%AF%E7%94%A8%E6%B3%95
> > 仔细看看这个吧
> 
> 我可以用SSR去替代吗？？

不可以，因为它是基于ssr+websocket+tls的（如果我理解没错的话），目前这个时间只有这个方法，
如果你只用他的ssr，像我最开始写的，还是裸奔，没意义。

**Comment by WJC-POG** [comment]
> > > > > > 我已经都配置好了，但是在windows上运行是直接运行ssr-client这个程序吗？？
> > > > > 
> > > > > 
> > > > > 我在那个文件加下创建了个bat文件
> > > > > @echo off
> > > > > cmd /k ssr-client -c config.json
> > > > > ——————————————————————————————————————————
> > > > > 你也可以用cmd在那个放程序的目录下运行ssr-client -c config.json
> > > > 
> > > > 
> > > > 这样就可以科学上网了？？还是说要配置其他东西？？
> > > 
> > > 
> > > > > > 我已经都配置好了，但是在windows上运行是直接运行ssr-client这个程序吗？？
> > > > > 
> > > > > 
> > > > > 我在那个文件加下创建了个bat文件
> > > > > @echo off
> > > > > cmd /k ssr-client -c config.json
> > > > > ——————————————————————————————————————————
> > > > > 你也可以用cmd在那个放程序的目录下运行ssr-client -c config.json
> > > > 
> > > > 
> > > > 我运行后出现error junk in handshake这样的输出信息，是不是没有成功？？
> > > 
> > > 
> > > https://github.com/ShadowsocksR-Live/shadowsocksr-native/wiki/%E5%AE%A2%E6%88%B7%E7%AB%AF%E7%94%A8%E6%B3%95
> > > 仔细看看这个吧
> > 
> > 
> > 我可以用SSR去替代吗？？
> 
> 不可以，因为它是基于ssr+websocket+tls的（如果我理解没错的话），目前这个时间只有这个方法，
> 如果你只用他的ssr，像我最开始写的，还是裸奔，没意义。

安卓是不是也要和电脑是在一个局域网内才能使用？？

**Comment by flowercoder** [comment]
> > > > > > > 我已经都配置好了，但是在windows上运行是直接运行ssr-client这个程序吗？？
> > > > > > 
> > > > > > 
> > > > > > 我在那个文件加下创建了个bat文件
> > > > > > @echo off
> > > > > > cmd /k ssr-client -c config.json
> > > > > > ——————————————————————————————————————————
> > > > > > 你也可以用cmd在那个放程序的目录下运行ssr-client -c config.json
> > > > > 
> > > > > 
> > > > > 这样就可以科学上网了？？还是说要配置其他东西？？
> > > > 
> > > > 
> > > > > > > 我已经都配置好了，但是在windows上运行是直接运行ssr-client这个程序吗？？
> > > > > > 
> > > > > > 
> > > > > > 我在那个文件加下创建了个bat文件
> > > > > > @echo off
> > > > > > cmd /k ssr-client -c config.json
> > > > > > ——————————————————————————————————————————
> > > > > > 你也可以用cmd在那个放程序的目录下运行ssr-client -c config.json
> > > > > 
> > > > > 
> > > > > 我运行后出现error junk in handshake这样的输出信息，是不是没有成功？？
> > > > 
> > > > 
> > > > https://github.com/ShadowsocksR-Live/shadowsocksr-native/wiki/%E5%AE%A2%E6%88%B7%E7%AB%AF%E7%94%A8%E6%B3%95
> > > > 仔细看看这个吧
> > > 
> > > 
> > > 我可以用SSR去替代吗？？
> > 
> > 
> > 不可以，因为它是基于ssr+websocket+tls的（如果我理解没错的话），目前这个时间只有这个方法，
> > 如果你只用他的ssr，像我最开始写的，还是裸奔，没意义。
> 
> 安卓是不是也要和电脑是在一个局域网内才能使用？？

对啊。它那个安卓我没试过，其实就是在你的电脑上开个1080端口的socks5服务器，手机上我没搞，还要给它开电脑，我直接用老王了。

**Comment by ssrlive** [comment]
Added. https://github.com/ShadowsocksR-Live/shadowsocksr-native/commit/6e2bfa09f52a716071f5898a685f36639b37746f
