### ISSUE TITLE
ssr-local, ssr-client无法打开https页面

### ISSUE THREAD

**Issue by chunzhouz** [ShadowsocksR-Live/shadowsocksr-native#107]
问题描述：ubuntu在terminal下运行ssr-local -c config.json（和ssr-client -c config.json），然后用firefox可以打开http网页，能看到外国机房ip。打开https网页时，ssr-local就会报错退出。

ssr-client的日志：
ssr-client 2020/01/31 14:49  info  listening on     0.0.0.0:1080

ssr-client 2020/01/31 14:49  info  ==== tunnel created     count   1 ====
ssr-client 2020/01/31 14:49  info  ==== tunnel created     count   2 ====
ssr-client 2020/01/31 14:49  info  ==== tunnel created     count   3 ====
ssr-client: /home/#####/ssr-n/src/ssr_executive.c:454: tunnel_cipher_client_encrypt: Assertion `buf->capacity >= 2048' failed.
Aborted (core dumped)

ssr-local日志：
 2020-01-31 13:55:33 INFO: listening at 0.0.0.0:1080
 2020-01-31 13:55:58 ERROR: local_recv_cb "connection reset by peer"
Segmentation fault (core dumped)

**Comment by ssrlive** [comment]
ssr-local 已经没有维护，会在某个时候删除。
有些网站打开会有问题，目前没找到原因。
能用油管就算没有大碍。

**Comment by ssrlive** [comment]
同 #117， 已经修正。
