### ISSUE TITLE
config.json配置

### ISSUE THREAD

**Issue by sakurakatana** [ShadowsocksR-Live/shadowsocksr-native#108]
config.json具体改如何配置啊？？？

**Comment by flowercoder** [comment]
不要自己创建，用它压缩包里自带的config.json文件修改
下面是我的配置，仅供参考，还有多项配置要参考服务器的配置
{
    "password": "your password",
    "method": "aes-256-cfb",
    "protocol": "auth_aes128_md5",
    "protocol_param": "",
    "obfs": "tls1.2_ticket_auth",
    "obfs_param": "",

    "udp": false,
    "timeout": 300,

    "server_settings": {
        "listen_address": "0.0.0.0",
        "listen_port": 14009
    },

    "client_settings": {
        "server": "your host"",
        "server_port": 443,
        "listen_address": "0.0.0.0",
        "listen_port": 1080
    },

    "over_tls_settings": {
        "enable": true,
        "server_domain": "your domain",
        "path": "need fill out",
        "root_cert_file": ""
    }
}

**Comment by sakurakatana** [comment]
> 不要自己創建，用它壓縮包裡自帶的config.json文件修改
> 下面是我的配置，可以參考，還有大量配置要參考服務器的配置
> {
> “ password”：“ your password”，
> “ method” ：“ aes-256-cfb”，
> “ protocol”：“ auth_aes128_md5”，
> “ protocol_param”：“”，
> “ obfs”：“ tls1.2_ticket_auth”，
> “ obfs_param”：“”，
> 
> ```
> "udp": false,
> "timeout": 300,
> 
> "server_settings": {
>     "listen_address": "0.0.0.0",
>     "listen_port": 14009
> },
> 
> "client_settings": {
>     "server": "your host"",
>     "server_port": 443,
>     "listen_address": "0.0.0.0",
>     "listen_port": 1080
> },
> 
> "over_tls_settings": {
>     "enable": true,
>     "server_domain": "your domain",
>     "path": "need fill out",
>     "root_cert_file": ""
> }
> ```
> 
> }

好的，谢谢

**Comment by ssrlive** [comment]
https://github.com/ShadowsocksR-Live/shadowsocksr-native/wiki/%E5%85%A8%E8%87%AA%E5%8A%A8%E5%AE%89%E8%A3%85-SSRoT-%E6%9C%8D%E5%8A%A1%E5%99%A8
