### ISSUE TITLE
我发现一个问题，用你的库做的分流机制，淘宝提示正在使用vpn或者代理，但是加载图片和文字确实走的国内

### ISSUE THREAD

**Issue by aishuidedabai** [ShadowsocksR-Live/shadowsocksr-native#11]
Please answer these questions before submitting your issue. Thanks!

**Comment by ssrlive** [comment]
這個實現並不包含分流功能, 只要是路由到 SSR-Native 到流量, 通通發送到了遠端服務器, 你應該檢查你自己的代碼.

**Comment by aishuidedabai** [comment]
我知道，我用的provixy实现的，但是同样的代码在mac上正常，我抓包也发现走的国内，所以我纳闷哪里导致的，ss连接用的是你的库
