### ISSUE TITLE
Wrote file to {0}, but couldn't download {1}: {2}".format(wellknown_path, wellknown_url, e

### ISSUE THREAD

**Issue by chinausers** [ShadowsocksR-Live/shadowsocksr-native#110]
Please answe
Parsing account key...
Parsing CSR...
Found domains: www.diaoshili.world, www.www.diaoshili.world
Getting directory...
Directory found!
Registering account...
Registered!
Creating new order...
Order created!
Verifying www.diaoshili.world...
www.diaoshili.world verified!
Verifying www.www.diaoshili.world...
Traceback (most recent call last):
  File "acme_tiny.py", line 198, in <module>
    main(sys.argv[1:])
  File "acme_tiny.py", line 194, in main
    signed_crt = get_crt(args.account_key, args.csr, args.acme_dir, log=LOGGER, CA=args.ca, disable_check=args.disable_check, directory_url=args.directory_url, contact=args.contact)
  File "acme_tiny.py", line 143, in get_crt
    raise ValueError("Wrote file to {0}, but couldn't download {1}: {2}".format(wellknown_path, wellknown_url, e))
ValueError: Wrote file to /fakesite/.well-known/acme-challenge/hosGX6eSZdLazReNoY0S-660YXTzEPAVBaGFLh5notk, but couldn't download http://www.www.diaoshili.world/.well-known/acme-challenge/hosGX6eSZdLazReNoY0S-660YXTzEPAVBaGFLh5notk: Error:
Url: http://www.www.diaoshili.world/.well-known/acme-challenge/hosGX6eSZdLazReNoY0S-660YXTzEPAVBaGFLh5notk
Data: None
Response Code: None
Response: <urlopen error [Errno -2] Name or service not known>
[错误]  [CA] 获取 网站证书 失败 
wtf

**Comment by chinausers** [comment]
不知道为啥 我用
www.diaoshili.world 就不行 diaoshili.world 就可以 疑似 最后校验多加了个www

**Comment by ssrlive** [comment]
脚本里有 www 的项目. 你可以在手工安装脚本教程里找到 命令行. 那里也有 www 你如果实在不行, 可以在命令行里把 www 去掉.

**Comment by chinausers** [comment]
64.222.212.199 - - [06/Feb/2020:05:40:15 -0500] "GET / HTTP/1.1" 200 396 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36"
test.test.test.假的 - - [06/Feb/2020:05:40:17 -0500] "GET /.well-known/acme-challenge/1umuM-PRnd3sylBgE0GlYSW4u0IRn8RrcRyHPfIRrCQ HTTP/1.1" 200 87 "-" "acme-tiny"
34.222.229.130 - - [06/Feb/2020:05:40:17 -0500] "GET /.well-known/acme-challenge/1umuM-PRnd3sylBgE0GlYSW4u0IRn8RrcRyHPfIRrCQ HTTP/1.1" 200 87 "-" "Mozilla/5.0 (compatible; Let's Encrypt validation server; +https://www.letsencrypt.org)"
3.14.255.131 - - [06/Feb/2020:05:40:17 -0500] "GET /.well-known/acme-challenge/1umuM-PRnd3sylBgE0GlYSW4u0IRn8RrcRyHPfIRrCQ HTTP/1.1" 200 87 "-" "Mozilla/5.0 (compatible; Let's Encrypt validation server; +https://www.letsencrypt.org)"
18.194.58.132 - - [06/Feb/2020:05:40:17 -0500] "GET /.well-known/acme-challenge/1umuM-PRnd3sylBgE0GlYSW4u0IRn8RrcRyHPfIRrCQ HTTP/1.1" 200 87 "-" "Mozilla/5.0 (compatible; Let's Encrypt validation server; +https://www.letsencrypt.org)"
66.133.109.36 - - [06/Feb/2020:05:40:18 -0500] "GET /.well-known/acme-challenge/1umuM-PRnd3sylBgE0GlYSW4u0IRn8RrcRyHPfIRrCQ HTTP/1.1" 200 87 "-" "Mozilla/5.0 (compatible; Let's Encrypt validation server; +https://www.letsencrypt.org)"
47.89.37.225 - - [06/Feb/2020:05:44:58 -0500] "GET / HTTP/1.1" 200 396 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.87 Safari/537.36"
47.89.37.225 - - [06/Feb/2020:05:44:58 -0500] "GET /favicon.ico HTTP/1.1" 404 209 "http://www.diaoshili.world/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.87 Safari/537.36"
test.test.test.假的 - - [06/Feb/2020:05:48:02 -0500] "GET /.well-known/acme-challenge/XnpxZ1_lQUssZ7J8iaV_EA1vxr0cSnNDHt1eLhsVEKI HTTP/1.1" 200 87 "-" "acme-tiny"
18.194.58.132 - - [06/Feb/2020:05:48:03 -0500] "GET /.well-known/acme-challenge/XnpxZ1_lQUssZ7J8iaV_EA1vxr0cSnNDHt1eLhsVEKI HTTP/1.1" 200 87 "http://diaoshili.world/.well-known/acme-challenge/XnpxZ1_lQUssZ7J8iaV_EA1vxr0cSnNDHt1eLhsVEKI" "Mozilla/5.0 (compatible; Let's Encrypt validation server; +https://www.letsencrypt.org)"
3.14.255.131 - - [06/Feb/2020:05:48:03 -0500] "GET /.well-known/acme-challenge/XnpxZ1_lQUssZ7J8iaV_EA1vxr0cSnNDHt1eLhsVEKI HTTP/1.1" 200 87 "http://diaoshili.world/.well-known/acme-challenge/XnpxZ1_lQUssZ7J8iaV_EA1vxr0cSnNDHt1eLhsVEKI" "Mozilla/5.0 (compatible; Let's Encrypt validation server; +https://www.letsencrypt.org)"
66.133.109.36 - - [06/Feb/2020:05:48:03 -0500] "GET /.well-known/acme-challenge/XnpxZ1_lQUssZ7J8iaV_EA1vxr0cSnNDHt1eLhsVEKI HTTP/1.1" 200 87 "http://diaoshili.world/.well-known/acme-challenge/XnpxZ1_lQUssZ7J8iaV_EA1vxr0cSnNDHt1eLhsVEKI" "Mozilla/5.0 (compatible; Let's Encrypt validation server; +https://www.letsencrypt.org)"
test.test.test.假的 - - [06/Feb/2020:05:48:05 -0500] "GET /.well-known/acme-challenge/v7eqCWmrSea3qw9FZx0KGj8-y44VovXqp9W0nWumkTU HTTP/1.1" 200 87 "-" "acme-tiny"
34.222.229.130 - - [06/Feb/2020:05:48:06 -0500] "GET /.well-known/acme-challenge/v7eqCWmrSea3qw9FZx0KGj8-y44VovXqp9W0nWumkTU HTTP/1.1" 200 87 "-" "Mozilla/5.0 (compatible; Let's Encrypt validation server; +https://www.letsencrypt.org)"
66.133.109.36 - - [06/Feb/2020:05:48:06 -0500] "GET /.well-known/acme-challenge/v7eqCWmrSea3qw9FZx0KGj8-y44VovXqp9W0nWumkTU HTTP/1.1" 200 87 "-" "Mozilla/5.0 (compatible; Let's Encrypt validation server; +https://www.letsencrypt.org)"
3.14.255.131 - - [06/Feb/2020:05:48:06 -0500] "GET /.well-known/acme-challenge/v7eqCWmrSea3qw9FZx0KGj8-y44VovXqp9W0nWumkTU HTTP/1.1" 200 87 "-" "Mozilla/5.0 (compatible; Let's Encrypt validation server; +https://www.letsencrypt.org)"
47.89.37.225 - - [06/Feb/2020:05:59:00 -0500] "GET / HTTP/1.1" 301 194 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.87 Safari/537.36"
131.196.8.249 - - [06/Feb/2020:06:03:17 -0500] "GET / HTTP/1.1" 301 194 "-" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36"
47.89.37.225 - - [06/Feb/2020:06:09:11 -0500] "GET / HTTP/1.1" 301 194 "-" "Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; rv:11.0) like Gecko"
101.89.19.197 - - [06/Feb/2020:06:10:12 -0500] "GET / HTTP/1.1" 301 194 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:50.0) Gecko/20100101 Firefox/50.0"
47.89.37.225 - - [06/Feb/2020:06:16:22 -0500] "GET /index.html HTTP/1.1" 301 194 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.87 Safari/537.36"
113.249.248.226 - - [06/Feb/2020:06:16:38 -0500] "GET / HTTP/1.1" 301 194 "http://whois.chinaz.com/diaoshili.world" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36"
14.152.92.110 - - [06/Feb/2020:06:16:44 -0500] "GET / HTTP/1.1" 301 194 "-" "Mozilla/5.0 (compatible; Baiduspider/2.0; +http://www.baidu.com/search/spider.html)"
47.89.37.225 - - [06/Feb/2020:06:16:50 -0500] "GET /index.html HTTP/1.1" 301 194 "-" "Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; rv:11.0) like Gecko"
14.152.92.110 - - [06/Feb/2020:06:16:54 -0500] "GET / HTTP/1.1" 301 194 "-" "Mozilla/5.0 (compatible; Baiduspider/2.0; +http://www.baidu.com/search/spider.html)"
60.176.146.72 - - [06/Feb/2020:06:33:55 -0500] "GET / HTTP/1.1" 301 194 "http://diaoshili.world/" "PostmanRuntime/7.15.0"
60.176.146.72 - - [06/Feb/2020:06:33:56 -0500] "GET / HTTP/1.1" 301 194 "https://diaoshili.world/" "PostmanRuntime/7.15.0"
60.176.146.72 - - [06/Feb/2020:06:33:57 -0500] "GET / HTTP/1.1" 301 194 "https://diaoshili.world/" "PostmanRuntime/7.15.0"
60.176.146.72 - - [06/Feb/2020:06:33:57 -0500] "GET / HTTP/1.1" 301 194 "https://diaoshili.world/" "PostmanRuntime/7.15.0"
60.176.146.72 - - [06/Feb/2020:06:33:58 -0500] "GET / HTTP/1.1" 301 194 "https://diaoshili.world/" "PostmanRuntime/7.15.0"
60.176.146.72 - - [06/Feb/2020:06:34:03 -0500] "GET /index.html HTTP/1.1" 301 194 "http://diaoshili.world/index.html" "PostmanRuntime/7.15.0"
60.176.146.72 - - [06/Feb/2020:06:34:03 -0500] "GET / HTTP/1.1" 301 194 "https://diaoshili.world/" "PostmanRuntime/7.15.0"
60.176.146.72 - - [06/Feb/2020:06:34:03 -0500] "GET / HTTP/1.1" 301 194 "https://diaoshili.world/" "PostmanRuntime/7.15.0"
60.176.146.72 - - [06/Feb/2020:06:34:04 -0500] "GET / HTTP/1.1" 301 194 "https://diaoshili.world/" "PostmanRuntime/7.15.0"
60.176.146.72 - - [06/Feb/2020:06:34:04 -0500] "GET / HTTP/1.1" 301 194 "https://diaoshili.world/" "PostmanRuntime/7.15.0"
60.176.146.72 - - [06/Feb/2020:06:34:11 -0500] "GET /index.html HTTP/1.1" 301 194 "-" "PostmanRuntime/7.15.0"
60.176.146.72 - - [06/Feb/2020:06:34:11 -0500] "GET / HTTP/1.1" 301 194 "https://diaoshili.world/" "PostmanRuntime/7.15.0"
60.176.146.72 - - [06/Feb/2020:06:34:11 -0500] "GET / HTTP/1.1" 301 194 "https://diaoshili.world/" "PostmanRuntime/7.15.0"
60.176.146.72 - - [06/Feb/2020:06:34:12 -0500] "GET / HTTP/1.1" 301 194 "https://diaoshili.world/" "PostmanRuntime/7.15.0"
60.176.146.72 - - [06/Feb/2020:06:34:13 -0500] "GET / HTTP/1.1" 301 194 "https://diaoshili.world/" "PostmanRuntime/7.15.0"
60.176.146.72 - - [06/Feb/2020:06:34:13 -0500] "GET / HTTP/1.1" 301 194 "https://diaoshili.world/" "PostmanRuntime/7.15.0"
60.176.146.72 - - [06/Feb/2020:06:36:07 -0500] "GET / HTTP/1.1" 301 194 "-" "PostmanRuntime/7.15.0"
60.176.146.72 - - [06/Feb/2020:06:36:08 -0500] "GET / HTTP/1.1" 301 194 "https://diaoshili.world/" "PostmanRuntime/7.15.0"
60.176.146.72 - - [06/Feb/2020:06:36:08 -0500] "GET / HTTP/1.1" 301 194 "https://diaoshili.world/" "PostmanRuntime/7.15.0"
60.176.146.72 - - [06/Feb/2020:06:36:08 -0500] "GET / HTTP/1.1" 301 194 "https://diaoshili.world/" "PostmanRuntime/7.15.0"
60.176.146.72 - - [06/Feb/2020:06:36:09 -0500] "GET / HTTP/1.1" 301 194 "https://diaoshili.world/" "PostmanRuntime/7.15.0"
60.176.146.72 - - [06/Feb/2020:06:36:09 -0500] "GET / HTTP/1.1" 301 194 "https://diaoshili.world/" "PostmanRuntime/7.15.0"
60.176.146.72 - - [06/Feb/2020:06:36:21 -0500] "GET / HTTP/1.1" 301 194 "-" "PostmanRuntime/7.15.0"
60.176.146.72 - - [06/Feb/2020:06:36:22 -0500] "GET / HTTP/1.1" 301 194 "https://diaoshili.world/" "PostmanRuntime/7.15.0"
60.176.146.72 - - [06/Feb/2020:06:36:22 -0500] "GET / HTTP/1.1" 301 194 "https://diaoshili.world/" "PostmanRuntime/7.15.0"
60.176.146.72 - - [06/Feb/2020:06:36:23 -0500] "GET / HTTP/1.1" 301 194 "https://diaoshili.world/" "PostmanRuntime/7.15.0"
60.176.146.72 - - [06/Feb/2020:06:36:24 -0500] "GET / HTTP/1.1" 301 194 "https://diaoshili.world/" "PostmanRuntime/7.15.0"
60.176.146.72 - - [06/Feb/2020:06:36:24 -0500] "GET / HTTP/1.1" 301 194 "https://diaoshili.world/" "PostmanRuntime/7.15.0"
198.23.231.123 - - [06/Feb/2020:06:37:58 -0500] "GET / HTTP/1.1" 301 194 "-" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/20.0.1132.57 Safari/537.36"
60.176.146.72 - - [06/Feb/2020:06:39:25 -0500] "GET / HTTP/1.1" 301 194 "-" "PostmanRuntime/7.15.0"
60.176.146.72 - - [06/Feb/2020:06:39:25 -0500] "GET / HTTP/1.1" 301 194 "https://diaoshili.world/" "PostmanRuntime/7.15.0"
60.176.146.72 - - [06/Feb/2020:06:39:26 -0500] "GET / HTTP/1.1" 301 194 "https://diaoshili.world/" "PostmanRuntime/7.15.0"
60.176.146.72 - - [06/Feb/2020:06:39:26 -0500] "GET / HTTP/1.1" 301 194 "https://diaoshili.world/" "PostmanRuntime/7.15.0"
60.176.146.72 - - [06/Feb/2020:06:39:27 -0500] "GET / HTTP/1.1" 301 194 "https://diaoshili.world/" "PostmanRuntime/7.15.0"
60.176.146.72 - - [06/Feb/2020:06:39:28 -0500] "GET / HTTP/1.1" 301 194 "https://diaoshili.world/" "PostmanRuntime/7.15.0"

**Comment by chinausers** [comment]
已经解决www 问题 但是又产生新的问题...

**Comment by chinausers** [comment]
我的域名在copy 进去后不能用 有排查方式吗

**Comment by ssrlive** [comment]
![image](https://user-images.githubusercontent.com/30760636/73934493-87d33f80-4919-11ea-8cb2-ab86c228dd1e.png)
 ping 通没问题啊

**Comment by chinausers** [comment]
我想看网站

**Comment by chinausers** [comment]
怀疑证书问题

**Comment by ssrlive** [comment]
手工获取证书 什么结果

**Comment by ssrlive** [comment]
你 nginx 服务器都没开. 或者配置有问题.  明文 http 都不通.

**Comment by flowercoder** [comment]
多跑两次试试，我目前就在用，全自动脚本包好。

**Comment by chinausers** [comment]
证书好的

**Comment by ssrlive** [comment]
https://github.com/ShadowsocksR-Live/shadowsocksr-native/wiki/%E6%89%8B%E5%B7%A5%E5%AE%89%E8%A3%85-SSRoT-%E6%9C%8D%E5%8A%A1%E5%99%A8%E5%85%A8%E7%A8%8B%E8%AF%A6%E8%A7%A3#%E5%B0%86-%E6%95%B0%E5%AD%97%E5%AE%89%E5%85%A8%E8%AF%81%E4%B9%A6-%E9%83%A8%E7%BD%B2%E5%88%B0-web-%E6%9C%8D%E5%8A%A1%E5%99%A8

**Comment by ssrlive** [comment]
![Screen Shot 2020-02-06 at 19 54 34](https://user-images.githubusercontent.com/30760636/73934993-88200a80-491a-11ea-92c8-c9f9d2b74c16.png)
网站配置文件 和 nginx 重新加载.

**Comment by chinausers** [comment]
图片看不到...

**Comment by chinausers** [comment]
我用的全自动的安装,然后过程中基本正常. 除了安装依赖的时候弹了一堆框框 让我选.. 有几个瞎选的

**Comment by ssrlive** [comment]
除了域名. 其余一路回车. 都可以顺利安装.

**Comment by chinausers** [comment]
没啥区别一样的 

  server {
        listen 443 ssl;
        ssl on;
        ssl_certificate       /fakesite_cert/chained.pem;
        ssl_certificate_key   /fakesite_cert/domain.key;
        ssl_protocols         TLSv1 TLSv1.1 TLSv1.2;
        ssl_ciphers           HIGH:!aNULL:!MD5;
        server_name           diaoshili.world;
        index index.html index.htm index.nginx-debian.html;
        root  /fakesite;
        error_page 400 = /400.html;

        location /u3UIqUJoRCnjIeMb7HqE/ {
            proxy_redirect off;
            proxy_pass http://127.0.0.1:10507;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $http_host;
        }
    }

    server {
        listen 80;
        server_name diaoshili.world;
        index index.html index.htm index.nginx-debian.html;
        root  /fakesite;

        location /.well-known/acme-challenge/ {
        }

        location / {
            rewrite ^/(.*)$ https://diaoshili.world/ permanent;
        }
    }

**Comment by flowercoder** [comment]
是ubuntu吗？不是就换成ubuntu

**Comment by chinausers** [comment]
是的

**Comment by ssrlive** [comment]
反斜杠 和 美元 符号 不见了. 你原文有吗?

**Comment by chinausers** [comment]
有的

**Comment by chinausers** [comment]
我可以开个ssh 给你 稍后我会删掉他.

**Comment by ssrlive** [comment]
删掉 这个VPS 重新开始吧. 折腾没意义. 还不如留着点时间看A片.

**Comment by chinausers** [comment]
- - 66.98.125.10:28784 root  NLfCervYAhRQ

**Comment by flowercoder** [comment]
+1 18.04，重新装一个，跑完这个脚本再搞个bbr2

**Comment by chinausers** [comment]
额..

**Comment by chinausers** [comment]
18.10 俺的版本

**Comment by ssrlive** [comment]
卧槽 我操作你的VPS我至少得走三级代理才不会暴露我的IP.

**Comment by chinausers** [comment]
心有点大  我自己在琢磨琢磨

**Comment by chinausers** [comment]
你们用的是搬瓦工的ss 吗

**Comment by ssrlive** [comment]
搬瓦工是 SSRoT 的绝佳部署主机. 部署 SS/SSR 就很悲摧了.
