### ISSUE TITLE
协议问题

### ISSUE THREAD

**Issue by cart88** [ShadowsocksR-Live/shadowsocksr-native#113]
Please answer these questions before submitting your issue. Thanks!

### What version of shadowsocks-native are you using?
master

### What operating system are you using?
debian 9

### What did you do?
 ./ssr-client -c config.json

### What did you see instead?
在 auth_chain_b  salsa20  tls1.2_ticket_auth 无法正常代理上网

### What is your config in detail (with all sensitive info masked)?
```
 {
     "password": "******",
     "method": "salsa20",
     "protocol": "auth_chain_b",
     "protocol_param": "",
     "obfs": "tls1.2_ticket_auth",
     "obfs_param": "",

     "udp": false,
     "timeout": 300,

     "server_settings": {
         "listen_address": "***********************",
         "listen_port": ***********
     },

     "client_settings": {
         "server": "******************",
         "server_port": *****,
         "listen_address": "192.168.2.216",
         "listen_port": 1080
     },

     "over_tls_settings": {
         "enable": false,
         "server_domain": "************",
         "path": "/udg151df/",
         "root_cert_file": ""
     }
 }
```

root@debian:~/ssr-n/build/src# ./ssr-client -c config.json
ssr-client 2020/01/09  1:38  info  ShadowsocksR native client

ssr-client 2020/01/09  1:38  info  remote server    xxxxx******************:xxxxx
ssr-client 2020/01/09  1:38  info  method           salsa20
ssr-client 2020/01/09  1:38  info  password         **********
ssr-client 2020/01/09  1:38  info  protocol         auth_chain_b
ssr-client 2020/01/09  1:38  info  obfs             tls1.2_ticket_auth
ssr-client 2020/01/09  1:38  info  udp relay        no
ssr-client 2020/01/09  1:38  info  listening on     192.168.2.216:1080

**Comment by cart88** [comment]
origin plain 正常

**Comment by flowercoder** [comment]
如果你明白网站证书的作用，你就会明白，其他有没有那些混淆是无所谓的。当然主要原因是目前的版本不支持你设的那些混淆，我也试过了，你可以看下我的一个提问，作者回答我了

**Comment by stardock** [comment]
@cart88 auth_chain 协议不支持加密和混淆，所以你只能用 origin, plain 来搭配。

**Comment by stardock** [comment]
这个是开发协议的时候就这么设计的， 和SSROT无关。

**Comment by cart88** [comment]
"method": "salsa20",
    "protocol": "auth_chain_b",
    "protocol_param": "",
    "obfs": "tls1.2_ticket_auth",
    "obfs_param": "",
    "speed_limit_per_con": 0,
    "speed_limit_per_user": 0,
已经解决目前这样使用是支持的

**Comment by ssrlive** [comment]
已修正。不好意思拖久了。
