### ISSUE TITLE
不支持部分SSR协议

### ISSUE THREAD

**Issue by galaxy001** [ShadowsocksR-Live/shadowsocksr-native#116]
Please answer these questions before submitting your issue. Thanks!

### What version of shadowsocks-native are you using?
master

### What operating system are you using?
macOS

### What did you do?
Test `ssr-local` with `ssr-protocol=auth_aes128_md5`.

### What did you expect to see?
Works

### What did you see instead?
Not working

### What is your config in detail (with all sensitive info masked)?

```json
{
    "server": "11111111",
    "local_address": "127.0.0.1",
    "local_port": 1111,
    "timeout": 300,
    "workers": 1,
    "server_port": 11111,
    "password": "xxxxx",
    "method": "chacha20-ietf",
    "obfs": "http_simple",
    "obfs_param": "xxxxxxx",
    "protocol": "auth_aes128_md5",
    "protocol_param": "xxxxx"
}
```

**Comment by ssrlive** [comment]
没必要再支持各种乱七八糟的协议, 下一步会砍掉 混淆, 协议只支持少数几个.
