### ISSUE TITLE
ssr-client，  tunnel_cipher_client_encrypt: Assertion failed.

### ISSUE THREAD

**Issue by estoniah** [ShadowsocksR-Live/shadowsocksr-native#117]
Please answer these questions before submitting your issue. Thanks!

### What version of shadowsocks-native are you using?
shadowsocksr-native/master 2020 10/03

### What operating system are you using?
Ubuntu 18.04

### What did you do?
ssr-client -c tokyo-cfg.json 

### What did you expect to see?
这个怎么回事啊，兄弟
 tunnel_cipher_client_encrypt: Assertion `buf->capacity >= 2048' failed.

### What did you see instead?

ssr-client 2020/03/12  5:54  info  ==== tunnel created     count   1 ====
ssr-client: /home/estonio/work/ssr-n/src/ssr_executive.c:454: tunnel_cipher_client_encrypt: Assertion `buf->capacity >= 2048' failed.

### What is your config in detail (with all sensitive info masked)?

ssr-client 2020/03/12  5:54  info  remote server    202.**********:12475
ssr-client 2020/03/12  5:54  info  method           aes-256-cfb
ssr-client 2020/03/12  5:54  info  password         ss**************
ssr-client 2020/03/12  5:54  info  protocol         auth_aes128_md5
ssr-client 2020/03/12  5:54  info  obfs             http_simple
ssr-client 2020/03/12  5:54  info  udp relay        no
ssr-client 2020/03/12  5:54  info  listening on     192.168.124.12:1080

**Comment by ssrlive** [comment]
访问什么网站时出现这问题？

**Comment by estoniah** [comment]
https://bitcointalk.org/

应该和网站无关，刚装2019新版本，不能工作。

**Comment by estoniah** [comment]
你好，ssr-server工作正常， 
ssr-client也有可能是我的本机器库依赖版本混乱缘故，去先弄一空机器试试.

**Comment by ssrlive** [comment]
已经修正。感谢提出。
