### ISSUE TITLE
无法正常打开网站

### ISSUE THREAD

**Issue by Alvin9999** [ShadowsocksR-Live/shadowsocksr-native#121]
ssr-client 2020/04/11 11:37  info  ShadowsocksR native client

ssr-client 2020/04/11 11:37  info  remote server    185. ********** :443
ssr-client 2020/04/11 11:37  info  method           salsa20
ssr-client 2020/04/11 11:37  info  password         nt*******
ssr-client 2020/04/11 11:37  info  protocol         auth_chain_b
ssr-client 2020/04/11 11:37  info  obfs             tls1.2_ticket_auth
ssr-client 2020/04/11 11:37  info
ssr-client 2020/04/11 11:37  warn  over TLS         yes
ssr-client 2020/04/11 11:37  info  over TLS domain  ****
ssr-client 2020/04/11 11:37  info  over TLS path    /pJsUOakA****/
ssr-client 2020/04/11 11:37  info
ssr-client 2020/04/11 11:37  info  udp relay        no

ssr-client 2020/04/11 11:37  info  listening on     127.0.0.1:1080

ssr-client 2020/04/11 11:37  info  connecting www.youtube.com:443 ...
ssr-client 2020/04/11 11:37  info  ---- disconnected www.youtube.com:443 ----
ssr-client 2020/04/11 11:37  info  connecting www.youtube.com:443 ...
ssr-client 2020/04/11 11:37  info  connecting www.google-analytics.com:443 ...
ssr-client 2020/04/11 11:37  info  connecting www.youtube.com:443 ...
ssr-client 2020/04/11 11:37  info  ---- disconnected www.youtube.com:443 ----
ssr-client 2020/04/11 11:37  info  connecting www.google.com:443 ...
ssr-client 2020/04/11 11:37  info  connecting ssl.gstatic.com:443 ...
ssr-client 2020/04/11 11:37  info  ---- disconnected www.google.com:443 ----
ssr-client 2020/04/11 11:37  info  ---- disconnected ssl.gstatic.com:443 ----
ssr-client 2020/04/11 11:37  info  ---- disconnected www.youtube.com:443 ----
ssr-client 2020/04/11 11:37  info  connecting www.youtube.com:443 ...
ssr-client 2020/04/11 11:37  info  ---- disconnected www.youtube.com:443 ----
ssr-client 2020/04/11 11:37  info  connecting mail.google.com:443 ...
ssr-client 2020/04/11 11:37  info  ---- disconnected mail.google.com:443 ----
ssr-client 2020/04/11 11:37  info  connecting www.youtube.com:443 ...
ssr-client 2020/04/11 11:37  info  ---- disconnected www.youtube.com:443 ----
ssr-client 2020/04/11 11:37  info  ---- disconnected www.google-analytics.com:443 ----
ssr-client 2020/04/11 11:37  info  connecting clients4.google.com:443 ...
ssr-client 2020/04/11 11:37  info  connecting www.youtube.com:443 ...
ssr-client 2020/04/11 11:37  info  ---- disconnected clients4.google.com:443 ----
ssr-client 2020/04/11 11:37  info  connecting mail.google.com:443 ...
ssr-client 2020/04/11 11:37  info  connecting play.google.com:443 ...
ssr-client 2020/04/11 11:37  info  ---- disconnected www.youtube.com:443 ----
ssr-client 2020/04/11 11:37  info  ---- disconnected mail.google.com:443 ----
ssr-client 2020/04/11 11:37  info  ---- disconnected play.google.com:443 ----
ssr-client 2020/04/11 11:38  info  connecting play.google.com:443 ...
ssr-client 2020/04/11 11:38  info  connecting ssl.gstatic.com:443 ...
ssr-client 2020/04/11 11:38  info  connecting play.google.com:443 ...
ssr-client 2020/04/11 11:38  info  ---- disconnected ssl.gstatic.com:443 ----
ssr-client 2020/04/11 11:38  info  ---- disconnected play.google.com:443 ----
ssr-client 2020/04/11 11:38  info  ---- disconnected play.google.com:443 ----
ssr-client 2020/04/11 11:38  info  connecting 0.client-channel.google.com:443 ...
ssr-client 2020/04/11 11:38  info  connecting 0.client-channel.google.com:443 ...
ssr-client 2020/04/11 11:38  info  ---- disconnected 0.client-channel.google.com:443 ----
ssr-client 2020/04/11 11:38  info  connecting www.google.com:443 ...

**Comment by Alvin9999** [comment]
打开网站，页面上报这个错误：
无法访问此网站网址为 https://www.youtube.com/?gl=US 的网页可能暂时无法连接，或者它已永久性地移动到了新网址。
ERR_SOCKS_CONNECTION_FAILED

**Comment by Alvin9999** [comment]
换了几个不同的加密方式、协议、混淆，还是不行。之前是好好的，突然就不行了。

访问主域名显示：Welcome to nginx!
If you see this page, the nginx web server is successfully installed and working. Further configuration is required.

For online documentation and support please refer to nginx.org.
Commercial support is available at nginx.com.

Thank you for using nginx.

**Comment by Alvin9999** [comment]
服务器防火墙处于关闭状态。安装过程中没有任何报错。

**Comment by ssrlive** [comment]
不知道。删掉主机，重新来过。

**Comment by Alvin9999** [comment]
@ssrlive 您的意思是重装系统？

**Comment by Alvin9999** [comment]
还想请假一个问题，如果套CDN，主域名和www域名是否都要套？

**Comment by ssrlive** [comment]
为了能够快速准确地定位bug，暂时不要套 cdn。毕竟测试环境与生产环境是不同的。

**Comment by Alvin9999** [comment]
没套CDN，重装系统后，重新部署，正常。

**Comment by httpdocs** [comment]
同样遇到这个问题了，之前好好的，然后就不行了。

**Comment by ssrlive** [comment]
这种情况是不是因为网页简单。被GFW封了？

**Comment by ssrlive** [comment]
或者在翻墙服务器上用 `ps aux` 命令列出所有进程，看有没有 `ssr-server`，如果没有，就是进程崩了，重启远程主机即可。

**Comment by httpdocs** [comment]
嗯。IP检测了一下没问题。简单重启就可以解决。

**Comment by Alvin9999** [comment]
同上，又不行了，重启服务器就好了。

**Comment by ssrlive** [comment]
哪个有条件帮助测试一下？我需要知道服务器程序崩溃在哪里。🧐

**Comment by Alvin9999** [comment]
> 哪个有条件帮助测试一下程序崩溃？我需要知道服务器程序崩溃在哪里。🧐

怎么测试，如果下次又不行了，你想获得哪些数据？

**Comment by ssrlive** [comment]
这里有一些参考文献：  
[linux下利用coredump技术追查进程崩溃原因](https://blog.csdn.net/u014585564/article/details/68063269)

[由开启coredump引起的对shell的深入探究](https://blog.csdn.net/u014585564/article/details/67637166)

[GDB观察栈的内存布局](https://blog.csdn.net/u014585564/article/details/68063187)

**Comment by ssrlive** [comment]
写了一篇教程，希望都能看懂并且会操作。

https://github.com/ShadowsocksR-Live/shadowsocksr-native/wiki/%E5%B8%AE%E5%8A%A9%E4%BD%9C%E8%80%85%E6%94%B9%E5%96%84-SSRoT

**Comment by ssrlive** [comment]
@Alvin9999 @httpdocs 
安装脚本已经改写，重新安装后，遭遇 ssr-server 进程崩溃后，会自动重启进程。不会再中断了。

**Comment by Alvin9999** [comment]
@ssrlive 谢谢大佬。

**Comment by Alvin9999** [comment]
@ssrlive  大佬，请教一个问题，如果我套了CDN，此时程序崩溃并自动重启后，是否会失效？因为套了CDN，域名解析的ip会变成CDN ip，重启服务担心会失效。

**Comment by ssrlive** [comment]
不会失效。

**Comment by Alvin9999** [comment]
> 不会失效。

好

**Comment by Alvin9999** [comment]
@ssrlive  换了其它服务器，用最新的脚本安装不能使用，提示为：

打开网站，页面上报这个错误：
无法访问此网站网址为 https://www.youtube.com/?gl=US 的网页可能暂时无法连接，或者它已永久性地移动到了新网址。
ERR_SOCKS_CONNECTION_FAILED

然后换了各种系统以及不同的加密方式，防火墙也关闭了，都不行。

**Comment by ssrlive** [comment]
k客户端得同时换

**Comment by Alvin9999** [comment]
> k客户端得同时换

换客户端后可以了，谢谢你
