### ISSUE TITLE
请问shadowsocksr-native支持多用户管理和流量统计功能吗？

### ISSUE THREAD

**Issue by zdm2008** [ShadowsocksR-Live/shadowsocksr-native#125]
请问shadowsocksr-native支持多用户管理和流量统计功能吗？

**Comment by ssrlive** [comment]
目前没有，一个人再牛逼，能打几根钉？

日程表：

udp 支持
Windows GUI 全局透明翻墙支持，
Android 支持。
iOS 支持。
机场后端集成支持。
机场流量多用户支持。

你看看啥时能排到？

**Comment by zdm2008** [comment]
为什么不基于https://github.com/shadowsocks/shadowsocks-libev的源码上修改，或者只需要实现一个真正的SSL+HTTP插件就行了，亦或者直接从他们的源码扒过来。

**Comment by ssrlive** [comment]
外行话。只要你看过 那个源码，你就知道有多烂，要想把它顺利地改造成 走 TLS，比重新开始还困难。而且全平台支持，几乎不可能。但如果抛开已有知名项目，自己搞一套，让人找到、发现、发现，也是极其困难。
目前走的路线已经算是不错的了。

**Comment by ssrlive** [comment]
外行话。只要你看过 那个源码，你就知道有多烂，要想把它顺利地改造成 走 TLS，比重新开始还困难。而且全平台支持，几乎不可能。但如果抛开已有知名项目，自己搞一套，让人找到、发现、传播，也是极其困难。
目前走的路线已经算是不错的了。
