### ISSUE TITLE
ubuntu 20.04 initializing ciphers... chacha20-ietf err

### ISSUE THREAD

**Issue by 0x2d3c** [ShadowsocksR-Live/shadowsocksr-native#127]
![err screenshot](https://user-images.githubusercontent.com/20468895/80436957-f7623500-8932-11ea-81eb-ee44bfaf15d8.png)

**Comment by 0x2d3c** [comment]
@ssrlive  why?

**Comment by ssrlive** [comment]
![ddd](https://user-images.githubusercontent.com/30760636/80556862-96f0f780-8a07-11ea-9dfd-c6e294ec39a2.png)
