### ISSUE TITLE
请问如何给网站添加内容

### ISSUE THREAD

**Issue by pjctrader** [ShadowsocksR-Live/shadowsocksr-native#129]
小白一枚，请问如何给fakesite  添加内容？谢谢

**Comment by ssrlive** [comment]
扒网站， 扒拉 5 分钟之内， 强行中断 Ctr + C， 就差不多了。
https://github.com/ShadowsocksR-Live/shadowsocksr-native/wiki/%E5%88%9B%E5%BB%BA%E5%81%87%E7%BD%91%E7%AB%99

**Comment by pjctrader** [comment]
非常感谢
