### ISSUE TITLE
do_tls_init_package: Assertion `result' failed.

### ISSUE THREAD

**Issue by zeus911** [ShadowsocksR-Live/shadowsocksr-native#131]
ssr-server: /root/shadowsocksr-native/src/server/server.c:993: do_tls_init_package: Assertion `result' failed.

when me connect server show top error.

server exit.

**Comment by ssrlive** [comment]
### What is your config in detail (with all sensitive info masked)?

**Comment by zeus911** [comment]
CentOS Linux release 7.7.1908 (Core)  

i used  Deploy server and source compiled all show same error.

**Comment by ssrlive** [comment]
I mean [this file](https://github.com/ShadowsocksR-Live/shadowsocksr-native#sample-configure-file)

**Comment by zeus911** [comment]
{
    "password": "j83nYJGyFcu",
    "method": "aes-128-ctr",
    "protocol": "auth_aes128_md5",
    "protocol_param": "",
    "obfs": "tls1.2_ticket_auth",
    "obfs_param": "",

    "udp": false,
    "timeout": 300,

    "server_settings": {
        "listen_address": "0.0.0.0",
        "listen_port": 18310
    },

    "client_settings": {
        "server": "170.105.24.193",
        "server_port": 443,
        "listen_address": "0.0.0.0",
        "listen_port": 1080
    },

    "over_tls_settings": {
        "enable": true,
        "server_domain": "sslgso.gad",
        "path": "/baidu.com/",
        "root_cert_file": ""
    }
}

**Comment by ssrlive** [comment]
I just tested using the [udp branch](https://github.com/ShadowsocksR-Live/shadowsocksr-native/tree/udp) and found no problems.

![image](https://user-images.githubusercontent.com/30760636/81473299-0ea4fa80-9230-11ea-97c2-e6f133111b86.png)

**Comment by ssrlive** [comment]
After many tests, we found no problems.
