### ISSUE TITLE
安装失败

### ISSUE THREAD

**Issue by LittleWhite-Carry** [ShadowsocksR-Live/shadowsocksr-native#134]
Please answer these questions before submitting your issue. Thanks!

### What version of shadowsocks-native are you using?
0.4

### What operating system are you using?
centos7

### What did you do?
执行如下代码
```
wget --no-check-certificate https://raw.githubusercontent.com/ShadowsocksR-Live/shadowsocksr-native/master/install/ssrn-ot-install.sh
chmod +x ssrn-ot-install.sh
./ssrn-ot-install.sh 2>&1 | tee ssr-n-ot.log
```

### What did you expect to see?
安装成功

### What did you see instead?
ShadowsocksR Native install failed, please contact @ssrlive

### What is your config in detail (with all sensitive info masked)?
[ 76%] Building C object src/CMakeFiles/ssr-client.dir/cache.c.o
[ 77%] Building C object src/CMakeFiles/ssr-client.dir/encrypt.c.o
[ 77%] Building C object src/CMakeFiles/ssr-client.dir/ssrbuffer.c.o
[ 77%] Building C object src/CMakeFiles/ssr-client.dir/ssrutils.c.o
[ 77%] Building C object src/CMakeFiles/ssr-client.dir/udprelay.c.o
/root/shadowsocksr-native/src/udprelay.c: In function ‘udp_remote_launch_begin’:
/root/shadowsocksr-native/src/udprelay.c:335:11: error: missing braces around initializer [-Werror=missing-braces]
     union sockaddr_universal u_dst_addr = { 0 };
           ^
/root/shadowsocksr-native/src/udprelay.c:335:11: error: (near initialization for ‘u_dst_addr.addr_stor’) [-Werror=missing-braces]
/root/shadowsocksr-native/src/udprelay.c: In function ‘udp_remote_send_data’:
/root/shadowsocksr-native/src/udprelay.c:375:11: error: missing braces around initializer [-Werror=missing-braces]
     union sockaddr_universal u_dst_addr = { 0 };
           ^
/root/shadowsocksr-native/src/udprelay.c:375:11: error: (near initialization for ‘u_dst_addr.addr_stor’) [-Werror=missing-braces]
cc1: all warnings being treated as errors
make[2]: *** [src/CMakeFiles/ssr-client.dir/udprelay.c.o] Error 1
make[1]: *** [src/CMakeFiles/ssr-client.dir/all] Error 2
make: *** [all] Error 2
/bin/cp: cannot stat ‘./shadowsocksr-native/src/ssr-server’: No such file or directory
[Info] firewall set start...
[Warning] firewalld looks like not running or not installed, please enable port 10165 manually if necessary.
[Info] firewall set completed...
ShadowsocksR Native install failed, please contact @ssrlive

**Comment by ssrlive** [comment]
fixed.
