### ISSUE TITLE
具体该如何写客户端的配置文件？

### ISSUE THREAD

**Issue by briteming** [ShadowsocksR-Live/shadowsocksr-native#135]
我看了这里：
https://github.com/ShadowsocksR-Live/shadowsocksr-native/wiki/%E5%AE%A2%E6%88%B7%E7%AB%AF%E7%94%A8%E6%B3%95 ，不过里面只是说：
./ssr-client -c /your/path/of/config.json
并没有显示客户端的配置文件的具体内容。
能在此贴出客户端的配置文件的具体内容吗？

**Comment by ssrlive** [comment]
https://github.com/ShadowsocksR-Live/shadowsocksr-native#sample-configure-file
