### ISSUE TITLE
如何在mac上，编译shadowsocksr-native？

### ISSUE THREAD

**Issue by briteming** [ShadowsocksR-Live/shadowsocksr-native#136]
在这里https://github.com/ShadowsocksR-Live/shadowsocksr-native/releases/tag/0.8.2 ，没有mac版下载

**Comment by ssrlive** [comment]
一會兒放上去

**Comment by ssrlive** [comment]
macOS 上的编译方法 https://github.com/ShadowsocksR-Live/shadowsocksr-native#macos
