### ISSUE TITLE
请问会像v2ray+tls+ws那样有断流现象吗?

### ISSUE THREAD

**Issue by qinghuawen** [ShadowsocksR-Live/shadowsocksr-native#138]
非常感谢大佬的辛苦付出!

因为项目是基于websocket, 担心会像v2ray+tls+ws出现断流的情况.我自己编译了一下ios版本并搭建服务端试了下,确实偶尔会出现断流情况,不知道是我服务器线路太差,还是本身就有断流的问题呢?

**Comment by ssrlive** [comment]
不是断流，是速度跟不上。因为 如果你请求的是 https 网站，就会建立两次 tls 连接，一次是与 ssr 服务器，一次是与目标网站，
第一次还有个反向代理转发。
这些都非常耗时。
目前又穷又忙，抽不出时间优化。
一旦伸手要钱党国就顺藤摸瓜抓人。

 忍着点吧！

**Comment by qinghuawen** [comment]
非常感谢大佬的辛苦付出,咱们不做伸手党,如果大佬需要支援,打赏点钱作为支援是没问题的,可以贴出打赏方式,不过大佬要注意安全.
