### ISSUE TITLE
在win10下打开会自动退出

### ISSUE THREAD

**Issue by KinderLi** [ShadowsocksR-Live/shadowsocksr-native#140]
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <startup>
    <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.8" />
  </startup>
</configuration>
```

**Comment by ssrlive** [comment]
把 config.json 文件的内容贴出来.

**Comment by KinderLi** [comment]
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <startup>
    <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.8" />
  </startup>
</configuration>

没有修改任何内容

**Comment by KinderLi** [comment]
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <startup>
    <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.8" />
  </startup>
</configuration>

**Comment by KinderLi** [comment]
是需要手动创建一个config.json文件？
