### ISSUE TITLE
Udp设置

### ISSUE THREAD

**Issue by asterriya** [ShadowsocksR-Live/shadowsocksr-native#145]
如何在服务器端和客户端正确配置SSR/native来激活udp？如果我的ISP阻挡了udp协议，还能用吗？

**Comment by ssrlive** [comment]
必须是 SSRoT, 配置文件的 udp 开关必须是 true, 在vps 主机上配置能收发 udp 包.

ssrot 服务器 没有监听 udp 端口, 服务器/客户端的udp通讯是通过tcp实现的.

**Comment by asterriya** [comment]
在土库曼斯坦可以绕过UDP或QoS过滤吗？如果UDP被阻断，TCP流量在整形中。

**Comment by ssrlive** [comment]
只要 服务端/客户端 能够 tcp 通讯, 就能 udp 通讯, ISP 商家做不到 分辨 哪个是 tcp 哪个是 udp over tcp.  服务器的 vps 应该可以 发送 udp 包的, 否则就不可能进行 dns 解析.

土国的 qos 过滤情况不清楚.

**Comment by asterriya** [comment]
那么如何确定它是否能通过QoS过滤和udp阻断呢？因为我想在使用这个方案之前确定一下。还有安卓客户端什么时候发布？

**Comment by ssrlive** [comment]
关于 [Qos](https://en.wikipedia.org/wiki/Quality_of_service) 我知道的并不比你多. 你得自己找资料看.

安卓 客户端 由于涉及到 dns 代理的难题, 也就涉及到 通讯速度的问题, 这就触及到了 SSRoT 的软肋, 多次 TLS 连接, 必须解决 冗余 TLS 握手的问题, 否则通讯速度不可能提升. 这很困难.

安卓 客户端 短时间内 出不来.

**Comment by ssrlive** [comment]
安卓客户端已经开发完毕，下载链接 https://github.com/ShadowsocksR-Live/ssrDroid/releases/latest

> 还有安卓客户端什么时候发布？
