### ISSUE TITLE
反馈：新客户端+重新部署+新vps系统无法使用

### ISSUE THREAD

**Issue by Alvin9999** [ShadowsocksR-Live/shadowsocksr-native#146]
客户端是最新的，报错如下：
ssr-client 2020/06/14 13:17 error  connecting "www.youtube.com:443" failed: -4039: connection timed out
ssr-client 2020/06/14 13:17 error  connecting "www.youtube.com:443" failed.
ssr-client 2020/06/14 13:17 error  connecting "fonts.googleapis.com:443" failed: -4039: connection timed out
ssr-client 2020/06/14 13:17 error  connecting "fonts.googleapis.com:443" failed.
ssr-client 2020/06/14 13:17 error  connecting "accounts.google.com:443" failed: -4039: connection timed out
ssr-client 2020/06/14 13:17 error  connecting "accounts.google.com:443" failed.
ssr-client 2020/06/14 13:17 error  connecting "play.google.com:443" failed: -4039: connection timed out
ssr-client 2020/06/14 13:17 error  connecting "play.google.com:443" failed.
ssr-client 2020/06/14 13:17 error  connecting "www.google.com:443" failed: -4039: connection timed out
ssr-client 2020/06/14 13:17 error  connecting "www.google.com:443" failed.
ssr-client 2020/06/14 13:17 error  connecting "ssl.gstatic.com:443" failed: -4039: connection timed out
ssr-client 2020/06/14 13:17 error  connecting "ssl.gstatic.com:443" failed.
ssr-client 2020/06/14 13:17 error  connecting "ssl.gstatic.com:443" failed: -4039: connection timed out
ssr-client 2020/06/14 13:17 error  connecting "ssl.gstatic.com:443" failed.
ssr-client 2020/06/14 13:17 error  connecting "www.google.com:443" failed: -4039: connection timed out
ssr-client 2020/06/14 13:17 error  connecting "www.google.com:443" failed.
ssr-client 2020/06/14 13:17 error  connecting "mail.google.com:443" failed: -4039: connection timed out
ssr-client 2020/06/14 13:17 error  connecting "mail.google.com:443" failed.
ssr-client 2020/06/14 13:17 error  connecting "chat-pa.clients6.google.com:443" failed: -4039: connection timed out
ssr-client 2020/06/14 13:17 error  connecting "chat-pa.clients6.google.com:443" failed.
ssr-client 2020/06/14 13:17 error  connecting "0.client-channel.google.com:443" failed: -4039: connection timed out
ssr-client 2020/06/14 13:17 error  connecting "0.client-channel.google.com:443" failed.
ssr-client 2020/06/14 13:17 error  connecting "chat-pa.clients6.google.com:443" failed: -4039: connection timed out

vps系统是ubuntu 18.04+ ，重装了系统。

**Comment by ssrlive** [comment]
把 `"connect_timeout": 6,` 改成 60秒怎样?

**Comment by Alvin9999** [comment]
ssr-client 2020/06/14 14:02  info  over TLS path    /MAGGBuIvIj7kA1Utq2cd/
ssr-client 2020/06/14 14:02  info
ssr-client 2020/06/14 14:02  info  udp relay        yes

ssr-client 2020/06/14 14:02  info  listening on     0.0.0.0:1080

ssr-client 2020/06/14 14:02 error  connecting "clientservices.googleapis.com:443" failed: -4039: connection timed out
ssr-client 2020/06/14 14:02 error  connecting "accounts.google.com:443" failed: -4039: connection timed out
ssr-client 2020/06/14 14:02 error  connecting "live.github.com:443" failed: -4039: connection timed out
ssr-client 2020/06/14 14:02 error  connecting "www.youtube.com:443" failed: -4039: connection timed out
ssr-client 2020/06/14 14:02 error  connecting "update.googleapis.com:443" failed: -4039: connection timed out
ssr-client 2020/06/14 14:02 error  connecting "www.google-analytics.com:443" failed: -4039: connection timed out
ssr-client 2020/06/14 14:02 error  connecting "www.google.com:443" failed: -4039: connection timed out
ssr-client 2020/06/14 14:02 error  connecting "soqhwjrhahvt:80" failed: -4039: connection timed out
ssr-client 2020/06/14 14:02 error  connecting "svobzqs:80" failed: -4039: connection timed out
ssr-client 2020/06/14 14:02 error  connecting "dcxilhgicsqx:80" failed: -4039: connection timed out
ssr-client 2020/06/14 14:02 error  connecting "ssl.gstatic.com:443" failed: -4039: connection timed out
ssr-client 2020/06/14 14:02 error  connecting "ssl.gstatic.com:443" failed: -4039: connection timed out
ssr-client 2020/06/14 14:02 error  connecting "adservice.google.com:443" failed: -4039: connection timed out
ssr-client 2020/06/14 14:02 error  connecting "dongtaiwang.com:80" failed: -4039: connection timed out
ssr-client 2020/06/14 14:02 error  connecting "live.github.com:443" failed: -4039: connection timed out

**Comment by Alvin9999** [comment]
不行，还是一样的报错

**Comment by ssrlive** [comment]
估计 vps 本身被墙了.

**Comment by Alvin9999** [comment]
测试了，域名和ip都没有被墙。

**Comment by ssrlive** [comment]
测试特定端口才算数.

**Comment by Alvin9999** [comment]
显示443端口关闭

**Comment by ssrlive** [comment]
那只能换端口了.

**Comment by Alvin9999** [comment]
OK，试试

**Comment by Alvin9999** [comment]
ssr-client 2020/06/14 14:30  info  over TLS path    /4rzWtPp4ePCy8eeZ5EaW/
ssr-client 2020/06/14 14:30  info
ssr-client 2020/06/14 14:30  info  udp relay        yes

ssr-client 2020/06/14 14:30  info  listening on     0.0.0.0:1080

ssr-client 2020/06/14 14:30 error  connecting "www.youtube.com:443" failed: -4081: operation canceled
ssr-client 2020/06/14 14:30 error  connecting "lzawyzh:80" failed: -4081: operation canceled
ssr-client 2020/06/14 14:31 error  connecting "accounts.google.com:443" failed: -4081: operation canceled

**Comment by Alvin9999** [comment]
换了端口，检测ip+端口没问题，但还是不行

**Comment by ssrlive** [comment]
不加代理, 从浏览器访问假网站有问题吗

**Comment by Alvin9999** [comment]
用的全自动安装脚本，假网站指的是的域名吗?

**Comment by ssrlive** [comment]
是

**Comment by Alvin9999** [comment]
打不开

**Comment by ssrlive** [comment]
如果你不是专业人士,弃用这个vps吧,换一个,也就换了一个IP.

**Comment by ssrlive** [comment]
想起来了, 如果 443 端口被墙, 你可以在安装脚本询问端口号时, 输入其它端口号, 就可以了.

![image](https://user-images.githubusercontent.com/30760636/84608602-c5f2f800-aee5-11ea-81d8-815c68fde501.png)

**Comment by Alvin9999** [comment]
@ssrlive 实际上换端口以及换vps都还是不行。秒封。

**Comment by ssrlive** [comment]
什么情况? 是刚开始可以, 一段时间后就不行了?

**Comment by Alvin9999** [comment]
> 什么情况? 是刚开始可以, 一段时间后就不行了? 假网站的内容没有跟上?

用的全自动脚本，也就没有弄假网站。

**Comment by ssrlive** [comment]
还是 安装完成以后, 就 ping 不通吗?

**Comment by Alvin9999** [comment]
@ssrlive 最后一次尝试的时候，端口是通的，但还是无法访问网站。报之前的错误。

**Comment by ssrlive** [comment]
代码已经重构, 再试一把. 看看还有没问题.

**Comment by Alvin9999** [comment]
@ssrlive 好的，感谢

**Comment by Alvin9999** [comment]
请问加密方式、协议、混淆有没有推荐的参数呢？

**Comment by ssrlive** [comment]
协议 和 混淆 在 SSRoT 已经弃用, 全部归零, 只有加密方式是可用的. 一般 aes 系列就可以.

**Comment by Alvin9999** [comment]
换了新域名+新ip+重新部署+重启，还是不行，区别是不要报之前的4081错误。
ssr-client 2020/06/21 09:03  info  connecting clientservices.googleapis.com:443 ...
ssr-client 2020/06/21 09:03  info  connecting accounts.google.com:443 ...
ssr-client 2020/06/21 09:03  info  connecting live.github.com:443 ...
ssr-client 2020/06/21 09:03  info  connecting ssl.google-analytics.com:443 ...
ssr-client 2020/06/21 09:03  info  ---- disconnected clientservices.googleapis.com:443 ----
ssr-client 2020/06/21 09:03  info  ---- disconnected accounts.google.com:443 ----
ssr-client 2020/06/21 09:03  info  ---- disconnected ssl.google-analytics.com:443 ----
ssr-client 2020/06/21 09:03  info  connecting www.youtube.com:443 ...
ssr-client 2020/06/21 09:03  info  connecting accounts.google.com:443 ...
ssr-client 2020/06/21 09:03  info  connecting ssl.gstatic.com:443 ...
ssr-client 2020/06/21 09:03  info  connecting www.google-analytics.com:443 ...
ssr-client 2020/06/21 09:03  info  ---- disconnected www.youtube.com:443 ----
ssr-client 2020/06/21 09:03  info  ---- disconnected accounts.google.com:443 ----
ssr-client 2020/06/21 09:03  info  connecting www.youtube.com:443 ...
ssr-client 2020/06/21 09:03  info  connecting update.googleapis.com:443 ...
ssr-client 2020/06/21 09:03  info  ---- disconnected ssl.gstatic.com:443 ----
ssr-client 2020/06/21 09:03  info  connecting www.youtube.com:443 ...

**Comment by Alvin9999** [comment]
网址直接访问域名没有伪装网站，显示如下：
Welcome to nginx!
If you see this page, the nginx web server is successfully installed and working. Further configuration is required.

For online documentation and support please refer to nginx.org.
Commercial support is available at nginx.com.

Thank you for using nginx.

**Comment by ssrlive** [comment]
经反复测试, 新服务端/新客户端 工作正常. 没有问题.

**Comment by ssrlive** [comment]
新发布的客户端已经将普通输出隐藏掉了,只输出错误信息,你正在使用的客户端如果不是自己编译的,就肯定是旧的客户端.

**Comment by Alvin9999** [comment]
@ssrlive 好的，我再看看

**Comment by Alvin9999** [comment]
ssr-client 2020/06/22 12:20 error  [TLS] connecting "r4---sn-5uaeznr6.googlevideo.com:443" failed: -4081: operation canceled
ssr-client 2020/06/22 12:20 error  [TLS] connecting "live.github.com:443" failed: -4081: operation canceled
ssr-client 2020/06/22 12:20 error  [TLS] connecting "www.youtube.com:443" failed: -4081: operation canceled
ssr-client 2020/06/22 12:20 error  [TLS] connecting "r4---sn-5uaeznr6.googlevideo.com:443" failed: -4081: operation canceled
ssr-client 2020/06/22 12:20 error  [TLS] connecting "r4---sn-5uaeznr6.googlevideo.com:443" failed: -4081: operation canceled
ssr-client 2020/06/22 12:20 error  [TLS] connecting "fonts.gstatic.com:443" failed: -4081: operation canceled
ssr-client 2020/06/22 12:20 error  [TLS] connecting "fonts.googleapis.com:443" failed: -4081: operation canceled
ssr-client 2020/06/22 12:20 error  [TLS] connecting "i.ytimg.com:443" failed: -4081: operation canceled
ssr-client 2020/06/22 12:20 error  [TLS] connecting "yt3.ggpht.com:443" failed: -4081: operation canceled
ssr-client 2020/06/22 12:20 error  [TLS] connecting "www.youtube.com:443" failed: -4081: operation canceled
ssr-client 2020/06/22 12:20 error  [TLS] connecting "r4---sn-5uaeznr6.googlevideo.com:443" failed: -4081: operation canceled
ssr-client 2020/06/22 12:20 error  [TLS] connecting "live.github.com:443" failed: -4081: operation canceled
ssr-client 2020/06/22 12:20 error  [TLS] connecting "www.youtube.com:443" failed: -4081: operation canceled
ssr-client 2020/06/22 12:20 error  [TLS] connecting "r4---sn-5uaeznr6.googlevideo.com:443" failed: -4081: operation canceled
ssr-client 2020/06/22 12:20 error  [TLS] connecting "live.github.com:443" failed: -4081: operation canceled
ssr-client 2020/06/22 12:20 error  [TLS] connecting "r4---sn-5uaeznr6.googlevideo.com:443" failed: -4081: operation canceled
ssr-client 2020/06/22 12:20 error  [TLS] connecting "r4---sn-5uaeznr6.googlevideo.com:443" failed: -4081: operation canceled
ssr-client 2020/06/22 12:20 error  [TLS] connecting "r4---sn-5uaeznr6.googlevideo.com:443" failed: -4081: operation canceled
ssr-client 2020/06/22 12:20 error  [TLS] connecting "www.youtube.com:443" failed: -4081: operation canceled
ssr-client 2020/06/22 12:20 error  [TLS] connecting "r4---sn-5uaeznr6.googlevideo.com:443" failed: -4081: operation canceled
ssr-client 2020/06/22 12:20 error  [TLS] connecting "yt3.ggpht.com:443" failed: -4081: operation canceled
ssr-client 2020/06/22 12:20 error  [TLS] connecting "i.ytimg.com:443" failed: -4081: operation canceled
ssr-client 2020/06/22 12:20 error  [TLS] connecting "fonts.gstatic.com:443" failed: -4081: operation canceled
ssr-client 2020/06/22 12:20 error  [TLS] connecting "fonts.googleapis.com:443" failed: -4081: operation canceled
ssr-client 2020/06/22 12:20 error  [TLS] connecting "www.youtube.com:443" failed: -4081: operation canceled
ssr-client 2020/06/22 12:20 error  [TLS] connecting "www.youtube.com:443" failed: -4081: operation canceled
ssr-client 2020/06/22 12:20 error  [TLS] connecting "live.github.com:443" failed: -4081: operation canceled
ssr-client 2020/06/22 12:20 error  [TLS] connecting "0.client-channel.google.com:443" failed: -4081: operation canceled
ssr-client 2020/06/22 12:20 error  [TLS] connecting "www.youtube.com:443" failed: -4081: operation canceled

**Comment by Alvin9999** [comment]
没用默认的443端口，用的12345端口，好奇怪哦
域名也无法打开默认的伪装网站，显示的是ngin那个页面。我在想，会不会是nginx的问题，试试candy？

**Comment by ssrlive** [comment]
很奇怪为什么连接超时

**Comment by ssrlive** [comment]
4081 是因为 TLS 连接超时, 定时器在6秒钟后强行断开了连接.

**Comment by ssrlive** [comment]
VPS 不应该性能如此低下. 最便宜的谷歌云主机都可以稳定连接.

**Comment by ssrlive** [comment]
Wiki 教程里 复制伪装网站之前会删掉原网页, 因此不存在 nginx 的那个简单网页.
https://github.com/ShadowsocksR-Live/shadowsocksr-native/wiki/%E5%88%9B%E5%BB%BA%E5%81%87%E7%BD%91%E7%AB%99

**Comment by Alvin9999** [comment]
vps1CPU 2G内存，性能应该没问题，确实很奇怪

**Comment by Alvin9999** [comment]
我再换个新域名试试看

**Comment by Alvin9999** [comment]
换了新域名还是不行，推测服务没有通，因为国外ip也不打开

**Comment by ssrlive** [comment]
把你的域名 vps ip 端口 密码 电邮发我.

**Comment by Alvin9999** [comment]
已发

**Comment by ssrlive** [comment]
没收到 ssrlivebox(at)gmail(dot)com

**Comment by Alvin9999** [comment]
重新发了

**Comment by ssrlive** [comment]
服务端真有问题, 你别关 VPS 哟, 估计晚上能解决.

**Comment by ssrlive** [comment]
找到原因了, 你的 VPS 上启用了 IPv6 于是就报错了. 禁用 IPv6 的方法见 [这里](https://blog.csdn.net/u011596455/article/details/76944186)

**Comment by Alvin9999** [comment]
好的，我试试，谢谢拉

**Comment by Alvin9999** [comment]
你已经帮忙加了吗

**Comment by ssrlive** [comment]
已经加了, 否则无法确认.

**Comment by Alvin9999** [comment]
谢谢，你可以在wiki里面加这个关闭ipv6提醒大家，全自动脚本如果方便的话也可以加这个关闭ipv6
