### ISSUE TITLE
ssr-client.exe  found error: junk in handshake

### ISSUE THREAD

**Issue by zebecool** [ShadowsocksR-Live/shadowsocksr-native#15]
Please answer these questions before submitting your issue. Thanks!
win10 vs2015 compile success

**1.**
ssr server

ShadowsocksR server configure
 I  P	    : 192.168.26.123
 port	    : 2333
 password	    : ctest
 method	    : rc4-md5
 protocol	    : auth_sha1_v4
 obfs	    : tls1.2_ticket_auth
 limit count : 10

 SSR link : ssr://VlBTX0lQOjIzMzM6YXV0aF9zaGExX3Y0OnJjNC1tZDU6dGxzMS4yX3RpY2tldF9hdXRoOlkzUmxjM1E 
 SSR barcode : http://doub.pw/qr/qr.php?text=ssr://VlBTX0lQOjIzMzM6YXV0aF9zaGExX3Y0OnJjNC1tZDU6dGxzMS4yX3RpY2tldF9hdXRoOlkzUmxjM1E 

**2.**
Modify chrome browser proxy setting， proxy： 127.0.0.1  port：1080

**3.**
run client:

config.json
{
    "server" : "192.168.26.123",
    "server_port" : 2333,
    "method" : "rc4-md5",
    "server_udp_port" : 0,
    "password" : "ctest",
    "protocol" : "auth_sha1_v4",
    "protocolparam" : "",
    "obfs" : "tls1.2_ticket_auth",
    "obfsparam" : "",
    "enable" : true,
    "udp_over_tcp" : false
}

>ssr-client.exe -c config.json
ssr-client.exe:info: listening on 127.0.0.1:1080
ssr-client.exe:error: junk in handshake
ssr-client.exe:error: junk in handshake
ssr-client.exe:error: junk in handshake

What's wrong?  thanks!!

**Comment by ssrlive** [comment]
track it by yourself. wrong with the config.
