### ISSUE TITLE
为什么能连上，但是有很多错误红字！

### ISSUE THREAD

**Issue by xuanlanlinghun** [ShadowsocksR-Live/shadowsocksr-native#150]
``ssr-client 2020/07/10 05:03 error  [TLS] connecting "alive.github.com:443" failed: -4081: operation canceled
ssr-client 2020/07/10 05:03 error  [TLS] connecting "mtalk.google.com:443" failed: -4081: operation canceled
ssr-client 2020/07/10 05:04 error  [TLS] connecting "mtalk.google.com:443" failed: -4081: operation canceled
ssr-client 2020/07/10 05:04 error  [TLS] connecting "avatars2.githubusercontent.com:443" failed: -4081: operation canceled
ssr-client 2020/07/10 05:04 error  [TLS] connecting "avatars3.githubusercontent.com:443" failed: -4081: operation canceled
ssr-client 2020/07/10 05:04 error  [TLS] connecting "user-images.githubusercontent.com:443" failed: -4081: operation canceled
ssr-client 2020/07/10 05:04 error  [TLS] connecting "avatars2.githubusercontent.com:443" failed: -4081: operation canceled
ssr-client 2020/07/10 05:04 error  [TLS] connecting "github.com:443" failed: -4081: operation canceled
ssr-client 2020/07/10 05:04 error  [TLS] connecting "github.com:443" failed: -4081: operation canceled
ssr-client 2020/07/10 05:04 error  [TLS] connecting "alive.github.com:443" failed: -4081: operation canceled
ssr-client 2020/07/10 05:04 error  [TLS] connecting "avatars2.githubusercontent.com:443" failed: -4081: operation canceled
ssr-client 2020/07/10 05:04 error  [TLS] connecting "avatars3.githubusercontent.com:443" failed: -4081: operation canceled
ssr-client 2020/07/10 05:04 error  [TLS] connecting "user-images.githubusercontent.com:443" failed: -4081: operation canceled
ssr-client 2020/07/10 05:04 error  [TLS] connecting "avatars2.githubusercontent.com:443" failed: -4081: operation canceled
ssr-client 2020/07/10 05:04 error  [TLS] connecting "github.com:443" failed: -4081: operation canceled
ssr-client 2020/07/10 05:04 error  [TLS] connecting "alive.github.com:443" failed: -4081: operation canceled
ssr-client 2020/07/10 05:05 error  [TLS] connecting "alive.github.com:443" failed: -4081: operation canceled
ssr-client 2020/07/10 05:05 error  [TLS] connecting "alive.github.com:443" failed: -4081: operation canceled
ssr-client 2020/07/10 05:05 error  [TLS] connecting "alive.github.com:443" failed: -4081: operation canceled

**Comment by xuanlanlinghun** [comment]
感觉能用，就是有点断流的样子，稍显不爽！知道怎么修复吗，是什么原因！

**Comment by ssrlive** [comment]
网速不快.

**Comment by xuanlanlinghun** [comment]
把 "connect_timeout": 6, 从 6 秒改成 60秒怎样?红字会减掉吗？

**Comment by ssrlive** [comment]
不一定

**Comment by xuanlanlinghun** [comment]
很卡，没法用，小鸡是cn线路，没那么差的

**Comment by ssrlive** [comment]
估计是服务端频繁崩溃, 有bug 你把 VPS 的 ip 密码 发给我.

**Comment by xuanlanlinghun** [comment]
能凑合用，就是很多红字，显示好几个错误数字码，什么原因，还有占用内存很大，2G内存用掉1.5G了，不是反代是特色么，为啥弄个本地伪装站？

**Comment by ssrlive** [comment]
希望能查看一下你的运行现场.
