### ISSUE TITLE
生成证书失败

### ISSUE THREAD

**Issue by GaryMMM** [ShadowsocksR-Live/shadowsocksr-native#156]
2020-08-04 02:59:18 (15.7 MB/s) - ‘acme_tiny.py’ saved [11513/11513]

Parsing account key...
Parsing CSR...
Found domains: 52site.top, www.52site.top
Getting directory...
Directory found!
Registering account...
Registered!
Creating new order...
Order created!
Verifying 52site.top...
Traceback (most recent call last):
  File "acme_tiny.py", line 198, in <module>
    main(sys.argv[1:])
  File "acme_tiny.py", line 194, in main
    signed_crt = get_crt(args.account_key, args.csr, args.acme_dir, log=LOGGER, CA=args.ca, disable_check=args.disable_check, directory_url=args.directory_url, contact=args.contact)
  File "acme_tiny.py", line 143, in get_crt
    raise ValueError("Wrote file to {0}, but couldn't download {1}: {2}".format(wellknown_path, wellknown_url, e))
ValueError: Wrote file to /fakesite/.well-known/acme-challenge/LGip88rq14O4hB4Aw44-Tw-BCdxxflrZrGh0ptbl47w, but couldn't download http://52site.top/.well-known/acme-challenge/LGip88rq14O4hB4Aw44-Tw-BCdxxflrZrGh0ptbl47w: Error:
Url: http://52site.top/.well-known/acme-challenge/LGip88rq14O4hB4Aw44-Tw-BCdxxflrZrGh0ptbl47w
Data: None
Response Code: 404
Response: <html>
<head><title>404 Not Found</title></head>
<body bgcolor="white">
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.14.0 (Ubuntu)</center>
</body>
</html>

**[Error]  [CA] Obtain website certificate Failed**

www.和不带www的域名都可以正常解析，端口80 可通

**Comment by ssrlive** [comment]
```
mkdir -p /fakesite/.well-known/acme-challenge/
```
这一句有没有报错?

**Comment by ssrlive** [comment]
再试一把

**Comment by GaryMMM** [comment]
mkdir -p /fakesite/.well-known/acme-challenge/ 这个没有报错的。
在生成证书的时候，无论自动还是手动，都是会报这个404的错误，就是访问这个URL的时候 http://xxxx/.well-known/acme-challenge/jhJOcaM57pALDRlBnL5FhJo4o--_uoXuxeLznhLyHDo
但是域名和解析我确定是没有问题的，这个一长串字符的文件也在acme-challenge目录下面。

**Comment by ssrlive** [comment]
是不是 nginx 的用户权限哪里出问题了?

**Comment by ssrlive** [comment]
奇怪的现象.

**Comment by ssrlive** [comment]
难道试新版 Linux 发行版的问题?

**Comment by GaryMMM** [comment]
权限都是使用的root账户操作的。。。
ubuntu 1804， GCP上的

**Comment by ssrlive** [comment]
nginx 的工作进程是运行在 nginx 账号权限下的.

**Comment by ssrlive** [comment]
把 `/fakesite/.well-known/acme-challenge/` 目录授权给 nginx 账号可读可写以后怎样?

**Comment by GaryMMM** [comment]
抱歉打扰，应该是我nginx的问题，我kill 掉进程后，重新跑了一遍，可以了，打扰打扰，多谢。
