### ISSUE TITLE
Connecting Failed 4077： Connection reset by peer 错误

### ISSUE THREAD

**Issue by zdf0221** [ShadowsocksR-Live/shadowsocksr-native#157]
Please answer these questions before submitting your issue. Thanks!

### What is your config in detail (with all sensitive info masked)?
<pre>
 {
    "password": "XXXXXX",
    "method": "aes-128-ctr",
    "protocol": "auth_aes128_md5",
    "protocol_param": "",
    "obfs": "tls1.2_ticket_auth",
    "obfs_param": "",

    "udp": true,
    "idle_timeout": 300,
    "connect_timeout": 6,
    "udp_timeout": 6,

    "server_settings": {
        "listen_address": "0.0.0.0",
        "listen_port": 9295
    },

    "client_settings": {
        "server": "XXX.XX.XX.XXX",
        "server_port": 443,
        "listen_address": "0.0.0.0",
        "listen_port": 1080
    },

    "over_tls_settings": {
        "enable": true,
        "server_domain": "XXX.XXX",
        "path": "/FgzjZqmduZzmr2bdE81u/",
        "root_cert_file": ""
    }
}
</pre>

![QQ图片20200804183122](https://user-images.githubusercontent.com/9160607/89284986-2bf83200-d682-11ea-8c14-a7db9c605f9e.png)

**Comment by zdf0221** [comment]
![QQ图片20200804183122](https://user-images.githubusercontent.com/9160607/89285152-75e11800-d682-11ea-9ea4-8c330d080517.png)

**Comment by ssrlive** [comment]
网络质量的问题.
