### ISSUE TITLE
IDEA通过代理连接创建个PR不行 能告诉我4081怎么查吗?

### ISSUE THREAD

**Issue by chinausers** [ShadowsocksR-Live/shadowsocksr-native#158]
日志：
sr-client 2020/08/13 16:26 error  [TLS] connecting "github.com:443" failed: -4081: operation canceled
ssr-client 2020/08/13 16:27 error  [TLS] connecting "54.169.195.247:443" failed: -4081: operation canceled
ssr-client 2020/08/13 16:27 error  [TLS] connecting "www.baidu.com:443" failed: -4081: operation canceled
ssr-client 2020/08/13 16:27 error  [TLS] connecting "ss0.baidu.com:443" failed: -4081: operation canceled
ssr-client 2020/08/13 16:27 error  [TLS] connecting "dss1.baidu.com:443" failed: -4081: operation canceled
ssr-client 2020/08/13 16:27 error  [TLS] connecting "sp1.baidu.com:443" failed: -4081: operation canceled
ssr-client 2020/08/13 16:27 error  [TLS] connecting "ss0.baidu.com:443" failed: -4081: operation canceled
ssr-client 2020/08/13 16:27 error  [TLS] connecting "timg01.bdimg.com:443" failed: -4081: operation canceled
ssr-client 2020/08/13 16:28 error  [TLS] connecting "alive.github.com:443" failed: -4081: operation canceled

**Comment by ssrlive** [comment]
不知道你啥意思。
