### ISSUE TITLE
这说明是不是https 也不安全了

### ISSUE THREAD

**Issue by chinausers** [ShadowsocksR-Live/shadowsocksr-native#159]
![image](https://user-images.githubusercontent.com/27771529/90508269-fd9e4a80-e189-11ea-9140-0de33fc7ec5b.png)

**Comment by ssrlive** [comment]
DSB Packet Tracer 是个著名的数据包模拟器，这些混混在糊弄他们的傻逼上司呢。
真 TLS 类型的数据流被 GFW 识别出来的唯一可能是，反代的入口路径字符串是 `/ray`, `/abc123`, `/pornhub` 之类的送分题给 GFW 的识别引擎，这怪不到 TLS-type 翻墙软件的头上。

**Comment by ssrlive** [comment]
https://www.netacad.com/zh-hans/courses/packet-tracer
![image](https://user-images.githubusercontent.com/30760636/90514925-70142800-e194-11ea-909c-d7d3deaa34da.png)
