### ISSUE TITLE
可以提供移动端项目可编译途径么感谢

### ISSUE THREAD

**Issue by Mondaydream** [ShadowsocksR-Live/shadowsocksr-native#16]
Please answer these questions before submitting your issue. Thanks!
new code
### What version of shadowsocks-libev are you using?
for ssr

### What operating system are you using?
iOS

### What did you do?
try to link this library to an iOS project.

### What did you see instead?
not work

### What is your config in detail (with all sensitive info masked)?
再次打扰了，根据linux的编译的code，尝试集成进入xcode还是有很多的编译错误，作者可以提供一个移动端可以编译的集成条件么，包括我看到作者您的ssrmac中的shadowsocksr-native target 跟ShadowsocksR-live有一些区别

**Comment by ssrlive** [comment]
你可以把ssrMac的工程文件稍微转换一下就可以用于iOS. 作为开发人员不能要求别人给你什么都递你手里. 正确的姿势是给开源项目提PR贡献代码.

**Comment by Mondaydream** [comment]
提出这个issue也是由于你的ssrmac项目根据readme的编译集成之后，项目缺少ssr-native，只是从头文件名字判断与live的区别，能理解你的烦躁，正确姿势正在努力去做，如果可以，可以有偿集成你的lib，需要您的帮助。

**Comment by Mondaydream** [comment]
@aishuidedabai 我放弃了这边这个途径，采用另外一个小伙子维护的分支，目前功能已经齐全ok。

**Comment by rc452860** [comment]
@Mondaydream 有地址吗？围观一下。

**Comment by zhangzhe192608** [comment]
@Mondaydream 有地址么？我也想看看
