### ISSUE TITLE
windows 1909 无法运行ssr-client

### ISSUE THREAD

**Issue by chinausers** [ShadowsocksR-Live/shadowsocksr-native#160]
![image](https://user-images.githubusercontent.com/27771529/90516856-2da01a80-e197-11ea-920c-3c4948d1a673.png)

**Comment by chinausers** [comment]
已经尝试使用管理员来启动此程序 同时也尝试过使用兼容模式来用

**Comment by ssrlive** [comment]
http://notesofaprogrammer.blogspot.com/2019/09/windows-10-complaining-permission.html
