### ISSUE TITLE
可以build一个MacOS的库吗？

### ISSUE THREAD

**Issue by GitTouch** [ShadowsocksR-Live/shadowsocksr-native#162]
自己编译的用不了

**Comment by ssrlive** [comment]
不知你还缺什么。
https://github.com/ShadowsocksR-Live/shadowsocksr-native/releases/latest

**Comment by GitTouch** [comment]
emm... 修改了 src/CMakeLists.txt 215行 #add_library(libssr-native ${SOURCE_FILES_LOCAL}) 的注释 ,编译出来的静态库用不了，但是同时编译的ssr-local 和 ssr-client 都是可以用的 。
使用的时候报错的都是加密的方法log如下:
[log.txt](https://github.com/ShadowsocksR-Live/shadowsocksr-native/files/5128987/log.txt)
我自己觉得应该是编译的时候哪里出了问题，但是不知道是什么问题，有可能是加密的库没有被包进去，编译日志如下
[compilelog.txt](https://github.com/ShadowsocksR-Live/shadowsocksr-native/files/5128993/compilelog.txt)
我用的是MacOS10.12系统编译和调用的，今天搞了一整天了，还是没有弄除了，哎，求大神帮帮我啊，，，生无可恋。。。

**Comment by ssrlive** [comment]
你在第 256 行

https://github.com/ShadowsocksR-Live/shadowsocksr-native/blob/a9254a4ce7da36c39045c79a83290f34637fc0ca/src/CMakeLists.txt#L254-L258

插入如下代码，就可以编译出一个静态库来。
```
add_library(ssr-native ${SOURCE_FILES_CLIENT})
set_target_properties(ssr-native PROPERTIES COMPILE_DEFINITIONS MODULE_LOCAL)
target_link_libraries(ssr-native ${ss_lib_net} uv-mbed)

```

**Comment by GitTouch** [comment]
谢啦，大哥，我等会去试试（^^）
