### ISSUE TITLE
可以发一个CentOS6的编译教程吗？

### ISSUE THREAD

**Issue by fivetime** [ShadowsocksR-Live/shadowsocksr-native#165]
可以发一个CentOS6的编译教程吗？
我目前有个机器必须是CentOS6的，尝试了一下编译不通过，原因可能在libuv上

```
CMake Error at CMakeLists.txt:33 (add_subdirectory):
  The source directory

    /data/software/shadowsocksr-native/depends/libuv

  does not contain a CMakeLists.txt file.
```

**Comment by ssrlive** [comment]
不能。搞不定 cmake。算了吧！

你可以直接下载编译好的二进制文件， 
https://github.com/ShadowsocksR-Live/shadowsocksr-native/releases

**Comment by fivetime** [comment]
编译好的二进制文件能在CentOS 6.x上运行吗？

**Comment by ssrlive** [comment]
试试看？

**Comment by fivetime** [comment]
尝试运行了一下，不能在CentOS 6.x上运行
```
./ssr-server -c config.json 
错误：
./ssr-server: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by ./ssr-server)
```

**Comment by ssrlive** [comment]
google 关键词 `/lib64/libc.so.6: version `GLIBC_2.14' not found` 看看能不能找到解决方案。
注意，这是一个很危险的操作，可能把系统搞挂掉，你可以在另一台 centos 6.x 上先做一遍。

**Comment by fivetime** [comment]
可以了，升级glibc就能用

···
./ssr-server -c config.json 
ssr-server 2020/09/29 05:49  info  ShadowsocksR native server

ssr-server 2020/09/29 05:49  info  listen port      8001
ssr-server 2020/09/29 05:49  info  method           none
ssr-server 2020/09/29 05:49  info  password         password
ssr-server 2020/09/29 05:49  info  protocol         origin
ssr-server 2020/09/29 05:49  info  obfs             plain
ssr-server 2020/09/29 05:49  info   
ssr-server 2020/09/29 05:49  warn  over TLS         yes
ssr-server 2020/09/29 05:49  info  over TLS domain  localhost
ssr-server 2020/09/29 05:49  info  over TLS path    /ss
ssr-server 2020/09/29 05:49  info   
ssr-server 2020/09/29 05:49  info  udp relay        yes
···

附：提供github现成的CentOS6.x升级glibc脚步
[https://gist.github.com/harv/f86690fcad94f655906ee9e37c85b174](url)

**Comment by ssrlive** [comment]
Good works.
