### ISSUE TITLE
Windows平台下全局代理无法使用

### ISSUE THREAD

**Issue by GitTouch** [ShadowsocksR-Live/shadowsocksr-native#166]
Windows 下设置系统代理无法上网，报的错误是
junk in handshake

**Comment by ssrlive** [comment]
知道。垃圾微软二十年过去了，都不直接支持SOCKS5代理，你可以使用前置代理 Privoxy 来让微软的垃圾浏览器 Edge 可以走代理。

https://github.com/ssrlive/Privoxy/releases

**Comment by GitTouch** [comment]
多谢
