### ISSUE TITLE
安装好一直提示报错无法上网

### ISSUE THREAD

**Issue by lszhwxa** [ShadowsocksR-Live/shadowsocksr-native#168]
![ssr1](https://user-images.githubusercontent.com/57699051/95655903-26fda600-0b3d-11eb-9ec9-a106f4d0167d.jpg)
![ssr3](https://user-images.githubusercontent.com/57699051/95655905-2c5af080-0b3d-11eb-93b1-ed430afc7c7a.jpg)
![ssr2](https://user-images.githubusercontent.com/57699051/95655906-2e24b400-0b3d-11eb-961d-a28c7d8a4994.jpg)

如图所示，麻烦帮忙解决，谢谢。

**Comment by ssrlive** [comment]
看不懂。 你想监听v2已经占用的端口？

**Comment by lszhwxa** [comment]
> 
> 
> 看不懂。 你想监听v2已经占用的端口？
