### ISSUE TITLE
[Error]  [CA] Obtain website certificate Failed 

### ISSUE THREAD

**Issue by yongqingxie** [ShadowsocksR-Live/shadowsocksr-native#170]
Please answer these questions before submitting your issue. Thanks!

ubuntu 18.04+ 使用一键安装脚本  安装失败 
![TIM截图20201011141816](https://user-images.githubusercontent.com/24885976/95671698-a25a6880-0bcc-11eb-9c2b-02da77d683ae.jpg)

**Comment by ssrlive** [comment]
不堪其扰，脚本已改，重新下载脚本，再来一次。

**Comment by yongqingxie** [comment]
> 不堪其扰，脚本已改，重新下载脚本，再来一次。

重新下载脚本 安装也是一样错误..... 在验证网站域名就会出现错误 关掉CDN加速也会出现错误
开启CDN
`Found domains: www.euservproxy.liorggi.ga, euservproxy.liorggi.ga
Getting directory...
Directory found!
Registering account...
Registered!
Creating new order...
Order created!
Verifying euservproxy.liorggi.ga...
Traceback (most recent call last):
  File "acme_tiny.py", line 198, in <module>
    main(sys.argv[1:])
  File "acme_tiny.py", line 194, in main
    signed_crt = get_crt(args.account_key, args.csr, args.acme_dir, log=LOGGER, CA=args.ca, disable_check=args.disable_check, directory_url=args.directory_url, contact=args.contact)
  File "acme_tiny.py", line 149, in get_crt
    raise ValueError("Challenge did not pass for {0}: {1}".format(domain, authorization))
ValueError: Challenge did not pass for euservproxy.liorggi.ga: {u'status': u'invalid', u'challenges': [{u'status': u'invalid', u'validationRecord': [{u'url': u'http://euservproxy.liorggi.ga/.well-known/acme-challenge/2nsTZrwctS5RaY9oLhBerp9XkDzIUPcJj-QVsvpmsk8', u'hostname': u'euservproxy.liorggi.ga', u'addressUsed': u'2606:4700:3030::6812:2584', u'port': u'80', u'addressesResolved': [u'104.18.37.132', u'104.18.36.132', u'172.67.193.159', u'2606:4700:3030::6812:2584', u'2606:4700:3035::6812:2484', u'2606:4700:3032::ac43:c19f']}, {u'url': u'https://euservproxy.liorggi.ga/.well-known/acme-challenge/2nsTZrwctS5RaY9oLhBerp9XkDzIUPcJj-QVsvpmsk8', u'hostname': u'euservproxy.liorggi.ga', u'addressUsed': u'2606:4700:3035::6812:2484', u'port': u'443', u'addressesResolved': [u'172.67.193.159', u'104.18.36.132', u'104.18.37.132', u'2606:4700:3035::6812:2484', u'2606:4700:3030::6812:2584', u'2606:4700:3032::ac43:c19f']}], u'url': u'https://acme-v02.api.letsencrypt.org/acme/chall-v3/7811018589/4rmyQw', u'token': u'2nsTZrwctS5RaY9oLhBerp9XkDzIUPcJj-QVsvpmsk8', u'error': {u'status': 403, u'type': u'urn:ietf:params:acme:error:unauthorized', u'detail': u'Invalid response from https://euservproxy.liorggi.ga/.well-known/acme-challenge/2nsTZrwctS5RaY9oLhBerp9XkDzIUPcJj-QVsvpmsk8 [2606:4700:3035::6812:2484]: "<!DOCTYPE html>\\n\\n<!--[if IE 7]>    <html class=\\"no-js "'}, u'type': u'http-01'}], u'identifier': {u'type': u'dns', u'value': u'euservproxy.liorggi.ga'}, u'expires': u'2020-10-18T06:42:00Z'}`
关闭CDN
`Found domains: www.euservproxy.liorggi.ga, euservproxy.liorggi.ga
Getting directory...
Directory found!
Registering account...
Registered!
Creating new order...
Order created!
Verifying euservproxy.liorggi.ga...
euservproxy.liorggi.ga verified!
Verifying www.euservproxy.liorggi.ga...
Traceback (most recent call last):
  File "acme_tiny.py", line 198, in <module>
    main(sys.argv[1:])
  File "acme_tiny.py", line 194, in main
    signed_crt = get_crt(args.account_key, args.csr, args.acme_dir, log=LOGGER, CA=args.ca, disable_check=args.disable_check, directory_url=args.directory_url, contact=args.contact)
  File "acme_tiny.py", line 143, in get_crt
    raise ValueError("Wrote file to {0}, but couldn't download {1}: {2}".format(wellknown_path, wellknown_url, e))
ValueError: Wrote file to /fakesite/.well-known/acme-challenge/3LRvGFpBZx1EObCMkWu-y7f5InL0j4ngmXLxeVmHqWc, but couldn't download http://www.euservproxy.liorggi.ga/.well-known/acme-challenge/3LRvGFpBZx1EObCMkWu-y7f5InL0j4ngmXLxeVmHqWc: Error:
Url: http://www.euservproxy.liorggi.ga/.well-known/acme-challenge/3LRvGFpBZx1EObCMkWu-y7f5InL0j4ngmXLxeVmHqWc
Data: None
Response Code: None
Response: <urlopen error [Errno -5] No address associated with hostname>
`

**Comment by ssrlive** [comment]
`www.euservproxy.liorggi.ga` 表明你用的就是 旧脚本，你下载新脚本之前得
```
rm -rf *
```
删掉所有旧东西。

**Comment by yongqingxie** [comment]
> `www.euservproxy.liorggi.ga` 表明你用的就是 旧脚本，你下载新脚本之前得
> 
> ```
> rm -rf *
> ```
> 
> 删掉所有旧东西。

已解决
