### ISSUE TITLE
报错 [Error] Installing crontab Failed

### ISSUE THREAD

**Issue by yjs0370** [ShadowsocksR-Live/shadowsocksr-native#172]
centos debian 安装均报错

Error: Package: glibc-headers-2.17-307.el7.1.x86_64 (base)
           Requires: kernel-headers >= 2.2.1
Error: Package: glibc-headers-2.17-307.el7.1.x86_64 (base)
           Requires: kernel-headers
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
[Error]  Installing crontab Failed

**Comment by ssrlive** [comment]
运行完
```
        curl http://vault.centos.org/5.7/os/x86_64/CentOS/kernel-headers-2.6.18-274.el5.x86_64.rpm -o kernel-headers.rpm
        rpm -ivh kernel-headers.rpm
```
再试看看，还报错吗？

**Comment by ssrlive** [comment]
```
yum install kernel-headers --disableexcludes=all
```
看看这个，[来源](https://www.node35.com/how-to-fix-missing-kernel-headers-on-centos-7/)

**Comment by yjs0370** [comment]
优秀！解决
