### ISSUE TITLE
 [CA] Obtain website certificate Failed 

### ISSUE THREAD

**Issue by qq854012410** [ShadowsocksR-Live/shadowsocksr-native#173]
Parsing account key...
Parsing CSR...
Found domains: xiaolin.tk
Getting directory...
Directory found!
Registering account...
Registered!
Creating new order...
Traceback (most recent call last):
  File "acme_tiny.py", line 198, in <module>
    main(sys.argv[1:])
  File "acme_tiny.py", line 194, in main
    signed_crt = get_crt(args.account_key, args.csr, args.acme_dir, log=LOGGER, CA=args.ca, disable_check=args.disable_check, directory_url=args.directory_url, contact=args.contact)
  File "acme_tiny.py", line 121, in get_crt
    order, _, order_headers = _send_signed_request(directory['newOrder'], order_payload, "Error creating new order")
  File "acme_tiny.py", line 60, in _send_signed_request
    return _do_request(url, data=data.encode('utf8'), err_msg=err_msg, depth=depth)
  File "acme_tiny.py", line 46, in _do_request
    raise ValueError("{0}:\nUrl: {1}\nData: {2}\nResponse Code: {3}\nResponse: {4}".format(err_msg, url, data, code, resp_data))
ValueError: Error creating new order:
Url: https://acme-v02.api.letsencrypt.org/acme/new-order
Data: {"protected": "eyJ1cmwiOiAiaHR0cHM6Ly9hY21lLXYwMi5hcGkubGV0c2VuY3J5cHQub3JnL2FjbWUvbmV3LW9yZGVyIiwgImFsZyI6ICJSUzI1NiIsICJub25jZSI6ICIwMDAyOVZLYmY0NU84WTRLcEpfemtxb3d2Q2Uyb1E5WFR6UzlRTldFV2NxXzJPVSIsICJraWQiOiAiaHR0cHM6Ly9hY21lLXYwMi5hcGkubGV0c2VuY3J5cHQub3JnL2FjbWUvYWNjdC85OTE3ODEyOCJ9", "payload": "eyJpZGVudGlmaWVycyI6IFt7InR5cGUiOiAiZG5zIiwgInZhbHVlIjogInhpYW9saW4udGsifV19", "signature": "kYDL-AVrxQXkVwO2T-jleO8CGeBKGfAYoF3Gw8j81nlkqlZHHF9xTv-y8tSihWiBOV_-h_O1cE5_7QivMB0esB99v5C4ywxFtYT9CT14L-uM4Y28zEPmFwOh0N70ig5cd4WJHf-T-1d229sj398ZquBAmVxXAF2we7ZZBPExBkJjd75bvkF5WaR63sF9AViZADfped7ItLTGWvs6Aozks5gMLo0d50gG-UF9D5tS4bTqYmMGtQ8WhzR8wTNTehAvHGivZtNug8HeJTDzU5F4DFVc8OC2dLsp5dQItv9CUR-4M16VOBkGTSHpwel7mLpe-LJqyVkXEZcPtYBHpBer_PE_YEONaz2j3k0XqNslrYRmW48tOfzLFc85ejYKpKKptOSeGoTkGOInwxDMlxdFTruBleKgOSW6KrqfQSzOHpmn4DpW2Mor91ToX49oRTjqBxSh_McjCHwXnRl07YVFgc1Ot5ryk3TdBNHmZOjDJ7aNaqCvampe4ygToowxcWGRvsFkMmzsYVOZpYKuWg8-n0L65zUFnCQOtB9ISe8_FwJB67xrHb3gCPPtP5mdJE7KS5sJCgD_UuUaKF873FhK3CgQv9u-uvq4-VduvnPpZ16lnGw3dlHQVmW2zo0c2iDCFJoiMgiSooT-rcMe-oA_Gf3x-xtL3AoBYVsKPDfKAbQ"}
Response Code: 429
Response: {u'status': 429, u'type': u'urn:ietf:params:acme:error:rateLimited', u'detail': u'Error creating new order :: too many certificates already issued for exact set of domains: xiaolin.tk: see https://letsencrypt.org/docs/rate-limits/'}
[Error]  [CA] Obtain website certificate Failed

**Comment by qq854012410** [comment]
求解决方法

**Comment by ssrlive** [comment]
没戏。只能换个主机，换个域名才能继续搞了。
https://github.com/ShadowsocksR-Live/shadowsocksr-native/wiki/%E6%89%8B%E5%B7%A5%E5%AE%89%E8%A3%85-SSRoT-%E6%9C%8D%E5%8A%A1%E5%99%A8%E5%85%A8%E7%A8%8B%E8%AF%A6%E8%A7%A3#lets-encrypt%E8%AF%81%E4%B9%A6%E7%94%B3%E8%AF%B7%E9%A2%91%E7%8E%87%E7%9A%84%E9%99%90%E5%88%B6
