### ISSUE TITLE
更新服务端的代码是什么啊

### ISSUE THREAD

**Issue by howa4037** [ShadowsocksR-Live/shadowsocksr-native#174]
如题 没有找到啊

**Comment by ssrlive** [comment]
自己编译. 复制. 或者干脆重新安装.

**Comment by ssrlive** [comment]
自己编译. 替换. 或者干脆重新安装. 或者使用下面这些命令

```
curl https://github.com/ShadowsocksR-Live/shadowsocksr-native/releases/latest/download/ssr-native-linux-x64.zip -o ssrn.zip
unzip ssrn.zip ssr-server
chmod +x ${ssr_dir}/ssr-server
rm -rf ssrn.zip

rm /usr/bin/ssr-server
mv ssr-server /usr/bin/

```

**Comment by ssrlive** [comment]
已经编写成脚本了。以下命令就可以自动更新。
```
sudo -i
wget https://raw.githubusercontent.com/ShadowsocksR-Live/shadowsocksr-native/master/install/update-server.sh
bash update-server.sh
```

**Comment by howa4037** [comment]
> 已经编写成脚本了。以下命令就可以自动更新。
> 
> ```shell
> 须藤-i
> rm -rf更新服务器.sh
> wget https://raw.githubusercontent.com/ShadowsocksR-Live/shadowsocksr-native/master/install/update-server.sh
> chmod + x update-server.sh
> ./update-server.sh
> ```
> 
> 执行完毕以后，如果出现绿色的`active (running)`字样，表示升级成功，如​​下图。
> 
> ![图片](https://user-images.githubusercontent.com/30760636/96358628-f53b9f00-113b-11eb-8f95-e4ccdedc7f48.png)
> 
> Wiki链接[https://github.com/ShadowsocksR-Live/shadowsocksr-native/wiki/%E5%85%A8%E8%87%AA%E5%8A%A8%E5%AE%89%E8%A3%85 -SSRoT-％E6％9C％8D％E5％8A％A1％E5％99％A8＃％E6％9B％B4％E6％96％B0％E7％8E％B0％E6％9C％89-ssrot-％ E6％9C％8D％E5％8A％A1％E7％AB％AF％E6％96％B9％E6％B3％95](https://github.com/ShadowsocksR-Live/shadowsocksr-native/wiki/%E5%85%A8%E8%87%AA%E5%8A%A8%E5%AE%89%E8%A3%85-SSRoT-%E6%9C%8D%E5%8A%A1%E5%99%A8#%E6%9B%B4%E6%96%B0%E7%8E%B0%E6%9C%89-ssrot-%E6%9C%8D%E5%8A%A1%E7%AB%AF%E6%96%B9%E6%B3%95)

感谢  这下方便多了
