### ISSUE TITLE
debian10安装时连不上服务器，一键安装脚本也连不上服务器

### ISSUE THREAD

**Issue by yjwqf** [ShadowsocksR-Live/shadowsocksr-native#176]
fatal: unable to access 'https://github.com/ShadowsocksR-Live/shadowsocksr-native.git/': Failed to connect to github.com port 443: Network is unreachable

Please answer these questions before submitting your issue. Thanks!

**Comment by ssrlive** [comment]
把你vps 的 ip 和 密码 电邮发给我。 我看看

ssrlivebox(at)gmail(dot)com

**Comment by ssrlive** [comment]
估计是 DNS 解析又出问题了。 把它改回去看看吧。
```
echo -e "nameserver 2001:67c:2b0::4\nnameserver 2001:67c:2b0::6" > /etc/resolv.conf
```

**Comment by ssrlive** [comment]
如果还有问题，把这个网站上的所有网址都试一遍。 https://nat64.xyz/

**Comment by ssrlive** [comment]
刚才查看了一下，我想你的问题已经解决了。

**Comment by yjwqf** [comment]
换了dns安装没问题，不过装完并不能翻墙。
----- 原始邮件 -----
发件人：ssrlive <notifications@github.com>
收件人：ShadowsocksR-Live/shadowsocksr-native <shadowsocksr-native@noreply.github.com>
抄送人：yjwqf <yjwqf@sina.com>,  Author <author@noreply.github.com>
主题：Re:_[ShadowsocksR-Live/shadowsocksr-native]_debian10安装时连不上服务器，一键安装脚本也连不上服务器_(#176)
日期：2020年10月28日 13点26分



刚才查看了一下，我想你的问题已经解决了。



&mdash;

**Comment by ssrlive** [comment]
我在vps上试过，应该可以翻墙。

**Comment by ssrlive** [comment]
再换个DNS吧。

**Comment by yjwqf** [comment]
一直显示tls错误
ssr-client 2020/10/28 17:46 error  [TLS] websocket error at "beacons.gcp.gvt2.com:443" with status: OK
ssr-client 2020/10/28 17:46  info  ---- disconnected  "beacons.gcp.gvt2.com:443" ----
ssr-client 2020/10/28 17:46  info  ==== tunnel destroyed   count   0 ====
----- 原始邮件 -----
发件人：ssrlive <notifications@github.com>
收件人：ShadowsocksR-Live/shadowsocksr-native <shadowsocksr-native@noreply.github.com>
抄送人：yjwqf <yjwqf@sina.com>,  Author <author@noreply.github.com>
主题：Re:_[ShadowsocksR-Live/shadowsocksr-native]_debian10安装时连不上服务器，一键安装脚本也连不上服务器_(#176)
日期：2020年10月28日 15点51分



我在vps上试过，应该可以翻墙。



&mdash;

**Comment by ssrlive** [comment]
刚换了一个纽伦堡的DNS，好了。

Germany / Nürnberg | 2a01:4f8:c2c:123f::1

**Comment by ssrlive** [comment]
以后你自己换着DNS玩儿。

**Comment by ssrlive** [comment]
https://github.com/ShadowsocksR-Live/shadowsocksr-native/wiki/%E5%85%A8%E8%87%AA%E5%8A%A8%E5%AE%89%E8%A3%85-SSRoT-%E6%9C%8D%E5%8A%A1%E5%99%A8#ipv6-only-%E4%B8%BB%E6%9C%BA%E4%B8%8A%E5%AE%89%E8%A3%85-ssrot-%E6%9C%8D%E5%8A%A1%E7%AB%AF%E4%B8%93%E7%94%A8%E8%84%9A%E6%9C%AC%E4%B8%8D%E8%A6%81%E4%B9%B1%E7%94%A8

**Comment by yjwqf** [comment]
非常感谢！
----- 原始邮件 -----
发件人：ssrlive <notifications@github.com>
收件人：ShadowsocksR-Live/shadowsocksr-native <shadowsocksr-native@noreply.github.com>
抄送人：yjwqf <yjwqf@sina.com>,  Author <author@noreply.github.com>
主题：Re:_[ShadowsocksR-Live/shadowsocksr-native]_debian10安装时连不上服务器，一键安装脚本也连不上服务器_(#176)
日期：2020年10月28日 18点31分



刚换了一个纽伦堡的DNS，好了。

Germany / Nürnberg | 2a01:4f8:c2c:123f::1



&mdash;
