### ISSUE TITLE
EUSERV最近运行一直报错，试着重新安装SSROT，多次出现[Error]  [nginx] copy files Failed ，一点头绪也没有啊！

### ISSUE THREAD

**Issue by isaac574** [ShadowsocksR-Live/shadowsocksr-native#177]
服务器安装平台是DEBIAN 10 64位的。用的代码是
wget --no-check-certificate https://raw.githubusercontent.com/ShadowsocksR-Live/shadowsocksr-native/master/install/ssrn-ot-install-ipv6.sh
chmod +x ssrn-ot-install-ipv6.sh
./ssrn-ot-install-ipv6.sh 2>&1 | tee ssr-n-ot.log
试着用UBUNTU 18.04，结果也是一样的。

**Comment by ssrlive** [comment]
按照 https://nat64.xyz/ 提供的IP，逐个试着改DNS，逐个试验。我也没更好的解决方案。

**Comment by ssrlive** [comment]
EUserv 的如果搞不定，就去薅羊毛 heroku 更简单。

**Comment by isaac574** [comment]
好的，多谢建议。的确我只用二个DNS, echo -e "nameserver 2001:67c:2b0::4\nnameserver 2001:67c:2b0::6" > /etc/resolv.conf，按油管上的博主小小白给出的。

**Comment by isaac574** [comment]
> 
> 
> 按照 https://nat64.xyz/ 提供的IP，逐个试着改DNS，逐个试验。我也没更好的解决方案。

您好，echo -e "nameserver 2a09:11c0:f1:bbf0::70\nnameserver 2001:67c:2b0::4\nnameserver 2001:67c:2b0::6" > /etc/resolv.conf
以上您给出代码中第一个DNS，好像我在https://nat64.xyz/ 列表中没有找到啊！

**Comment by ssrlive** [comment]
那是某网友提供的，没在那个网站上列出。

**Comment by ssrlive** [comment]
DNS 查询的结果不是恒定不变的，有可能过几天就失灵了，过几天又恢复了，所以多准备两个线路，一旦失灵可以紧急抢修。

**Comment by isaac574** [comment]
多谢大虾指点，今天重装SSROT成功！ 不过还是连不到油管和GOOGLE；看其它英文网站速度非常慢，看来还是HEROKU坚挺。今后如再有问题，也不轻易卸载SSROT了。
