### ISSUE TITLE
请问安装完ssrot翻墙可以查询到服务器ip正常吗？

### ISSUE THREAD

**Issue by lszhwxa** [ShadowsocksR-Live/shadowsocksr-native#178]
我使用谷歌云debian系统自动脚本安装的ssrot，同时在cloudflare中设置A记录域名和服务器ip并点成已代理。然后使用全局代理浏览各种查询ip的网站，都可以查询到谷歌云服务器的真实ip，我在想既然已经在cloudflare中设置了代理难道不是显示cloudflare的IP吗？本人小白，不太懂，望解答，谢谢。

非常感谢您的贡献。

**Comment by ssrlive** [comment]
这个问题你可以问 cloudflare。 当我设置如下图后，dns查询到的就**可能**是 真实IP。

![](https://user-images.githubusercontent.com/30760636/95162995-870ce900-07d9-11eb-841f-0e37dc5d0fa4.png)

**Comment by ssrlive** [comment]
如果被GFW封了，在cloudflare上改个域名，改个dns查询就又可以了，没啥事儿。
