### ISSUE TITLE
Can you release the 32-bit version of Windows?

### ISSUE THREAD

**Issue by zdm2008** [ShadowsocksR-Live/shadowsocksr-native#179]
Can you release the 32-bit version of Windows?

**Comment by ssrlive** [comment]
https://github.com/ShadowsocksR-Live/shadowsocksr-native/releases/latest

ssr-native-windows-x86.zip

**Comment by zdm2008** [comment]
It only contains Windows 64-bit application, which I want to run on Windows 32-bit computers.

**Comment by zdm2008** [comment]
Oh, I'm sorry, I saw x86, which belongs to Windows 32-bit application.

**Comment by zdm2008** [comment]
But I can't find any linux 32-bit applications, and there are still a lot of 32-bit operating systems on some low-processing devices.

**Comment by ssrlive** [comment]
I don't know how to build a 32-bit linux binary.

**Comment by ssrlive** [comment]
done.
ssr-native-linux-x86.zip
