### ISSUE TITLE
Cannot compile on Fedora 27 x86_64

### ISSUE THREAD

**Issue by mia0x75** [ShadowsocksR-Live/shadowsocksr-native#18]
$ git clone https://github.com/ShadowsocksR-Live/shadowsocksr-native.git
$ cd shadowsocksr-native/
$ git submodule update --init
$ git submodule foreach -q 'git checkout $(git config -f $toplevel/.gitmodules submodule.$name.branch || echo master)'
$ cmake CMakeLists.txt && make
-- The CXX compiler identification is GNU 7.3.1
-- Check for working CXX compiler: /bin/c++
-- Check for working CXX compiler: /bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Perl: /bin/perl (found version "5.26.1") 
Can't open perl script "/usr/local/src/shadowsocksr-native/scripts/config.pl": No such file or directory
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of off64_t
-- Check size of off64_t - done
-- Looking for fseeko
-- Looking for fseeko - found
-- Looking for unistd.h
-- Looking for unistd.h - found
CMake Deprecation Warning at depends/pcre/staticbuild/CMakeLists.txt:6 (CMAKE_POLICY):
  The OLD behavior for policy CMP0026 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.

-- Looking for dirent.h
.
.
.
-- Check size of unsigned long long - done
-- Found PCRE: /usr/local/src/shadowsocksr-native/depends/pcre/staticbuild (found version "..") 
.
.
.
autoreconf: running: automake --add-missing --copy --no-force
configure.ac:50: installing './compile'
configure.ac:12: installing './config.guess'
configure.ac:12: installing './config.sub'
configure.ac:6: installing './install-sh'
configure.ac:6: installing './missing'
Makefile.am:13: error: Libtool library used but 'LIBTOOL' is undefined
Makefile.am:13:   The usual way to define 'LIBTOOL' is to add 'LT_INIT'
Makefile.am:13:   to 'configure.ac' and run 'aclocal' and 'autoconf' again.
Makefile.am:13:   If 'LT_INIT' is in 'configure.ac', make sure
Makefile.am:13:   its definition is in aclocal's search path.
Makefile.am: installing './depcomp'
parallel-tests: installing './test-driver'
autoreconf: automake failed with exit status: 1
checking for a BSD-compatible install... /bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make sets $(MAKE)... (cached) yes
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
Multi-threaded support disabled. Use --enable-threading to enable.
RDRAND Hardware RNG Hash Seed disabled. Use --enable-rdrand to enable
checking whether make supports nested variables... (cached) yes
checking for style of include used by make... GNU
checking for gcc... gcc
.
.
.
checking if .gnu.warning accepts long strings... no
/usr/local/src/shadowsocksr-native/depends/json-c/staticbuild/../configure: line 5132: LT_INIT: command not found
checking for -Bsymbolic-functions linker flag... yes
checking whether C compiler accepts -Wall... yes
checking whether C compiler accepts -Werror... yes
checking whether C compiler accepts -Wcast-qual... yes
checking whether C compiler accepts -Wno-error=deprecated-declarations... yes
checking whether C compiler accepts -Wextra... yes
checking whether C compiler accepts -Wwrite-string... no
checking whether C compiler accepts -Wno-unused-parameter... yes
checking whether C compiler accepts -D_GNU_SOURCE... yes
checking whether C compiler accepts -D_REENTRANT... yes
checking size of int... 4
checking size of long... 8
checking size of long long... 8
checking size of size_t... 8
checking size of int64_t... 8
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: error: cannot find input file: `Makefile.in'
CMake Error at depends/json-c/staticbuild/CMakeLists.txt:47 (file):
  file COPY cannot find
  "/usr/local/src/shadowsocksr-native/depends/json-c/staticbuild/../config.h".

CMake Error at depends/json-c/staticbuild/CMakeLists.txt:48 (file):
  file COPY cannot find
  "/usr/local/src/shadowsocksr-native/depends/json-c/staticbuild/../json_config.h".

-- Configuring incomplete, errors occurred!
See also "/usr/local/src/shadowsocksr-native/CMakeFiles/CMakeOutput.log".
See also "/usr/local/src/shadowsocksr-native/CMakeFiles/CMakeError.log".

**Comment by ssrlive** [comment]
I have no Fedora environment. maybe the following commands are helpful.
```
sudo su                       # using root account
yum install --no-install-recommends build-essential autoconf libtool asciidoc xmlto -y
yum install git gcc g++ cmake automake -y
yum -f install
yum update
yum upgrade
```

**Comment by mia0x75** [comment]
thanks for reply, after installing libtool, only 1 warning message left

Can't open perl script "/usr/local/src/github.com/mia0x75/shadowsocksr-native/scripts/config.pl": No such file or directory

**Comment by ssrlive** [comment]
It's no matter.
