### ISSUE TITLE
Questions about timeout configuration.

### ISSUE THREAD

**Issue by zdm2008** [ShadowsocksR-Live/shadowsocksr-native#180]
Why is there only "timeout": 300 in the configuration example file of Windows, but "idle_timeout": 300, "connect_timeout": 6, and "udp_timeout": 6 in the configuration examples of linux and mac?

**Comment by ssrlive** [comment]
replace 
```
"timeout": 300,
``
with
```
"idle_timeout": 300, 
"connect_timeout": 6, 
"udp_timeout": 6
```
It's new format.
