### ISSUE TITLE
Windows的exe程序结束不掉，必要强制kill

### ISSUE THREAD

**Issue by fivetime** [ShadowsocksR-Live/shadowsocksr-native#181]
没有加-d参数的情况下，在Windows下用CreateProcess创建的包装进程终止不了，必须要强制在任务栏kill掉，可是强制kill必须要管理员权限，请问是做了什么限制吗？

**Comment by ssrlive** [comment]
加入 -f 参数，在 ctrl+c 后，过三秒就强制退出了。

**Comment by ssrlive** [comment]
估计 CreateProcess 函数的调用方法没有用对，在它调用完就直接退出，不用死等。

**Comment by ssrlive** [comment]
自有 Windows 客户端已经开发完毕，你可以试用看看。
https://github.com/ShadowsocksR-Live/ssrWin/releases/latest
