### ISSUE TITLE
tls设置了后怎么继续呢？

### ISSUE THREAD

**Issue by WangFeiFei** [ShadowsocksR-Live/shadowsocksr-native#183]
普通模式没有问题，但是开了ssrot后，就不行了，也不知道怎么连，怎么都试了。
服务器的转发应该是没有问题的，复制了一个人家的配置。
location /boom/
{
    proxy_redirect off;
    proxy_pass http://127.0.0.1:12475;
    proxy_http_version 1.1;
    proxy_set_header Upgrade \$http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host \$http_host;
}

1.本地用ssr连服务器的443带协议，监听sock5-1080，不行
2 本地直接socks5连服务器ssr-client socks5 ，不行
3 本地ssr-client连服务器443/12475，监听1080，本地再socks5-1080,不行。

谷歌了不少，试了各种路子。都不得行，老哥指点我一下。
自己弄个ssr自己用，隔三叉四被封。

**Comment by ssrlive** [comment]
Wiki说得不能再详细了啊。而且特别照顾了生手。

**Comment by WangFeiFei** [comment]
> Wiki说得不能再详细了啊。而且特别照顾了生手。

我竟然没看到wiki在哪，我去找找。谢谢😜
