### ISSUE TITLE
ssr-native支持标准的 Unix domain socket 来传输数据吗？

### ISSUE THREAD

**Issue by fivetime** [ShadowsocksR-Live/shadowsocksr-native#184]
ssr-native支持标准的 Unix domain socket 来传输数据吗？
我想前端的nginx和后端的ssr-native采用/dev/shm/ssr-native.sock的内存文件传输，可以吗？

**Comment by ssrlive** [comment]
没有。你把相关资料发我看看，才能决定怎么弄。
