### ISSUE TITLE
Client can TCP-send to server, but no response, if protocol is auth_aes128_sha1

### ISSUE THREAD

**Issue by johnx7271** [ShadowsocksR-Live/shadowsocksr-native#185]
### What version of shadowsocks-native are you using?

It happens to almost all free servers by 科学加速云， 
if the protocol is auth_aes128_sha1.
Alghouth I dont know the server origin and version, my guess is, this is a universal problem, i.e. it applies to all SSR servers regardless of origin and version.

The client is https://github.com/HMBSbige/ShadowsocksR-Windows, version 5.1.10 (latest).
It also happens to other ssr client. My guess is, it happens to all flavors of SSR clients.

The config:
"server" : "aga.ohss.icu",
"server_port" : 10003,
"server_udp_port" : 0,
"password" : "2Lf9t3",
"method" : "aes-256-cfb",
"protocol" : "auth_aes128_sha1",
"protocolparam" : "89574:IQ4tdH",
"obfs" : "plain",
"obfsparam" : "ce83489574.microsoft.com",

There are many other servers from 科学加速云, you can find it through google.

### What operating system are you using?
win 8.1

### What did you expect to see?

I expect the ssr server and ssr client should work as when the protocol is plain.

I did some debugging step-following, I found that the clients can successfully tcp-send to the server, but no reply. My guess is there is mis-match at the protocol level between server and client, so the server does not understand the client.

**Comment by ssrlive** [comment]
We can't be compatible with all ssr implementations, so for simplicity, please use the code from https://github.com/ShadowsocksR-Live/shadowsocksr as the server and then test it with ssr-client as the client.

Please report the results of the test in a follow up post here.

**Comment by ssrlive** [comment]
See [this link](https://github.com/ShadowsocksR-Live/ssrMac/issues/15#issuecomment-731100411).
