### ISSUE TITLE
SSROT怎么添加反向代理

### ISSUE THREAD

**Issue by uxgsiwy5swdo** [ShadowsocksR-Live/shadowsocksr-native#186]
我是个小白，按照全自动教程搭建之后，配置文件填写VPS IP地址和域名可以正常上网，但是怎么添加反向代理，配置文件该怎么修改啊。还有，SSROT怎么卸载。

**Comment by ssrlive** [comment]
https://github.com/ShadowsocksR-Live/shadowsocksr-native/wiki/%E6%89%8B%E5%B7%A5%E5%AE%89%E8%A3%85-SSRoT-%E6%9C%8D%E5%8A%A1%E5%99%A8%E5%85%A8%E7%A8%8B%E8%AF%A6%E8%A7%A3#%E5%B0%86-%E6%95%B0%E5%AD%97%E5%AE%89%E5%85%A8%E8%AF%81%E4%B9%A6-%E9%83%A8%E7%BD%B2%E5%88%B0-web-%E6%9C%8D%E5%8A%A1%E5%99%A8

https://github.com/ShadowsocksR-Live/shadowsocksr-native/blob/master/README.md#deploy-server
