### ISSUE TITLE
Example of client with tls and path

### ISSUE THREAD

**Issue by sae13** [ShadowsocksR-Live/shadowsocksr-native#188]
Where i can find a client json config with tls and path on port 443?

**Comment by ssrlive** [comment]
[Here](https://github.com/ShadowsocksR-Live/shadowsocksr-native/wiki/%E5%85%A8%E8%87%AA%E5%8A%A8%E5%AE%89%E8%A3%85-SSRoT-%E6%9C%8D%E5%8A%A1%E5%99%A8).

Help yourself.

**Comment by sae13** [comment]
Thanks, sadly i dont know Chinese, i'll google translate 
I would appreciate if some one share a json config or ssr example.
All i find are plain 
Not tls

ssr://NDUuNzkuOTYuMTA0OjgwOTk6b3JpZ2luOmFlcy0yNTYtY2ZiOnBsYWluOlpVbFhNRVJ1YXpZNU5EVTBaVFp1VTNkMWMzQjJPVVJ0VXpJd01YUlJNRVEvP29iZnNwYXJhbT01THVZNkxTNVUxTlM1ck9vNVlhTU9taDBkSEE2THk5MExtTnVMMFZIU2tsNWNtdyZwcm90b3BhcmFtPWRDNXRaUzlUVTFKVFZVSSZyZW1hcmtzPVFGTlRVbE5WUWkzbnZvN2xtNzFCTURJdDVMdVk2TFM1VTFOUzVvNm82STJRT25RdVkyNHZSVWRLU1hseWJBJmdyb3VwPWRDNXRaUzlUVTFKVFZVSQ

**Comment by sae13** [comment]
I wrote 
`path=/X50IdN4GdFsHcK54QuRl/;tls;host=srv1-http.myserveraddress.com`
In obfsparam but didnt work

**Comment by ssrlive** [comment]
You must use a dedicated SSRoT client, to connect to the SSRoT server.

[Clients](https://github.com/ShadowsocksR-Live/shadowsocksr-native/wiki/%E5%AE%A2%E6%88%B7%E7%AB%AF%E7%94%A8%E6%B3%95)

We all live in authoritarian states, and we all face a common enemy.

**Comment by sae13** [comment]
> You must use a dedicated SSRoT client, to connect to the SSRoT server.
> 
> [Clients](https://github.com/ShadowsocksR-Live/shadowsocksr-native/wiki/%E5%AE%A2%E6%88%B7%E7%AB%AF%E7%94%A8%E6%B3%95)
> 
> We all live in authoritarian states, and we all face a common enemy.

Thats not problem, problem is i dont know how to config

**Comment by ssrlive** [comment]
https://palitechsociety.blogspot.com/2019/08/shadowsocksr-over-tls-ssrot-server.html

**Comment by sae13** [comment]
Sorry i couldnt  make my point.
I have an already configured  ssr server 
And i have android client 
https://github.com/xxf098/shadowsocksr-v2ray-trojan-android/releases/tag/v3.8.6

But i cant configure my android app to connect server. 
My email is saeb@riseup.net 
Can you please send me an email and i tell u my server config.js and help me i configure android client?

**Comment by sae13** [comment]
My android client configuration is like this:
But it doesnt connect to my server
!(my ssr client)[https://axbabak.ir/uploads/ef58Screenshot-20201218-160459.png]

**Comment by ssrlive** [comment]
SSRoT Android client NOT completed yet!

**Comment by sae13** [comment]
Ow ok! I get that now! Ill use v2ray-plugin again, i wanted something with free client for ios. I thought it will work with potasto
