### ISSUE TITLE
Prebuild devel packages vs compiling from source

### ISSUE THREAD

**Issue by mia0x75** [ShadowsocksR-Live/shadowsocksr-native#19]
How about add dependencies for libuv-devel, libsodium-devel, zlib-devel, mbedtls-devel, json-c-devel pcre-devel or pcre2-devel while compiling them from source?

**Comment by ssrlive** [comment]
no. i hate the .dylib .so files etc.

**Comment by ssrlive** [comment]
If you are an expert in Linux server development, I hope you can help solve this problem.
ssr-server works well on Windows OS but not on Linux OS.
and i add the following lines but it's not work. 

https://github.com/ShadowsocksR-Live/shadowsocksr-native/blob/master/src/client/tunnel.c#L88

![0](https://files.gitter.im/breakwa11/shadowsocksr/amBu/Untitled.png)

![1](https://files.gitter.im/breakwa11/shadowsocksr/Vs6u/image.png)
