### ISSUE TITLE
CPU使用率100%

### ISSUE THREAD

**Issue by luwanjia** [ShadowsocksR-Live/shadowsocksr-native#190]
![image](https://user-images.githubusercontent.com/23115071/103860896-71b89b00-50f7-11eb-9032-119e6367fb03.png)

**Comment by ssrlive** [comment]
那个时刻你做了哪些上网操作?

**Comment by luwanjia** [comment]
没有干啥，master分支直接编译的，fedora33系统，功能没问题，就是cpu总是100%

**Comment by ssrlive** [comment]
已修正。你测试一把？

**Comment by luwanjia** [comment]
Good job!
已验证，问题修复。
