### ISSUE TITLE
客户端和服务端是有版本对应要求的吗

### ISSUE THREAD

**Issue by godlikejoke** [ShadowsocksR-Live/shadowsocksr-native#193]
大佬好！
今天部署了一台新的vps，使用最新的shadowsocksr-native脚本安装代码，ios端iShadowsocksR发现无论怎么样都无法连接上。
然而以前安装部署的服务器却可以连接，最后实在没有办法抱着试一试的心态更新了最新的客户端iShadowsocksR，竟然可以连接上最新的这台服务器(同时旧的vps也连接不上了)。
所以shadowsocksr-native项目的版本号和iShadowsocksR的版本号有对应的表吗
或者我vps可以选择性安装指定版本吗
希望大佬回答！

**Comment by ssrlive** [comment]
放弃向后兼容吧。都用最新版本。

**Comment by godlikejoke** [comment]
大佬回答好快！
意思是现在已经0.9.0 不往后兼容了是吧，
以后是大版本不往后兼容吗，例如以后1.0.0不兼容0.9.0，而0.9.5兼容0.9.0吗

**Comment by ssrlive** [comment]
不是的。只有 0.9.0 是个坎，以后的版本都会不变的。

**Comment by godlikejoke** [comment]
好的，谢谢大佬，0.9.0写着不往后兼容，我自己没有看到，自己傻逼了。
