### ISSUE TITLE
请问项目有可以配置拦截违法地址吗

### ISSUE THREAD

**Issue by godlikejoke** [ShadowsocksR-Live/shadowsocksr-native#194]
首先大佬您好！
    请问项目有可以配置拦截违法地址吗
    例如有些敏感网站或者迅雷这些大流量下载想屏蔽它，可以在服务端配置吗

**Comment by ssrlive** [comment]
没有这些功能。本项目的初衷是方便墙内民众绕开GFW的审查，而不是整套的完备翻墙产业链解决方案。虽然一直往这方面努力，然单兵作战的力量毕竟有限。

**Comment by godlikejoke** [comment]
感谢！
