### ISSUE TITLE
ssrWin客户端为何配置不成功，ssrMac客户端可用

### ISSUE THREAD

**Issue by yinchd** [ShadowsocksR-Live/shadowsocksr-native#195]
昨晚先在mac下按教程配置ssrMac客户端后能成功连接，今天打算在windows下尝试，于是下载ssrWin客户端后，配置了一条服务器配置（这条配置和配置文件中一致的，应该没问题），接下来配置Options，有4个需要填的地方：SSR client listen host，我填了127.0.0.1, SSR client listen port，我填了1080，在任务栏图标中右键菜单选择Run后，发现无法连接，于是我这4个框我轮流填了后都没法连接，请问这是如何配置的？

**Comment by ssrlive** [comment]
Options 是给我这样有特殊需求的人准备的，普通用户只要 Reset to default 按钮采用默认值然后点 OK 就够了。

**Comment by yinchd** [comment]
感谢抽空回复！
那天我又试了下用火狐插件的形式，发现能成功连接，后来我按你说的试了下恢复默认配置，也能连了，那应该是我之前操作不对引起的。但是又出现另一个问题，火狐下用插件的形式好像不能用了，如果我不启动ssrWin客户端，火狐连不上去，我描述一下我是怎么使用的：目前ssr-native-windows-x64 + ssr-win-x64 客户端可以用，ssr-native-windows-x64 + 火狐插件发现不行，请有空的时候帮忙看一下，成分感谢！
![Uploading firefox.png…]()

**Comment by ssrlive** [comment]
请卸载 FireProxy 插件，都用 SwitchyOmega 好了。

[FireFox](https://www.mozilla.org/zh-CN/firefox/new/) 浏览器也使用 [SwitchyOmega](https://addons.mozilla.org/en-US/firefox/addon/switchyomega/) 插件, 配置方法类似.
