### ISSUE TITLE
Compile error on Fedora 27

### ISSUE THREAD

**Issue by mia0x75** [ShadowsocksR-Live/shadowsocksr-native#20]
/home/linus/ssr-n/src/encrypt.c:80:10: fatal error: sodium.h: No such file or directory
 #include <sodium.h>
          ^~~~~~~~~~
compilation terminated.
make[2]: *** [src/CMakeFiles/ssr-local.dir/build.make:141: src/CMakeFiles/ssr-local.dir/encrypt.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:742: src/CMakeFiles/ssr-local.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

depends on libsodium-devel?

**Comment by ssrlive** [comment]
```
sudo su

dnf install autoconf libtool asciidoc xmlto -y
dnf install git gcc gcc-c++ cmake automake -y

cd /                          # switch to root directory
git clone https://github.com/ShadowsocksR-Live/shadowsocksr-native.git
mv shadowsocksr-native ssr-n  # rename shadowsocksr-native to ssr-n
cd ssr-n                      # enter ssr-n directory. 
git submodule update --init
git submodule foreach -q 'git checkout $(git config -f $toplevel/.gitmodules submodule.$name.branch || echo master)'

cmake CMakeLists.txt && make

```
