### ISSUE TITLE
能上外网，但是google用户登录界面报错，进不去

### ISSUE THREAD

**Issue by yilovezy** [ShadowsocksR-Live/shadowsocksr-native#200]
error  [TLS] websocket error at "ssl.gstatic.com:443" with status: Gateway Time-out
客户端报如上错误，想知道是啥原因。

**Comment by ssrlive** [comment]
不知道。估计是 `ssl.gstatic.com:443` 阶段性故障。

**Comment by yilovezy** [comment]
很奇怪，我用Firefox可以登录Google账号，Chrome就不行

**Comment by ssrlive** [comment]
这种情况我也经常遇到，你 chrome 和 firefox 交替着用吧。

**Comment by yilovezy** [comment]
amazing
