### ISSUE TITLE
 [TLS] websocket error at "xxx" with status: Not Found

### ISSUE THREAD

**Issue by QiyuanZqy** [ShadowsocksR-Live/shadowsocksr-native#202]
Please answer these questions before submitting your issue. Thanks!

### What version of shadowsocks-native are you using?
latest

### What operating system are you using?
Server： Ubuntu 20.04.3 LTS
Client: Windows 11

### What did you do?
Try to open Google

### What did you expect to see?
The website work nomally

### What did you see instead?
error  [TLS] websocket error at "google.com:443" with status: Not Found

### What is your config in detail (with all sensitive info masked)?

```
{
    "password": "......",
    "method": "aes-128-ctr",
    "protocol": "auth_aes128_md5",
    "protocol_param": "",
    "obfs": "tls1.2_ticket_auth",
    "obfs_param": "",

    "udp": true,
    "idle_timeout": 300,
    "connect_timeout": 6,
    "udp_timeout": 6,

    "server_settings": {
        "listen_address": "0.0.0.0",
        "listen_port": 9237
    },

    "client_settings": {
        "server": "......",
        "server_port": 443,
        "listen_address": "0.0.0.0",
        "listen_port": 1080
    },

    "over_tls_settings": {
        "enable": true,
        "server_domain": "......",
        "path": "......",
        "root_cert_file": ""
    }
}
```

**Comment by ssrlive** [comment]
Is this issue occurs on one site, Google, or all sites are inaccessible?

**Comment by QiyuanZqy** [comment]
All sites are inaccessible.

**Comment by ssrlive** [comment]
try to access your fake site from your browser without any proxy. like this:   `https://yoursitename.com`

**Comment by QiyuanZqy** [comment]
My fake site works normally

**Comment by ssrlive** [comment]
Well. please send IP and port and password of  your VPS via **email**, I spend some time to investment it.

**Comment by ssrlive** [comment]
Maybe [this](https://github.com/ShadowsocksR-Live/shadowsocksr-native/wiki/%E7%A6%81%E7%94%A8-IPv6) is the reason.

**Comment by QiyuanZqy** [comment]
> Maybe [this](https://github.com/ShadowsocksR-Live/shadowsocksr-native/wiki/%E7%A6%81%E7%94%A8-IPv6) is the reason.

No,It's unuseful,There's still error.
I had  something change in these config files.Are there any wrong?
[ssr.zip](https://github.com/ShadowsocksR-Live/shadowsocksr-native/files/7027121/ssr.zip)

**Comment by QiyuanZqy** [comment]
> Well. please send IP and port and password of your VPS via **email**, I spend some time to investment it.

Which password? The password of ssr or the password for login in the VPS?

**Comment by ssrlive** [comment]
IP and password and port of SSH for login in the VPS

**Comment by QiyuanZqy** [comment]
OK.I mailed to ssrlivebox@gmail.com

**Comment by QiyuanZqy** [comment]
OK.I mailed to ssrlivebox@gmail.com

**Comment by ssrlive** [comment]
https://github.com/ShadowsocksR-Live/shadowsocksr-native/blob/40a36c5b635184e6c42cd1270e0d76d829be2ab1/install/ssrn-ot-install.sh#L195

**Comment by QiyuanZqy** [comment]
It works.Thanks.
