### ISSUE TITLE
域名验证报错

### ISSUE THREAD

**Issue by codthing** [ShadowsocksR-Live/shadowsocksr-native#207]
ping通域名，且对应上vps的ip.
vps中的防火墙设置80和443开启（22默认开启）。
域名使用的是http，安装过程端口写的是80.
OS: Ubuntu 20.04 x64

![image](https://user-images.githubusercontent.com/16655229/141452193-c5e01ccc-95c4-4f4a-8b2e-a4b9f4551487.png)

**Comment by ssrlive** [comment]
很奇怪：“Timeout during connect (likely firewall problem)”。

**Comment by fungmo** [comment]
> 很奇怪：“Timeout during connect (likely firewall problem)”。

我用另一个域名和新开一个18版本可以，没问题。第一个域名fuck它了，也许在委婉地告诉我要曲线一点。

**Comment by fungmo** [comment]
我现在正在新建一个假网站中，不知道后续情况如何，拭目以待

**Comment by fungmo** [comment]
![image](https://user-images.githubusercontent.com/16655229/141464757-edcd9440-7ada-4b5e-8f43-b14ef1de799a.png)
现在来到这一步了，但是这里我有点没太弄清楚，这里是要自己创建一个文件夹吗？ 在哪个位置创建？

**Comment by ssrlive** [comment]
自动创建的。其中包含 隐藏文件夹 .well-known/acme-challenge/ 不要 手工删除。 否则以后 自动更新 证书会失败。

**Comment by fungmo** [comment]
![image](https://user-images.githubusercontent.com/16655229/141465247-dea9b67d-3822-4dba-beeb-478cbb388c88.png)
在目录2直接执行 ？
![image](https://user-images.githubusercontent.com/16655229/141465332-899a99b7-f1b0-49bf-94e1-56470389fc74.png)

**Comment by ssrlive** [comment]
/fakesite/ 文件夹是脚本在 根目录 自动创建的。

**Comment by ssrlive** [comment]
第一个吧

**Comment by fungmo** [comment]
> /fakesite/ 文件夹是脚本在 根目录 自动创建的。

cd ..到 :/ 根目录 ls，可以看到 fakesite 文件夹，

**Comment by fungmo** [comment]
我的理解是在:/根目录执行：``
在 www.xxx.com 目录执行: `mv * /fakesite/`

**Comment by ssrlive** [comment]
cd ~/xyc. com/  然后执行那两个命令。

**Comment by fungmo** [comment]
> cd ~/xyc. com/ 然后执行那两个命令。

谢谢，搞定，通过我都域名确实访问到了这个网站。

**Comment by fungmo** [comment]
windows客户端配置好了，但是用Chrome打开youtube没响应呢

**Comment by ssrlive** [comment]
https://github.com/ShadowsocksR-Live/shadowsocksr-native/wiki/%E5%AE%A2%E6%88%B7%E7%AB%AF%E7%94%A8%E6%B3%95#chrome-%E6%B5%8F%E8%A7%88%E5%99%A8%E8%AE%BE%E7%BD%AE

**Comment by fungmo** [comment]
是的，我支持用的这个：
![image](https://user-images.githubusercontent.com/16655229/141468446-c8668c09-f706-4cd6-b2db-1a22cfa098f8.png)
![image](https://user-images.githubusercontent.com/16655229/141468481-77ae6f25-2143-45a5-a9d0-6df07291b1df.png)

**Comment by fungmo** [comment]
我需要run一下

**Comment by fungmo** [comment]
以前的方式确实不行了，我今天搜索看到了这个库，很感谢作者@ssrlive 的创作，很Nice!

**Comment by fungmo** [comment]
android客户端在开发中了吗？很期待

**Comment by ssrlive** [comment]
客户端运行 native 进程 报错，没解决，Android 生手。要过段时间。

**Comment by fungmo** [comment]
> 客户端运行 native 进程 报错，没解决，Android 生手。要过段时间。

嗯，加油

**Comment by codthing** [comment]
> > 很奇怪：“Timeout during connect (likely firewall problem)”。
> 
> 我用另一个域名和新开一个18版本可以，没问题。第一个域名fuck它了，也许在委婉地告诉我要曲线一点。fuckxxxx是.club的后缀，用.com的后缀域名可以。现在没时间去排查具体的原因。新域名+18可以看到nginx页面，另一个不行。

club后缀的也可以了，可能和传播速度有关系。club<com

**Comment by codthing** [comment]
遇到个问题，我的git之前设置的
`git config --global --add remote.origin.proxy "127.0.0.1:1080"`, 
不起作用了，
`Failed to connect to 127.0.0.1 port 1080: Connection refused`，

**Comment by codthing** [comment]
> 遇到个问题，我的git之前设置的 `git config --global --add remote.origin.proxy "127.0.0.1:1080"`, 不起作用了， `Failed to connect to 127.0.0.1 port 1080: Connection refused`，
> 
> > 
> 
> 我想起来今天手动安装SSRoT的端口号为 10000， 所以，配置为 `git config --global --add remote.origin.proxy "127.0.0.1:10000`后， 报： `Received HTTP code 400 from proxy after CONNECT`
> 
> > 
> 
> OS win10

经测试，remote.origin.proxy 需要配置为 安装SSRoT的时候生成的反向代理字符串，终于搞定，运行正常。

**Comment by ssrlive** [comment]
git 设置 socks5 代理是这个方法  https://github.com/ShadowsocksR-Live/iShadowsocksR#tips
