### ISSUE TITLE
debian

### ISSUE THREAD

**Issue by nxz123-nxz** [ShadowsocksR-Live/shadowsocksr-native#208]
- [ ] 

- [ ] #debain如何安装使用啊？安装完了不会使用，需要配置文件和服务器吗？
- [ ]

**Comment by ssrlive** [comment]
先看文档。

https://github.com/ShadowsocksR-Live/shadowsocksr-native/wiki/%E5%87%86%E5%A4%87%E5%B7%A5%E4%BD%9C

和 

https://github.com/ShadowsocksR-Live/shadowsocksr-native/wiki/%E5%85%A8%E8%87%AA%E5%8A%A8%E5%AE%89%E8%A3%85-SSRoT-%E6%9C%8D%E5%8A%A1%E5%99%A8
