### ISSUE TITLE
client连上server，但是无法浏览网页

### ISSUE THREAD

**Issue by bigjimmy546** [ShadowsocksR-Live/shadowsocksr-native#210]
ssr-server成功安裝
但是client无法上网
跑ssr-server

root@ubuntu:~# ssr-server
ssr-server 2022/01/11 09:10  info  ShadowsocksR native server

ssr-server 2022/01/11 09:10  info  listen address   0.0.0.0:54814
ssr-server 2022/01/11 09:10  info   
ssr-server 2022/01/11 09:10  info  method           aes-128-ctr
ssr-server 2022/01/11 09:10  info  password         xxxxxxxx
ssr-server 2022/01/11 09:10  info  protocol         auth_aes128_md5
ssr-server 2022/01/11 09:10  info  obfs             tls1.2_ticket_auth
ssr-server 2022/01/11 09:10  info  udp relay        no

ssr-server 2022/01/11 09:10 error  /root/shadowsocksr-native/src/server/server.c : 264	Error on listening "0.0.0.0:54814": address already in use.

**Comment by ssrlive** [comment]
启用 SSRoT 和旧的 SSR 不一样的。得照着 wiki 说的安装。

**Comment by bigjimmy546** [comment]
关闭ssrot也是不能上网

**Comment by ssrlive** [comment]
爲了省事，先把服務端卸載，
```
./ssrn-install.sh uninstall
```
再把它裝上。然後用 `ps aux | grep ssr` 查看服務端是否已經運行，最後用命令
```
cat /etc/ssr-native/config.json
```
列出配置文件的內容，本地客戶端就可以使用這個配置了。

值得一提的是，SSR流量已經被監控，一般幾天甚至幾小時就會被GFW封掉。

**Comment by bigjimmy546** [comment]
Synchronizing state of ssr-native.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable ssr-native

======== config.json ========

{
    "password": "xxxx",
    "method": "aes-128-ctr",
    "protocol": "auth_aes128_md5",
    "protocol_param": "",
    "obfs": "tls1.2_ticket_auth",
    "obfs_param": "",

    "udp": true,
    "idle_timeout": 300,
    "connect_timeout": 6,
    "udp_timeout": 6,

    "server_settings": {
        "listen_address": "0.0.0.0",
        "listen_port": 10047
    },

    "client_settings": {
        "server": "122.116.14.182",
        "server_port": 443,
        "listen_address": "0.0.0.0",
        "listen_port": 1080
    },

    "over_tls_settings": {
        "enable": true,
        "server_domain": "xxxx.com",
        "path": "/xxxxxxx-fc76-4797-b718-xxxxxxxx/",
        "root_cert_file": ""
    }
}

=============================

[OK]  Installing ShadowsocksR Native Completed 
[OK]  web camouflage Completed 
root@ubuntu:~/ssr-n/build# ssr-server
ssr-server 2022/01/11 14:09  info  ShadowsocksR native server

ssr-server 2022/01/11 14:09  info  listen address   0.0.0.0:10047
ssr-server 2022/01/11 14:09  info   
ssr-server 2022/01/11 14:09  info  method           aes-128-ctr
ssr-server 2022/01/11 14:09  info  password         xxxxxxxx
ssr-server 2022/01/11 14:09  info  protocol         origin
ssr-server 2022/01/11 14:09  info  obfs             plain
ssr-server 2022/01/11 14:09  info   
ssr-server 2022/01/11 14:09  warn  over TLS         yes
ssr-server 2022/01/11 14:09  info  over TLS domain  xxxxxxx
ssr-server 2022/01/11 14:09  info  over TLS path    /xxxxxxx-fc76-4797-b718-xxxxxxx/
ssr-server 2022/01/11 14:09  info   
ssr-server 2022/01/11 14:09  info  udp relay        yes

ssr-server 2022/01/11 14:09 error  /root/ssr-n/build/shadowsocksr-native/src/server/server.c : 264	Error on listening "0.0.0.0:10047": address already in use.

**Comment by ssrlive** [comment]
后台已经作为服务运行了。再运行当然端口占用。

**Comment by bigjimmy546** [comment]
請問可以那裡查找為何連線成功，但是客戶端無法上網（全網）。可以看到用戶連線情況？謝謝

**Comment by ssrlive** [comment]
![image](https://user-images.githubusercontent.com/30760636/148900099-da0cc6c8-8238-425e-b0db-a04e18e4e10a.png)
如果你没有安装 SSRoT 所必须的域名和 网站证书，你连不上服务器，端口直接拒绝链接。

至于客户端的用法，自己看完教程再提问。
https://github.com/ShadowsocksR-Live/shadowsocksr-native/wiki/%E5%AE%A2%E6%88%B7%E7%AB%AF%E7%94%A8%E6%B3%95

**Comment by bigjimmy546** [comment]
好的，謝謝你
