### ISSUE TITLE
无法与bbr共存?

### ISSUE THREAD

**Issue by Clownsw** [ShadowsocksR-Live/shadowsocksr-native#219]
### What version of shadowsocks-native are you using?
Version 0.9.2

### What operating system are you using?
ubuntu 18+

### What did you do?
我使用了shadowsocksR-native 一键脚本. 可以正常使用, 但是很卡
于是我使用了bbr加速, 安装正常使用报错

error:
ssrWin 2022/02/23 11:13  info  ++++ connecting  "ime.sogou.com:80" ... ++++
ssrWin 2022/02/23 11:13 error  [TLS] connecting "149.154.167.92:80" failed: -4078: connection refused
ssrWin 2022/02/23 11:13 error  ---- disconnected  "149.154.167.92:80" with failed. ---
ssrWin 2022/02/23 11:13  info  ==== tunnel destroyed   count   7 ====
ssrWin 2022/02/23 11:13 error  [TLS] connecting "91.108.56.192:80" failed: -4078: connection refused
ssrWin 2022/02/23 11:13 error  ---- disconnected  "91.108.56.192:80" with failed. ---
ssrWin 2022/02/23 11:13  info  ==== tunnel destroyed   count   6 ====
ssrWin 2022/02/23 11:13 error  [TLS] connecting "91.108.56.192:443" failed: -4078: connection refused
ssrWin 2022/02/23 11:13 error  ---- disconnected  "91.108.56.192:443" with failed. ---
ssrWin 2022/02/23 11:13  info  ==== tunnel destroyed   count   5 ====

**Comment by ssrlive** [comment]
“很卡”是個什麼程度？youtube 效果？測速結果？

**Comment by Clownsw** [comment]
> youtube

v2ray youtube: 三四万左右
shadowsocksR-native: 一万和一万以下

**Comment by Clownsw** [comment]
> “很卡”是個什麼程度？youtube 效果？測速結果？

v2ray youtube: 三四万左右
shadowsocksR-native: 一万和一万以下

**Comment by Clownsw** [comment]
"method": "aes-128-ctr",
"protocol": "auth_aes128_md5",
"obfs": "tls1.2_ticket_fastauth"

**Comment by Clownsw** [comment]
@ssrlive 老哥

**Comment by ssrlive** [comment]
我在一個bwg主機上的結果，油管視頻2倍速很流暢，我沒測過4k高清，應該也沒問題。

![image](https://user-images.githubusercontent.com/30760636/155266466-e6beb189-faa9-467e-88a7-1151e7ab33f1.png)

**Comment by Clownsw** [comment]
> bwg
