### ISSUE TITLE
Slow bug not a bug

### ISSUE THREAD

**Issue by wonderful27x** [ShadowsocksR-Live/shadowsocksr-native#222]
Please answer these questions before submitting your issue. Thanks!

### What version of shadowsocks-native are you using?
use auto install, latest commit hash is 255e198687bce23f639f87a23f6feeab085dc628 of master

### What operating system are you using?
server  
```
CentOS Linux release 7.9.2009 (Core)
Linux core-buzz-1.localdomain 3.10.0-1160.59.1.el7.x86_64 #1 SMP Wed Feb 23 16:47:03 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```
client  
```
Ubuntu 21.04
Linux wonderful-ubuntu 5.11.0-49-generic #55-Ubuntu SMP Wed Jan 12 17:36:34 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

### What is you question but not a bug!!!
* I found that its much more slower than [the original version](https://github.com/shadowsocks/shadowsocks/tree/master) of clowwindy

**Comment by ssrlive** [comment]
please show the 4K youtube video info via SSRoT and via SS. like this

![image](https://user-images.githubusercontent.com/30760636/161426618-c10686d3-3c8b-407e-8806-77de76a452dd.png)

**Comment by wonderful27x** [comment]
我没太明白你的意思该具体怎么做，我就是明显的感觉到浏览网页和下载webrtc的时候比SS慢了很多
