### ISSUE TITLE
安卓的客户端啥时候可以好啊？

### ISSUE THREAD

**Issue by radiumliu** [ShadowsocksR-Live/shadowsocksr-native#223]
都2年啦，大佬

**Comment by ssrlive** [comment]
在學 rust ，安卓撂下了，學好了再來。可惡 rust 讓我入門無數次，跨線程 web 服務器讓偶至今深陷泥淖沒出坑。
So，安卓客戶端拖着了。

**Comment by ssrlive** [comment]
等不及的，可以自取一個 https://github.com/ssrlive/ssrDroid3 源代碼編譯一個自己玩，還不支持 SSRoT 但傳統 功能是有的。

**Comment by ssrlive** [comment]
安卓客户端已经开发完毕，下载链接 https://github.com/ShadowsocksR-Live/ssrDroid/releases/latest
