### ISSUE TITLE
默认编译出的只有ssr-client和ssr-server，而没有ssr-local

### ISSUE THREAD

**Issue by truelv** [ShadowsocksR-Live/shadowsocksr-native#224]
Please answer these questions before submitting your issue. Thanks!

**Comment by ssrlive** [comment]
ssr-client 就是 ssr-local

**Comment by truelv** [comment]
ssr-client和ssr-local不是一个程序，虽然两者都是客户端，功能类似但是不是同一个软件

**Comment by ssrlive** [comment]
好吧，我早已把 ssr-local 刪了。你可以在 git 的提交歷史裏把它找出來。
