### ISSUE TITLE
没有配置over_tls_settings这个部分容易被gfw封吗？

### ISSUE THREAD

**Issue by redstoneleo** [ShadowsocksR-Live/shadowsocksr-native#225]
我的现在就是如下做做样子，没有配置这个部分容易被gfw封吗？

```
    "over_tls_settings": {
        "enable": false,
        "server_domain": "",
        "path": "//",
        "root_cert_file": ""
    }
```

**Comment by ssrlive** [comment]
一般管用两个小时到一周。

**Comment by redstoneleo** [comment]
顺便问一下，根据这里的方法
https://github.com/ShadowsocksR-Live/shadowsocksr-native/wiki/%E5%85%A8%E8%87%AA%E5%8A%A8%E5%AE%89%E8%A3%85-SSRoT-%E6%9C%8D%E5%8A%A1%E5%99%A8

一键安装的时候出现如下情况怎么办？

```
DNS resolution IP: 3.112.1.233
Local IP: 2406:da14:d8b:c000:a2e2:daa:ec57:156a
[Error]  The DNS resolution IP does not match the local IP. Do you want to continue the installation? (y/n)
```

**Comment by ssrlive** [comment]
你是在 euserv 上安装吗？这个 IPv6 的情况，放过就行了。

**Comment by redstoneleo** [comment]
亚马逊lightsail上安装

**Comment by ssrlive** [comment]
那估计得改脚本。  `curl ipv6.ip.sb` 和 `curl ip.sb` 分别返回什么？

**Comment by ssrlive** [comment]
那估计得改脚本。  `curl ipv6.ip.sb` 和 `curl ip.sb` 分别返回什么？

或者更直白地询问 IPv4 和 IPv6 地址
```
curl ipv6.ip.sb
curl ipv4.ip.sb
```


如果两种地址都返回了，那建议你禁掉 IPv6 。否则很麻烦。

https://github.com/ShadowsocksR-Live/shadowsocksr-native/wiki/%E7%A6%81%E7%94%A8-IPv6

**Comment by redstoneleo** [comment]
都返回了，不过IPv6 是未来趋势，禁掉 IPv6也只是一时半会儿的权宜之计吧？
```
ubuntu@ip-172-26-7-128:~$ curl ipv6.ip.sb
2406:da14:d8b:c000:a2e2:daa:ec57:156a
ubuntu@ip-172-26-7-128:~$ curl ipv4.ip.sb
3.112.1.233
ubuntu@ip-172-26-7-128:~$ curl ip.sb
2406:da14:d8b:c000:a2e2:daa:ec57:156a
ubuntu@ip-172-26-7-128:~$
```

**Comment by ssrlive** [comment]
这未来趋势都他妈趋势了30年了，现在还是使用 IPv4 为主，我们翻墙软件还要挺多久？中共垮台以后翻墙软件就就狗屁不是了。难道还要30年？

**Comment by redstoneleo** [comment]
大哥息怒，随便聊聊。
换一个gov应该不代表墙的消失吧，想起了《一九八四·动物农场》
随着手持设备和物联网设备的增加，IPv6应该会发展得更快吧。
