### ISSUE TITLE
Win客户端HTTP监听的8118端口能否自定义IP？

### ISSUE THREAD

**Issue by imskk89** [ShadowsocksR-Live/shadowsocksr-native#229]
Win客户端HTTP监听的8118端口能否自定义IP？比如设置成0.0.0.0.
我试了设置只能改socks5，HTTP仍为127.0.0.1
如果能改，手机或其他便携设备能够方便的用wifi代理设置使用了

**Comment by ssrlive** [comment]
貌似不能，因爲 privoxy 不支撐 0.0.0.0 這個監聽地址。

![image](https://user-images.githubusercontent.com/30760636/172057059-8195803d-8315-43d4-ba6a-ff0ffaafa54a.png)

**Comment by imskk89** [comment]
能不能参考SS客户端来实现？
![image](https://user-images.githubusercontent.com/3604583/172060562-d5b9f93d-4f7a-46ca-bcff-72e3eb40f15e.png)

**Comment by imskk89** [comment]
> 貌似不能，因爲 privoxy 不支持 0.0.0.0 這個監聽地址。
> 
> ![image](https://user-images.githubusercontent.com/30760636/172057059-8195803d-8315-43d4-ba6a-ff0ffaafa54a.png)
能不能参考SS客户端来的功能来实现？
![image](https://user-images.githubusercontent.com/3604583/172060603-6ac8624b-a4f4-4530-8ef3-82fb27779128.png)

**Comment by ssrlive** [comment]
加上了。
![image](https://user-images.githubusercontent.com/30760636/172297575-61c5d9f6-2681-4f87-b780-10f26af43208.png)
