### ISSUE TITLE
关于v2ray-plugin for iOS

### ISSUE THREAD

**Issue by yangdehui** [ShadowsocksR-Live/shadowsocksr-native#233]

**Comment by ssrlive** [comment]
既然你一再要求支持 v2 協議，表明你不是 ssrot 協議的用戶，你都不是我的目標用戶了，我就沒必要搭理你。懂？

事實上， 使用純 C 語言實現的 ssrot 的處理速度比使用 golang 實現的 v2 速度快了不是一倍兩倍，那麼你守着 v2 想要幹什麼？
