### ISSUE TITLE
Latest version does not work on debian 11

### ISSUE THREAD

**Issue by kolatv23** [ShadowsocksR-Live/shadowsocksr-native#235]
Please answer these questions before submitting your issue. Thanks!

### What version of shadowsocks-native are you using?
0.9.3

### What operating system are you using?
Debian 11

### What did you do?
SSR server process exits with error every time upon client connection, on my debian 11 machine. I tested 0.9.2 and it was fine. 

### What did you expect to see?
SSR-Server works flawlessly like previous versions.

### What did you see instead?
```
ssr-server 2022/09/01 20:43  info  ==== tunnel created     count   1 ====
ssr-server 2022/09/01 20:43  info  tunnel_stage_initial
ssr-server 2022/09/01 20:43 error  unexpect tunnel terminated. about _client_ "(null)": Unknown system error 465 - tunnel_stage_initial
>>>> memory panic of expected size = 2036497376 and allocated size = 0 in OS  <<<<
>>>> memory panic of expected size = 2036497888 and allocated size = 0 in OS  <<<<
free(): invalid pointer
Aborted
```

### What is your config in detail (with all sensitive info masked)?
 info  listen address   0.0.0.0:8755
 info  method           none
 info  password         [password]
 info  protocol         origin
 info  obfs             tls1.2_ticket_auth
 info  udp relay        no

**Comment by kolatv23** [comment]
> 

This is what I got from core files:
`Core was generated by ./ssr -c config.json'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  buffer_release (ptr=0x50) at /root/ssr-n/src/ssrbuffer.c:295
295     /root/ssr-n/src/ssrbuffer.c: No such file or directory.
`
and 
`Core was generated by ./ssr -c config.json'.
Program terminated with signal SIGABRT, Aborted.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
`

**Comment by ssrlive** [comment]
can you send me your VPS login to me? you can email me with ssrlive(at)gmail(dot)com

**Comment by kolatv23** [comment]
> 

Sorry I can't provide login info at the moment. You should be able to reproduce this bug on a new installed debian 11 machine.

**Comment by ssrlive** [comment]
I will update the binary package soon.
