### ISSUE TITLE
怎么防止网站被墙

### ISSUE THREAD

**Issue by qian9008** [ShadowsocksR-Live/shadowsocksr-native#238]
ssl加密网站墙是看不见内容的，除非主动探测，那么给所有用户都开访问验证。网站是不是就安全了。不至于人工去审核吧

**Comment by ssrlive** [comment]
沒看懂你要表達什麼。https 類型的網站，傳輸的內容是加密的，GFW 目前無法破解合符 TLS 標準的傳輸內容。GFW 主動探測時使用的路徑字符串是有限的的，比如 `https://mysite.com/xjpsgdsb/` 諸如此類的，但用戶能創造的路徑是無限的；路徑字符串在傳輸時是用 TLS 加密的，GFW 不知道你對網站的訪問路徑是什麼，我們只要在客戶端和服務端約定好，哪個特定的複雜字符串才是翻牆流量，就順利翻牆了，這就是目前翻牆軟件能騙過 GFW 的祕密。

不知道你懂了沒有。

**Comment by qian9008** [comment]
只是想了解下，一些不知名小站是怎么被墙的。除了被举报应该很安全的。如果sni dns全加密的话，是不是无法被墙了，可以直接上Google了。

**Comment by ssrlive** [comment]
中共为了省心，已经直接把 加密 SNI 屏蔽了。所以，想要用 ESNI 骗过 GFW 是行不通的。除非全世界所有网站都用 ESNI ，而且中国到那时还没闭关锁国到朝鲜这种程度，中共才可能放松对 ESNI 的控制。

无名小站被墙的唯一理由是，不管你访问该站的流量特征是不是 TLS， 都像是在翻墙。我的 [这篇文章](https://github.com/ShadowsocksR-Live/shadowsocksr-native/wiki#ssr-over-tls-%E5%8E%9F%E7%90%86) 已经说得很透了。
