### ISSUE TITLE
编译成功后，无法连接到购买的服务上去

### ISSUE THREAD

**Issue by wangsanshi123** [ShadowsocksR-Live/shadowsocksr-native#241]
Please answer these questions before submitting your issue. Thanks!

### What version of shadowsocks-native are you using?
最新版

### What operating system are you using?
centos7

### What did you do?
有个ssr协议的账号，手机上能够翻墙，想在centos也能翻墙。想把这个软件充当一个linux上的客户端
执行的命令：./ssr-client -c /root/download/ssr-n/config.json
然后在浏览器中配置指向代理
![image](https://user-images.githubusercontent.com/15081998/206655283-7b70e4a6-6206-4d1d-b7c5-75aaca9a9791.png)

### What did you expect to see?

加上这个代理后能够访问网络
### What did you see instead?
不能够正常访问网络。墙内网都不行

### What is your config in detail (with all sensitive info masked)?
![image](https://user-images.githubusercontent.com/15081998/206654879-12372da3-02fa-42d0-8020-69318b3a3c66.png)

**Comment by ssrlive** [comment]
我這裏沒問題啊。
```
root@ggg:~/ssr-n/build# cat v.json
{
    "password": "password",
    "method": "chacha20-ietf",
    "protocol": "auth_aes128_md5",
    "protocol_param": "",
    "obfs": "tls1.2_ticket_auth",
    "obfs_param": "",

    "server_settings": {
        "listen_address": "0.0.0.0",
        "listen_port": 8380
    },

    "client_settings": {
        "server": "my server ip",
        "server_port": 8380,
        "listen_address": "0.0.0.0",
        "listen_port": 2080
    }
}

root@ggg:~/ssr-n/build# curl --proxy socks5h://127.0.0.1:2080 https://google.com
<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>301 Moved</TITLE></HEAD><BODY>
<H1>301 Moved</H1>
The document has moved
<A HREF="https://www.google.com/">here</A>.
</BODY></HTML>
root@ggg:~/ssr-n/build# 
```
要不你架一個 python 版的服務器試試這個配置？

**Comment by wangsanshi123** [comment]
~                                                                                                                                                                                                                ~                                                                                                                                                                                                               服务端：./ssr-server -c /root/download/ssr-n/config_local.json 
客户端：./ssr-client -c /root/download/ssr-n/config_local.json 
配置文件：
{
    "password": "password",
    "method": "chacha20-ietf",
    "protocol": "auth_aes128_md5",
    "protocol_param": "",
    "obfs": "tls1.2_ticket_auth",
    "obfs_param": "",

    "server_settings": {
        "listen_address": "0.0.0.0",
        "listen_port": 8380
    },

    "client_settings": {
        "server": "localhost",
        "server_port": 8380,
        "listen_address": "0.0.0.0",
        "listen_port": 2080
    }
}
~   然后运行如下命令，还是不行。                                                                                                                                                                                                             
(opendoor) [root@VM-16-3-centos ssr-n]# curl --proxy socks5h://127.0.0.1:2080  http://106.13.147.31:8000/
curl: (52) Empty reply from server
(opendoor) [root@VM-16-3-centos ssr-n]# 
~

**Comment by ssrlive** [comment]
客戶端 和 服務端 都報什麼信息？

**Comment by wangsanshi123** [comment]
客户端：ssr-client 2022/12/09 17:46  info  ==== tunnel created     count   1 ====
ssr-client 2022/12/09 17:46  info  tunnel_stage_handshake -- Client App S5 handshake coming.
ssr-client 2022/12/09 17:46  info  socks5 handshake normal style called
ssr-client 2022/12/09 17:46  info  tunnel_stage_handshake_replied -- Start waiting for request data.
ssr-client 2022/12/09 17:46  info  tunnel_stage_s5_request_from_client_app -- SOCKS5 Request data from client app.
ssr-client 2022/12/09 17:46  info  tunnel_stage_s5_response_done
ssr-client 2022/12/09 17:46  info  tunnel_stage_client_first_pkg
ssr-client 2022/12/09 17:46  info  ++++ connecting  "106.13.147.33:8000" ... ++++
ssr-client 2022/12/09 17:46  info  tunnel_stage_resolve_ssr_server_host_done -- Upstream hostname DNS lookup has completed.
ssr-client 2022/12/09 17:46 error  connect failed about _server_ "106.13.147.31:8000": connection refused - tunnel_stage_resolve_ssr_server_host_done -- Upstream hostname DNS lookup has completed.
ssr-client 2022/12/09 17:46  info  ---- disconnected  "106.13.147.33:8000" ----
ssr-client 2022/12/09 17:46  info  ==== tunnel destroyed   count   0 ====
^Cssr-client 2022/12/09 17:48  info   

服务端：(base) [root@VM-16-3-centos src]# ./ssr-server -c /root/download/ssr-n/config_local.json 
ssr-server 2022/12/09 17:46  info  ShadowsocksR native server

ssr-server 2022/12/09 17:46  info  listen address   0.0.0.0:8380
ssr-server 2022/12/09 17:46  info   
ssr-server 2022/12/09 17:46  info  method           chacha20-ietf
ssr-server 2022/12/09 17:46  info  password         password
ssr-server 2022/12/09 17:46  info  protocol         auth_aes128_md5
ssr-server 2022/12/09 17:46  info  obfs             tls1.2_ticket_auth
ssr-server 2022/12/09 17:46  info  udp relay        yes

**Comment by ssrlive** [comment]
測試命令改成下面試試？
```
curl --proxy socks5h://127.0.0.1:2080 http://baidu.com
```

**Comment by wangsanshi123** [comment]
链接百度的也试了，也不行。客户端和服务端都在同一台服务器，应该不存在防火墙的问题吧

**Comment by ssrlive** [comment]
那現在可以確認，你的 CentOS 有問題。這是我在我的 ubuntu 上的所有操作，連回退 libuv 舊版本的操作都做了，沒問題。
如果你懂 C 語言，可以用 lldb 跟蹤一下，看看到底哪裏出了問題。

```
root@gggg:~/ssr-n/build# cat src/v.json
{
    "password": "password",
    "method": "chacha20-ietf",
    "protocol": "auth_aes128_md5",
    "protocol_param": "",
    "obfs": "tls1.2_ticket_auth",
    "obfs_param": "",

    "server_settings": {
        "listen_address": "0.0.0.0",
        "listen_port": 8380
    },

    "client_settings": {
        "server": "127.0.0.1",
        "server_port": 8380,
        "listen_address": "0.0.0.0",
        "listen_port": 2080
    }
}

root@gggg:~/ssr-n/build# history 10
  756  cd ../depends/libuv
  757  git checkout 71932a9fc9e234b3ebac90de0dd061fb00ba191b
  758  cd ../../build
  743  /root/ssr-n/build/src/ssr-server -c /root/ssr-n/build/src/v.json &
  745  src/ssr-client -c src/v.json &
  746  curl --proxy socks5h://127.0.0.1:2080 https://google.com
  749  cat src/v.json

root@gggg:~/ssr-n/build# curl --proxy socks5h://127.0.0.1:2080 https://google.com
ssr-client 2022/12/10 00:50  info  ==== tunnel created     count   1 ====
ssr-client 2022/12/10 00:50  info  tunnel_stage_handshake -- Client App S5 handshake coming.
ssr-client 2022/12/10 00:50  info  socks5 handshake normal style called
ssr-client 2022/12/10 00:50  info  tunnel_stage_handshake_replied -- Start waiting for request data.
ssr-client 2022/12/10 00:50  info  tunnel_stage_s5_request_from_client_app -- SOCKS5 Request data from client app.
ssr-client 2022/12/10 00:50  info  tunnel_stage_s5_response_done
ssr-client 2022/12/10 00:50  info  tunnel_stage_client_first_pkg
ssr-client 2022/12/10 00:50  info  ++++ connecting  "google.com:443" ... ++++
ssr-client 2022/12/10 00:50  info  tunnel_stage_connect_ssr_server_done -- Connect to server complete.
ssr-server 2022/12/10 00:50  info  ==== tunnel created     count   1 ====
ssr-client 2022/12/10 00:50  info  tunnel_stage_ssr_auth_sent
ssr-server 2022/12/10 00:50  info  tunnel_stage_initial
ssr-server 2022/12/10 00:50  info  tunnel_stage_obfs_receipt_done
ssr-client 2022/12/10 00:50  info  tunnel_stage_ssr_server_feedback_arrived
ssr-server 2022/12/10 00:50  info  tunnel_stage_client_feedback_coming
ssr-client 2022/12/10 00:50  info  tunnel_stage_ssr_receipt_to_server_sent
ssr-client 2022/12/10 00:50  info  tunnel_stage_auth_completion_done -- Auth succeeded. Can start piping data.
ssr-server 2022/12/10 00:50  info  tunnel_stage_protocol_confirm_done
ssr-client 2022/12/10 00:50  info  tunnel_stage_streaming -- Pipe data back and forth. ...
ssr-server 2022/12/10 00:50  info  connecting "google.com:443" ...
ssr-server 2022/12/10 00:50  info  tunnel_stage_connect_host
ssr-server 2022/12/10 00:50  info  tunnel_stage_streaming ...
<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>301 Moved</TITLE></HEAD><BODY>
<H1>301 Moved</H1>
The document has moved
<A HREF="https://www.google.com/">here</A>.
</BODY></HTML>
ssr-server 2022/12/10 00:50  info  ==== tunnel destroyed   count   0 ====
ssr-client 2022/12/10 00:50  info  ---- disconnected  "google.com:443" ----
ssr-client 2022/12/10 00:50  info  ==== tunnel destroyed   count   0 ====


```

**Comment by wangsanshi123** [comment]
![image](https://user-images.githubusercontent.com/15081998/206952838-630e6556-7893-438f-83f9-1847d201f265.png)
原来是配置文件中不能用localhost,换成127.0.0.1就可以了

**Comment by wangsanshi123** [comment]
在本地运行客户端和和服务端，然后代理访问百度是能成功的。
(base) [root@VM-16-3-centos ~]#  curl --proxy socks5h://localhost:2080 https://baidu.com

```
<html>
<head><title>302 Found</title></head>
<body bgcolor="white">
<center><h1>302 Found</h1></center>
<hr><center>bfe/1.0.8.18</center>
</body>
</html>
```




但是通过客户端访问购买的远程服务不行。
配置文件如下：

```
{
    "password": "xxx",
    "method": "chacha20-ietf",
    "protocol": "auth_aes128_md5",
    "protocol_param": "",
    "obfs": "tls1.2_ticket_auth",
    "obfs_param": "",


    "client_settings": {
        "server": "remote ip",
        "server_port": 7002,
        "listen_address": "0.0.0.0",
        "listen_port": 1081
    }

}
```

运行命令
`(base) [root@VM-16-3-centos ~]#  curl --proxy socks5h://localhost:1081 https://baidu.com
curl: (35) Encountered end of file
(base) [root@VM-16-3-centos ~]#  curl --proxy socks5h://localhost:1081 https://google.com
curl: (35) Encountered end of file
(base) [root@VM-16-3-centos ~]# 
`

客户端日志：
```
(base) [root@VM-16-3-centos src]# ./ssr-client -c ./ssr-client -c /root/download/ssr-n/config.json
ssr-client 2022/12/12 11:22  info  ShadowsocksR native client

ssr-client 2022/12/12 11:22  info  remote server    orac*******************:7002
ssr-client 2022/12/12 11:22  info  method           chacha20-ietf
ssr-client 2022/12/12 11:22  info  password         di****
ssr-client 2022/12/12 11:22  info  protocol         auth_aes128_md5
ssr-client 2022/12/12 11:22  info  obfs             tls1.2_ticket_auth
ssr-client 2022/12/12 11:22  info  udp relay        yes

ssr-client 2022/12/12 11:22  info  listening on     0.0.0.0:1081

ssr-client 2022/12/12 11:22  info  ==== tunnel created     count   1 ====
ssr-client 2022/12/12 11:22  info  tunnel_stage_handshake -- Client App S5 handshake coming.
ssr-client 2022/12/12 11:22  info  socks5 handshake normal style called
ssr-client 2022/12/12 11:22  info  tunnel_stage_handshake_replied -- Start waiting for request data.
ssr-client 2022/12/12 11:22  info  tunnel_stage_s5_request_from_client_app -- SOCKS5 Request data from client app.
ssr-client 2022/12/12 11:22  info  tunnel_stage_s5_response_done
ssr-client 2022/12/12 11:22  info  tunnel_stage_client_first_pkg
ssr-client 2022/12/12 11:22  info  ++++ connecting  "baidu.com:443" ... ++++
ssr-client 2022/12/12 11:22  info  tunnel_stage_resolve_ssr_server_host_done -- Upstream hostname DNS lookup has completed.
ssr-client 2022/12/12 11:22  info  tunnel_stage_connect_ssr_server_done -- Connect to server complete.
ssr-client 2022/12/12 11:22  info  tunnel_stage_ssr_auth_sent
ssr-client 2022/12/12 11:22  info  tunnel_stage_ssr_server_feedback_arrived
ssr-client 2022/12/12 11:22  info  tunnel_stage_ssr_receipt_to_server_sent
ssr-client 2022/12/12 11:22  info  tunnel_stage_auth_completion_done -- Auth succeeded. Can start piping data.
ssr-client 2022/12/12 11:22  info  tunnel_stage_streaming -- Pipe data back and forth. ...
ssr-client 2022/12/12 11:22  info  ---- disconnected  "baidu.com:443" ----
ssr-client 2022/12/12 11:22  info  ==== tunnel destroyed   count   0 ====
ssr-client 2022/12/12 11:22  info  ==== tunnel created     count   1 ====
ssr-client 2022/12/12 11:22  info  tunnel_stage_handshake -- Client App S5 handshake coming.
ssr-client 2022/12/12 11:22  info  socks5 handshake normal style called
ssr-client 2022/12/12 11:22  info  tunnel_stage_handshake_replied -- Start waiting for request data.
ssr-client 2022/12/12 11:22  info  tunnel_stage_s5_request_from_client_app -- SOCKS5 Request data from client app.
ssr-client 2022/12/12 11:22  info  tunnel_stage_s5_response_done
ssr-client 2022/12/12 11:22  info  tunnel_stage_client_first_pkg
ssr-client 2022/12/12 11:22  info  ++++ connecting  "google.com:443" ... ++++
ssr-client 2022/12/12 11:22  info  tunnel_stage_resolve_ssr_server_host_done -- Upstream hostname DNS lookup has completed.
ssr-client 2022/12/12 11:22  info  tunnel_stage_connect_ssr_server_done -- Connect to server complete.
ssr-client 2022/12/12 11:22  info  tunnel_stage_ssr_auth_sent
ssr-client 2022/12/12 11:22  info  tunnel_stage_ssr_server_feedback_arrived
ssr-client 2022/12/12 11:22  info  tunnel_stage_ssr_receipt_to_server_sent
ssr-client 2022/12/12 11:22  info  tunnel_stage_auth_completion_done -- Auth succeeded. Can start piping data.
ssr-client 2022/12/12 11:22  info  tunnel_stage_streaming -- Pipe data back and forth. ...
ssr-client 2022/12/12 11:22  info  ---- disconnected  "google.com:443" ----
ssr-client 2022/12/12 11:22  info  ==== tunnel destroyed   count   0 ====
```

**Comment by ssrlive** [comment]
你的服務端應該是修改過的。你可以安裝個python 服務端測試一把。

**Comment by wangsanshi123** [comment]
直接通过在网上下载安卓版的shadowsocksR的客户端是能使用的。安装python服务器怎样测试，应该先要安装客户端端吧？

**Comment by ssrlive** [comment]
最後再奉勸一句，這種很快就被封的節點，不用也罷。浪費的時間、精力不算錢的嗎？
