### ISSUE TITLE
建立后量子节点

### ISSUE THREAD

**Issue by oilel** [ShadowsocksR-Live/shadowsocksr-native#246]
目前找到的后量子VPN都是收费的，可能这是商机，所以很多公司就收费了。但是有人用Rust语言实现了Kyber算法，我利用Rust语言写了 https://github.com/oilel/pqt 。我为了用免费软件代替收费服务，就写了这款 pqt ；我认为网络安全和内存安全不应该作为商机和赚钱的工具，所以我写了免费的 pqt 。Lattice问题是抵抗量子计算机的，但是有些公司偏偏把它当作商机来卖Lattice算法的VPN，所以我抓紧学Rust语言，自己写了款免费的，希望引起重视（网络安全不应该作为商机）

**Comment by ssrlive** [comment]
不明覺厲，小夥子有志氣，期待你成功，注意安全，不要被條子找到。 也可以玩玩我的新玩具 [overtls](https://github.com/ssrlive/overtls)

**Comment by oilel** [comment]
> 不明覺厲

其实采用了几个第三方包，第三方实现了Kyber（基于Lattice的加密）。我没有实现这些加密算法，而是借用第三方实现的。

**Comment by oilel** [comment]
@ssrlive 其实现在Rust语言已经很热门了，不再是冷门语言。有些新语言的成长速度远远不及Rust，比如：Kyber算法（基于Lattice）都有第三方采用Rust实现（我写的软件就调用了这个第三方包），说明Rust语言的成长速度非常快。

**Comment by ssrlive** [comment]
我同意，因此我寫的所有新代碼都是 rust。寫 rust 代碼比過性生活更爽。

**Comment by oilel** [comment]
> 我同意

我是从来没写过C语言代码（顶多写过Hello World，用C语言输出Hello World），然后就直接用Rust语言了。就是说，C语言水平可能就留在Hello World阶段，然后直接用Rust写了。

**Comment by ssrlive** [comment]
別寫C了，我都被虐出心病了，看哪個指針都覺得下一秒就會爆炸。

**Comment by oilel** [comment]
> 別寫C了

Rust语言也有unsafe关键字，有时需要unsafe去除边界检查，这样要自己确保安全。

**Comment by ssrlive** [comment]
看看電子書 [Too Many Linked Lists](https://rust-unofficial.github.io/too-many-lists/) 就會對 unsafe 有個客觀的認識。

**Comment by oilel** [comment]
@ssrlive 但是我只提供软件，不提供VPS。还得劳烦别人买VPS，我没办法买硬件。

**Comment by oilel** [comment]
@ssrlive Tor（洋葱路由）和I2P（大蒜路由）的设计初衷不是翻墙，而是匿名；我写的pqt的设计初衷也是为了避免被量子计算机破解。如果Tor和I2P（还有zeronet、freenet、lokinet）容易被封的话，避免只是为了匿名，我这个协议也很容易被封，设计初衷只是对抗量子计算机，不是为了欺骗GFW以实现翻墙。

**Comment by ssrlive** [comment]
嗯。在GFW 面前，任何精巧的加密都是浪費表情，所以我的 overtls 砍掉了所有加密套接直接 走最 普通的 TLS ，GFW 終於老實了，不再封鎖我的節點。

**Comment by oilel** [comment]
> 所以我的 overtls 砍掉了所有加密套接

那就还要连接专门匿名或对抗量子计算机的VPS才行，翻墙成功以后，可以再连接匿名网络。

**Comment by ssrlive** [comment]
對。多級節可以走你的那種強加密節點。

**Comment by ssrlive** [comment]
但任何在網絡上的隱匿行蹤的努力，都有可能因爲一個小小的低級失誤而前功盡棄，就像 編程隨想 阮曉寰 的暴露，就是因爲二十年前創建 CSDN 帳號時使用的臨時密碼是 `rxh-temp` 而 CSDN 又發生過一次大規模泄漏，更糟糕的是 CSDN 存儲的是明文密碼而不是 密碼哈希，於是…… 所以在嚴密的規劃還是敵不過共匪針對 人性弱點 的攻擊。

**Comment by oilel** [comment]
@ssrlive 如果你浏览了一遍我的项目，会发现两件比较好笑的事：每个版本打包成.tar.xz文件发到项目里。因为我不知道git能否替换同名文件、git怎么管理版本，这些还没学会，所以我把每个版本打包成.tar.xz发到项目主页；单单这件事就好笑了。除此之外，流量被服务端解密以后，转发给 Privoxy （第三方代理），转发给 Privoxy 说明我还不知道如何处理浏览器的 HTTP 请求。

**Comment by ssrlive** [comment]
對於 github 在 B 站找個視頻一學就會。

**Comment by oilel** [comment]
> 對於 github 在 B 站找個視頻一學就會。

但是按照审查严重程度来排的话，应该是：B站>YouTube>BitChute。最后那个BitChute据说是英国公司，这个英国公司的审查居然比YouTube还宽松。BitChute会通过一些带有远见或仇恨言论的视频。

**Comment by ssrlive** [comment]
哦。沒上過。

**Comment by oilel** [comment]
> 哦。沒上過。

而且YouTube强制要求手机号注册，BitChute无需手机号即可注册。

**Comment by oilel** [comment]
@ssrlive 现在翻墙不一定走公网（Public Internet），可以走内网翻墙。IPLC（International Private Leased Circuit）就是内网，但是可以跨国连接，所以走内网可以翻墙，“内网”不一定指墙内的网络，跨国连接比如IPLC和IEPL都算内网，内网可以实现翻墙。

**Comment by ssrlive** [comment]
但內網還是要走海底光纜，而 GFW 的過濾設備就在光纜的入口點。 內網的節點難道不接受我黨的審查嗎？所以 IPLC 就是個都市傳說。

**Comment by oilel** [comment]
@ssrlive 我认为0.3.4版本稳定了，服务端搭配 Privoxy 就能用了。有没有必要给这款代理加上处理 GET POST CONNECT 等请求的代码？还是说就搭配 Privoxy 就好了？浏览器是通过 GET POST CONNECT 等请求来获取网站内容的，这款代理现在只是对抗一下量子计算机，最终处理 GET POST CONNECT 转交给 Privoxy 了。

**Comment by ssrlive** [comment]
沒必要。

**Comment by oilel** [comment]
除此之外， @ssrlive 这款代理的性能（网页加载速度）似乎会比Tor（洋葱路由）还慢一点，因为注重安全性，导致它比Tor慢。

**Comment by ssrlive** [comment]
夠用了

**Comment by oilel** [comment]
> listen-address  0.0.0.0:8118
> forward-socks5 / 127.0.0.1:1080 .

这里有错误，错误就是绑定到了0.0.0.0。因为Privoxy是给服务端解析HTTP请求的，仅仅辅助pqt，所以必须绑定到127.0.0.1或[::1]。假如绑定到0.0.0.0，万一客户端配置错误的话，就明文通信了；假设用户在中国内地，配置错误使得浏览器连接服务端Privoxy，然后连上Google查了一下IP地址确实在美国（说明这个用户还有点安全意识，还要查IP地址在不在外国），就以为自己是连接到pqt的，那太危险了；因此必须绑定到127.0.0.1或[::1]。

**Comment by oilel** [comment]
代理的工作原理参考 https://github.com/oilel/pqt/blob/main/%E5%8E%9F%E7%90%86.md ，只是简要概括。 @ssrlive

**Comment by oilel** [comment]
> 不要被條子找到。

如果你在台湾，可以fork一下项目。原项目被删，fork应该不受影响。

**Comment by oilel** [comment]
@ssrlive 除此之外，pqt代码里面有没有性能比较差的部分？有没有运行更快的写法？

**Comment by oilel** [comment]
> 不明覺厲，小夥子有志氣，期待你成功，注意安全，不要被條子找到。 也可以玩玩我的新玩具 [overtls](https://github.com/ssrlive/overtls)

你的overtls怎么转移到 https://github.com/ShadowsocksR-Live 名下了？

**Comment by ssrlive** [comment]
反正都是我的. SSRoT 不打算維護了. 這個作爲替代品.
