### ISSUE TITLE
nginx 无法启动

### ISSUE THREAD

**Issue by return2010** [ShadowsocksR-Live/shadowsocksr-native#252]
数字安全证书 部署到 web 服务器后，启动nginx失败：
nginx: [emerg] SSL_CTX_use_PrivateKey("/fakesite_cert/private_key.pem") failed (SSL: error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch)

**Comment by ssrlive** [comment]
如果你實在沒辦法，就重裝操作系統 ubuntu，再裝一次 服務端。

**Comment by return2010** [comment]
换了个域名重装可以了，之前没注意，godaddy申请的域名被墙了，
服务器端run起来了，
请教客户端一定也要特殊配置的，Potatso这种按照参数配置不能用？

**Comment by ssrlive** [comment]
協議已經無法後向兼容老舊的 土豆絲 了。自己編譯新的 客戶端吧。
