### ISSUE TITLE
我好像遇到了点问题

### ISSUE THREAD

**Issue by 9844201** [ShadowsocksR-Live/shadowsocksr-native#29]
ssr-server.exe:error: recieve data failed about _server_ "8.8.8.8": no buffer sp
ace available

**Comment by OneSecure** [comment]
server 的值必须是 0.0.0.0

**Comment by 9844201** [comment]
是0.0.0.0




------------------ 原始邮件 ------------------
发件人: "OneSecure"<notifications@github.com>;
发送时间: 2018年6月28日(星期四) 晚上9:45
收件人: "ShadowsocksR-Live/shadowsocksr-native"<shadowsocksr-native@noreply.github.com>;
抄送: "◕ ̯͡◕ぺCore"<9844201@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [ShadowsocksR-Live/shadowsocksr-native] 我好像遇到了点问题 (#29)




server 的值必须是 0.0.0.0

**Comment by 9844201** [comment]
------------------ 原始邮件 ------------------
发件人: "OneSecure"<notifications@github.com>;
发送时间: 2018年6月28日(星期四) 晚上9:45
收件人: "ShadowsocksR-Live/shadowsocksr-native"<shadowsocksr-native@noreply.github.com>;
抄送: "◕ ̯͡◕ぺCore"<9844201@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [ShadowsocksR-Live/shadowsocksr-native] 我好像遇到了点问题 (#29)




server 的值必须是 0.0.0.0

**Comment by ssrlive** [comment]
把 config.json 文件和 错误 信息贴出来

**Comment by 9844201** [comment]
{
    "server": "0.0.0.0",
    "server_port": 1443,
    "method": "aes-128-ctr",
    "password": "password",
    "protocol": "origin", // "auth_aes128_md5",
    "protocol_param": "",
    "obfs": "plain", // "tls1.2_ticket_auth",
    "obfs_param": "",
    "local_address": "127.0.0.1",
    "local_port": 1080,
    "udp": true,
    "timeout": 300
}

=========================================================

C:\Users\Administrator\Desktop\Release>ssr-server.exe -c C:\Users\Administrator\
Desktop\config.json
ssr-server.exe:info: ShadowsocksR native server

ssr-server.exe:info: listen port      1443
ssr-server.exe:info: method           aes-128-ctr
ssr-server.exe:info: password         password
ssr-server.exe:info: protocol         origin
ssr-server.exe:info: obfs             plain
ssr-server.exe:info: udp relay        yes

ssr-server.exe:error: recieve data failed about _server_ "8.8.8.8": no buffer sp
ace available
ssr-server.exe:error: recieve data failed about _server_ "8.8.8.8": no buffer sp
ace available
ssr-server.exe:error: recieve data failed about _server_ "8.8.8.8": no buffer sp
ace available
ssr-server.exe:error: recieve data failed about _server_ "8.8.8.8": no buffer sp
ace available
ssr-server.exe:error: recieve data failed about _server_ "8.8.8.8": no buffer sp
ace available
ssr-server.exe:error: recieve data failed about _server_ "8.8.8.8": no buffer sp
ace available
ssr-server.exe:error: recieve data failed about _server_ "8.8.8.8": no buffer sp
ace available
ssr-server.exe:error: recieve data failed about _server_ "8.8.8.8": no buffer sp
ace available
ssr-server.exe:error: recieve data failed about _server_ "8.8.8.8": no buffer sp
ace available
ssr-server.exe:error: recieve data failed about _server_ "go.microsoft.com": no
buffer space available
ssr-server.exe:error: recieve data failed about _server_ "go.microsoft.com": no
buffer space available
ssr-server.exe:error: recieve data failed about _server_ "8.8.8.8": no buffer sp
ace available
ssr-server.exe:error: recieve data failed about _server_ "8.8.8.8": no buffer sp
ace available
ssr-server.exe:error: recieve data failed about _server_ "8.8.8.8": no buffer sp
ace available
ssr-server.exe:error: recieve data failed about _server_ "8.8.8.8": no buffer sp
ace available
ssr-server.exe:error: recieve data failed about _server_ "8.8.8.8": no buffer sp
ace available
ssr-server.exe:error: recieve data failed about _server_ "8.8.8.8": no buffer sp
ace available
ssr-server.exe:error: recieve data failed about _server_ "8.8.8.8": no buffer sp
ace available
ssr-server.exe:error: recieve data failed about _server_ "8.8.8.8": no buffer sp
ace available
ssr-server.exe:error: recieve data failed about _server_ "8.8.8.8": no buffer sp
ace available
ssr-server.exe:error: recieve data failed about _server_ "8.8.8.8": no buffer sp
ace available
ssr-server.exe:error: recieve data failed about _server_ "8.8.8.8": no buffer sp
ace available
ssr-server.exe:error: recieve data failed about _server_ "8.8.8.8": no buffer sp
ace available
ssr-server.exe:error: recieve data failed about _server_ "8.8.8.8": no buffer sp
ace available
ssr-server.exe:error: recieve data failed about _server_ "8.8.8.8": no buffer sp
ace available
ssr-server.exe:error: recieve data failed about _server_ "8.8.8.8": no buffer sp
ace available
ssr-server.exe:error: recieve data failed about _server_ "8.8.8.8": no buffer sp
ace available
ssr-server.exe:error: recieve data failed about _server_ "8.8.8.8": no buffer sp
ace available
ssr-server.exe:error: recieve data failed about _server_ "8.8.8.8": no buffer sp
ace available
ssr-server.exe:error: recieve data failed about _server_ "8.8.8.8": no buffer sp
ace available
ssr-server.exe:error: recieve data failed about _server_ "8.8.8.8": no buffer sp
ace available
ssr-server.exe:error: recieve data failed about _server_ "8.8.8.8": no buffer sp
ace available
ssr-server.exe:error: recieve data failed about _server_ "8.8.8.8": no buffer sp
ace available
ssr-server.exe:error: recieve data failed about _server_ "8.8.8.8": no buffer sp
ace available
ssr-server.exe:error: recieve data failed about _server_ "8.8.8.8": no buffer sp
ace available

**Comment by ssrlive** [comment]
协议 和混淆 请用后者。
前者还没测试。

**Comment by 9844201** [comment]
谢谢 搞定了！
