### ISSUE TITLE
为什么我安装完之后输入命令显示“bash: ssr-server: 未找到命令”啊

### ISSUE THREAD

**Issue by WXiaoyao** [ShadowsocksR-Live/shadowsocksr-native#35]
Please answer these questions before submitting your issue. Thanks!

### What version of shadowsocks-libev are you using?
0.4

### What operating system are you using?
Linux kali 4.15.0-kali2-amd64 #1 SMP Debian 4.15.11-1kali1 (2018-03-21) x86_64 GNU/Linux

### What did you do?
我已完成了如下操作：
sudo su                       # using root account
apt-get install --no-install-recommends build-essential autoconf libtool asciidoc xmlto -y
apt-get install git gcc g++ cmake automake -y
apt-get -f install
apt-get update
apt-get upgrade
cd /                          # switch to root directory
git clone https://github.com/ShadowsocksR-Live/shadowsocksr-native.git
mv shadowsocksr-native ssr-n  # rename shadowsocksr-native to ssr-n
cd ssr-n                      # enter ssr-n directory. 
git submodule update --init
git submodule foreach -q 'git checkout $(git config -f $toplevel/.gitmodules submodule.$name.branch || echo master)'
cmake CMakeLists.txt && make

以及：
配置完config.json

然后命令行界面输入：
root@kali:~# ssr-server -c /ssr-n/config.json

### What did you expect to see?
我本以为至少会作为执行命令有输出，然而..

### What did you see instead?
系统显示——“bash: ssr-server: 未找到命令”

### What is your config in detail (with all sensitive info masked)?
{
    "server": "45.76.48.150",
    "server_port": 2018,
    "method": "chacha20-ietf",
    "password": "password(masked)",
    "protocol": "auth_chain_a",
    "protocol_param": "",
    "obfs": "plain", 
    "obfs_param": "",
    "local_address": "127.0.0.1",
    "local_port": 1080,
    "udp": true,
    "timeout": 300
}

**Comment by ssrlive** [comment]
没有复制到 /usr/bin 目录里. 你应该用全路径, 比如 /ssr-n/src/ssr-server -c  /ssr-n/config.json -d

**Comment by WXiaoyao** [comment]
嗯..按照你这样子去做确实可以执行命令了，谢谢！不过执行了命令之后应该是输出什么结果？像我这样的输出对吗：
root@kali:~# /ssr-n/src/ssr-server -c /ssr-n/config.json
ssr-server:info: ShadowsocksR native server

ssr-server:info: listen port      2018
ssr-server:info: method           chacha20-ietf
ssr-server:info: password         ********
ssr-server:info: protocol         auth_chain_a
ssr-server:info: obfs             plain
ssr-server:info: udp relay        yes

因为我不太懂这样子之后该做什么了..我试了下浏览器还是不能翻墙额

**Comment by ssrlive** [comment]
我操! 我不是奶妈. 自己弄去吧.    服务端 ssr-server     客户端 ssr-client 或 ssr-local    怎么部署. 怎么编译. 怎么 配置浏览器的 socks5 代理. 还要我一一道来吗?
如果你搞明白了. 欢迎写个详细教程. 然后 提交 PR . 
怎么样?

**Comment by WXiaoyao** [comment]
我没有向你支付过任何费用，所以我也从不认为你有一定要帮助我的义务，你先前给我回复让我以为看到了github上优秀的程序员们的分享和乐于帮助精神，呵呵。然而对于我之后的追问你完全可以回复说“剩下的那些细节你自己去查百度吧”或者不回复，我不会因此对你有任何的意见，反而会因为你回复了我在github上提的第一个问题而心存感激。但是你现在回我一个“我操”？？？你懂一点技术，你牛逼了？不过就算你技术真的很强，冲你这种态度我也鄙视你。

**Comment by ssrlive** [comment]
你丫开心就好。继续鄙视。
