### ISSUE TITLE
Install fail in linode debian 

### ISSUE THREAD

**Issue by xpoy1** [ShadowsocksR-Live/shadowsocksr-native#37]
Please answer these questions before submitting your issue. Thanks!

### What version of shadowsocks-native are you using?
last one

### What operating system are you using?
Linux version 4.15.13-x86_64-linode106 (maker@build.linode.com) (gcc version 4.9.2 (Debian 4.9.2-10+deb8u1)) #1 SMP Tue Mar 27 14:42:14 UTC 2018

### What did you do?
run install_sh

### What did you expect to see?
Install it 

### What did you see instead?
------------- DONE WITH COMPILER FLAG CHECKS. -------------

-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found.
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
CMake Error at libcork/cmake/FindCTargets.cmake:61 (target_include_directories):
  Unknown CMake command "target_include_directories".
Call Stack (most recent call first):
  libcork/CMakeLists.txt:98 (add_c_library)

-- Configuring incomplete, errors occurred!
/bin/cp: cannot stat `./shadowsocksr-native/src/ssr-server': No such file or directory
ShadowsocksR Native install failed, please contact @ssrlive

### What is your config in detail (with all sensitive info masked)?
default

**Comment by ssrlive** [comment]
your cmake version?
```
cmake --version
```

**Comment by xpoy1** [comment]
I tried to manual install newest cmake. The error is still there,  after check the install log,I found

> The following NEW packages will be installed:
>   cmake
> 0 upgraded, 1 newly installed, 0 to remove and 2 not upgraded.
> Need to get 0 B/4,730 kB of archives.
> After this operation, 11.6 MB of additional disk space will be used.
> Selecting previously unselected package cmake.
> (Reading database ... 34356 files and directories currently installed.)
> Unpacking cmake (from .../cmake_2.8.9-1_amd64.deb) ...

It replace cmake to the apt-get one.

I delete apt-get install command in install-ssr.sh. The autoconf report,

> autoreconf: running: /usr/bin/autoconf 
> configure.ac:8: error: possibly undefined macro: AC_CONFIG_MACRO_DIRS If this token and others are legitimate, please use m4_pattern_allow. See the Autoconf documentation. 
> autoreconf: /usr/bin/autoconf failed with exit status: 1 configure: error: cannot find install-sh, install.sh, or shtool in "." "./.." "./../.."

I will see what can I do

**Comment by ssrlive** [comment]
check out the new install script. i think it works fine in debian 8.x+
