### ISSUE TITLE
是个坑吧，安装完了不能用也不能卸载

### ISSUE THREAD

**Issue by rhsy445566** [ShadowsocksR-Live/shadowsocksr-native#39]
debian8 系统，。安装完了不能使用，哎，按照你给你命令也不能卸载

**Comment by ssrlive** [comment]
嘚便 系统本身 很不友好. 你要装两次. 你凭什么张嘴就说是坑? 骗你钱了吗?

**Comment by redstoneleo** [comment]
我想问一下在服务器上面怎么卸载shadowsocksr-native？

**Comment by ssrlive** [comment]
首頁 readme.md 有寫。
