### ISSUE TITLE
什么时候添加"aes256-gcm",     "chacha20-ietf-poly1305"支持 在encrypt 文件里

### ISSUE THREAD

**Issue by aishuidedabai** [ShadowsocksR-Live/shadowsocksr-native#4]
Please answer these questions before submitting your issue. Thanks!

**Comment by ssrlive** [comment]
目前腾不出时间. 你有心把它加进去然后提个 PR 怎样?

**Comment by aishuidedabai** [comment]
我在试

**Comment by aishuidedabai** [comment]
我改不出来，水平有限，您能抽个时间吗，我急需

**Comment by ssrlive** [comment]
经过阅读 [破娃酱的代码](https://github.com/ShadowsocksR-Live/shadowsocksr-csharp/blob/master/shadowsocks-csharp/Encryption/LibcryptoEncryptor.cs) ，没有发现 "aes256-gcm" 等算法， 这个算法是适用于 [Shadowsocks](http://shadowsocks.org/en/index.html) 后来加进去的 [AEAD 特性](http://shadowsocks.org/en/spec/AEAD-Ciphers) ，似乎不必理会。

**Comment by aishuidedabai** [comment]
你终于回我了，是的啊，这两个加密仅仅是ss才用，ssr并没有

**Comment by ssrlive** [comment]
你再看 SS 的新代码，AEAD 和 stream 流加密是两套不同的路径。

**Comment by aishuidedabai** [comment]
是的啊，完全不一样，但是当时他们已经预留了这两个加密的处理，水平低，补充不了

**Comment by ssrlive** [comment]
你看看 这一行。 
https://github.com/ShadowsocksR-Live/shadowsocksr-native/blob/master/src/obfs/obfs.c#L115
破娃酱注释掉了这段代码。你有无测试是否可用？

**Comment by aishuidedabai** [comment]
这段代码可以用，已测试，在src文件里面，全局搜一下，方法已经写好了

**Comment by ssrlive** [comment]
好的。我稍后更新。

**Comment by aishuidedabai** [comment]
sodium这个文件夹里面

**Comment by ssrlive** [comment]
破娃酱已经移除了 verify_simple, auth_simple, 等， 测试环境都没有了，你怎么测试通过的？用的是旧版？这些代码似乎没必要存在了，后向兼容都没有必要了。

https://github.com/ShadowsocksR-Live/shadowsocksr/blob/manyuser/CHANGES#L37

**Comment by aishuidedabai** [comment]
新版这个我也移除了，已经被淘汰了，你接下来要做什么，计划是什么

**Comment by ssrlive** [comment]
服务端 和 mac 版。

**Comment by aishuidedabai** [comment]
请问手机版（比如ios）你怎么加负载均衡，或者指定ip，域名走指定服务器

**Comment by ssrlive** [comment]
可以在遠程服務器上新開一個監聽端口, 隨時給手機客戶端報告服務端的當前狀態, 客服端再綜合分析所有服務端的狀態, 選擇一個遠程服務端.
