### ISSUE TITLE
[UDP] UDP转发内存很快超过15M，PacketTunnel崩溃

### ISSUE THREAD

**Issue by android0276** [ShadowsocksR-Live/shadowsocksr-native#40]
Please answer these questions before submitting your issue. Thanks!

### What version of shadowsocks-native are you using?
当前master分支

### What operating system are you using?
iOS11.4.1

### What did you do?
开启ssr的UDP转发，每打开一个app，连接数增加内存就增加，很快15M

### What did you expect to see?
UDP转发是不是存在内存泄露或是代码错误

**Comment by android0276** [comment]
![2018-09-05 at 8 05](https://user-images.githubusercontent.com/8524130/45092221-59ab6800-b147-11e8-8442-5aa4c168d8df.png)

**Comment by android0276** [comment]
![2018-09-05 at 8 05](https://user-images.githubusercontent.com/8524130/45092302-8fe8e780-b147-11e8-88d6-19cfb0b793ef.png)

**Comment by ssrlive** [comment]
经反复检查代码, 没有 发现泄漏 不知你遇到了什么情况.
![tu](https://files.gitter.im/ShadowsocksR-Live/Lobby/UKLb/image.png)

**Comment by android0276** [comment]
我使用的是Google开源项目Outline进行的测试，这个是个基于Tun2socks的包处理，在之前的potasto的基础上改过，你可以看下handleUDPPacket这个方法，文件地址：https://github.com/Jigsaw-Code/outline-client/blob/master/third_party/Potatso/PacketProcessor/TunnelInterface.m ，目前光DNS解析就会出现ssrlocal内存剧增最后崩溃的问题

**Comment by ssrlive** [comment]
真诚希望你能跟踪一下代码，找出问题所在。目前我没在iOS项目上工作，没有调试环境。udp relay 模块是独立的，可以与主模块随意拆装，不影响主模块的工作。

**Comment by android0276** [comment]
可以的，最近工作比较忙，后面闲下来我去跟踪下，谢谢热情的作者

**Comment by ssrlive** [comment]
不再修正，因为 SSRoT 已经实现了 UDP 代理。各位有时间请参与测试。
