### ISSUE TITLE
Diconnecting Telegram when use SSR

### ISSUE THREAD

**Issue by speedsharj** [ShadowsocksR-Live/shadowsocksr-native#44]
Hi
I have problem in iran, i use SSR and config it with this information
"Encryption": "aes-128-cfb",
"Port": 4030,
"Protocol": "auth_chain_a",
"Obfs": "tls1.2_ticket_auth",
"Obfs_param": "",
"Protocol_param": "",

But only when use telegram app, in top of ke telegram shows connecting in every seconds, and it's seems disconnect ssr, but it's connected
only in telegram i have this problem, in iran telegram has filtered , and must connect with vpn or proxy
Please help me, and if you know,please send me net config for SSR

**Comment by ssrlive** [comment]
Since telegram have changed there codebase from June 1, 2018, the iOS
client can’t work with normal vpn client. So you must install mtproto proxy
server yourself.
