### ISSUE TITLE
google blocked

### ISSUE THREAD

**Issue by agavrel** [ShadowsocksR-Live/shadowsocksr-native#49]
### What did you do?

Trying to use google using the server and client.

**client side:**
./ssr-client 
ssr-client:info: ShadowsocksR native client

ssr-client:info: remote server    **********:443
ssr-client:info: method           chacha20
ssr-client:info: password         ********
ssr-client:info: protocol         origin
ssr-client:info: obfs             http_simple
ssr-client:info: udp relay        yes

ssr-client:info: listening on     0.0.0.0:1080

**and on server**
systemctl restart ssr-native.service (config below)

### What did you expect to see?

google.com / youtube.com working (im in China)

### What did you see instead?
In terminal:
```
ssr-client:error: connect failed about _server_ "www.google.com.sg": connection refused
```
and in chrome:
```
This site can’t be reached The webpage at https://www.google.com.sg might be temporarily down or it may have moved permanently to a new web address.
ERR_QUIC_PROTOCOL_ERROR
```

### What is your config in detail (with all sensitive info masked)?
cat /etc/ssr-native/config.json 
```json
{
    "server": "****************",
    "server_port": 443,
    "password": "**************",
    "method": "chacha20",
    "protocol": "origin",
    "protocol_param": "",
    "obfs": "http_simple",
    "obfs_param": "",
    "local_address": "0.0.0.0",
    "local_port": 1080,
    "udp": true,
    "timeout": 300
}
```

**Comment by agavrel** [comment]
Do I need to have OpenVPN on top of SSR ?  (you might want to contact me through email ?)

**Comment by ssrlive** [comment]
don't use `http_simple` as obfuscater. it's not safe.

Please use the sample settings. 
https://github.com/ShadowsocksR-Live/shadowsocksr-native/#sample-configure-file

**Comment by agavrel** [comment]
Ok I switched to :
**server**
```json
{
    "server": "{XXX.XX.XXX.XXX}",
    "server_port": 443,
    "method": "aes-128-ctr",
    "password": "password",
    "protocol": "auth_aes128_md5",
    "protocol_param": "",
    "obfs": "tls1.2_ticket_auth",
    "obfs_param": "",
    "local_address": "0.0.0.0",
    "local_port": 1080,
    "udp": true,
    "timeout": 300
}
```
client
```json
{
    "server": "{XXX.XX.XXX.XXX}",
    "server_port": 443,
    "method": "aes-128-ctr",
    "password": "password",
    "protocol": "auth_aes128_md5",
    "protocol_param": "",
    "obfs": "tls1.2_ticket_auth",
    "obfs_param": "",
    "local_address": "0.0.0.0",
    "local_port": 1080,
    "udp": true,
    "timeout": 300
}
```

But still nothing. Could it be that the VPS has been flagged and I need to use a new one ?

**Comment by ssrlive** [comment]
please test your ip and port with this website: http://old.tool.chinaz.com/port/

**Comment by agavrel** [comment]
where should I click exactly? I am not chinese

**Comment by ssrlive** [comment]
As a programmer, you are not qualified!
![image](https://user-images.githubusercontent.com/30760636/54874748-5e5a1400-4e2c-11e9-912b-19ed609c23fe.png)

**Comment by agavrel** [comment]
It was greyed out before but thank for the tip ;)

**ssh ports:**  80,8080,3128,8081,9080,1080,21,23,443,69,22,25,110,7001,9090,3389,1521,1158,2100,1433

**IP:** 106.XXX.XXX.XXX Chengdu (I had to go another [website](https://www.whatismyip.com/)) which is different from shadowsocksR server 12X.XXX.XXX.XXX 


On the server I checked the status:
```
systemctl status ssr-native.service
● ssr-native.service - ssr-native
   Loaded: loaded (/lib/systemd/system/ssr-native.service; enabled; vendor preset: enabled)
   Active: active (running) since Sat 2019-03-23 03:13:15 UTC; 1 day 3h ago
  Process: 13868 ExecStop=/etc/init.d/ssr-native stop (code=exited, status=0/SUCCESS)
  Process: 13876 ExecStart=/etc/init.d/ssr-native start (code=exited, status=0/SUCCESS)
 Main PID: 13890 (ssr-server)
    Tasks: 1 (limit: 1152)
   Memory: 924.0K
   CGroup: /system.slice/ssr-native.service
           └─13890 /usr/bin/ssr-server -d -c /etc/ssr-native/config.json

Mar 23 05:13:15 XXX systemd[1]: Starting ssr-native...
Mar 23 05:13:15 XXX ssr-native[13876]: Starting ShadowsocksR Native success
Mar 23 05:13:15 XXX systemd[1]: Started ssr-native.
```

**Comment by agavrel** [comment]
If it can help:

sudo iptables -L (on client)
```
Chain INPUT (policy ACCEPT)
target     prot opt source               destination         
ACCEPT     udp  --  anywhere             anywhere             udp dpt:domain
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:domain
ACCEPT     udp  --  anywhere             anywhere             udp dpt:bootps
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:bootps
ACCEPT     tcp  --  localhost            anywhere             tcp dpt:openvpn
DROP       tcp  --  anywhere             anywhere             tcp dpt:openvpn
ACCEPT     tcp  --  localhost            anywhere             tcp dpt:openvpn
DROP       tcp  --  anywhere             anywhere             tcp dpt:openvpn

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination         
ACCEPT     all  --  anywhere             192.168.122.0/24     ctstate RELATED,ESTABLISHED
ACCEPT     all  --  192.168.122.0/24     anywhere            
ACCEPT     all  --  anywhere             anywhere            
REJECT     all  --  anywhere             anywhere             reject-with icmp-port-unreachable
REJECT     all  --  anywhere             anywhere             reject-with icmp-port-unreachable

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         
ACCEPT     udp  --  anywhere             anywhere             udp dpt:bootpc

```

on server:

```
Chain INPUT (policy ACCEPT)
target     prot opt source               destination         

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination   
```

**Comment by agavrel** [comment]
**server**

netstat -tulpn | grep 443

`tcp        0      0 0.0.0.0:443             0.0.0.0:*               LISTEN `

**Comment by agavrel** [comment]
Also is the  "local_address": "0.0.0.0", correct ? in both client and server ?

**Comment by ssrlive** [comment]
Test your VPS `server`  ip and `SSH` port (such as 22 for normal or dynamic number in `bandwagonhost`) with this website: http://old.tool.chinaz.com/port/

in server, 'local_address' is `not` work. 
in client, you'd better set `local_address` to `0.0.0.0`.

**Comment by agavrel** [comment]
I dont know why but my computer (client) cant access anything while using vpn... like if I had been flagged by the gfw -_-
do u have a whatsapp/telegram/wechat?

**Comment by ssrlive** [comment]
I don't leak my real information. I will fight with China Communism Party, CCP, till it crushed.
you can email me with your VPS login IP, SSH port, and password. ssrlivebox(at)gmail(dot)com.
