### ISSUE TITLE
建立第一个连接后程序直接退出

### ISSUE THREAD

**Issue by NyanChanMeow** [ShadowsocksR-Live/shadowsocksr-native#50]
Please answer these questions before submitting your issue. Thanks!

### What version of shadowsocks-native are you using?
shadowsocks-libev 3.0.1 with MBEDTLS_VERSION_TEXT

### What operating system are you using?
Windows 10

### What did you do?
通过Readme中的说明自行编译了Shadowsocksr-native，使用VS2017编译，Windows SDK版本10.0.17134.0，平台工具集 v141，在更新依赖库时并未成功拉取libuv，所以我从[这里](https://github.com/ShadowsocksR-Live/libuv) git clone了libuv并成功编译。

### What did you see instead?

```
 2019-04-22 13:00:40 INFO: protocol auth_aes128_sha1
 2019-04-22 13:00:40 INFO: protocol_param
 2019-04-22 13:00:40 INFO: method chacha20
 2019-04-22 13:00:40 INFO: obfs plain
 2019-04-22 13:00:40 INFO: obfs_param
 2019-04-22 13:00:40 INFO: initializing ciphers... chacha20
 2019-04-22 13:00:40 INFO: listening at 127.0.0.1:1081
 2019-04-22 13:00:45 INFO: connect to www.speedtest.net:443 via *******:******
```
随后程序退出，没有其他输出，这是Verbose模式下的日志

### What is your config in detail (with all sensitive info masked)?

```
{
    "server": "********",
    "server_port": 1234,
    "method": "chacha20",
    "protocol": "auth_aes128_sha1",
    "obfs": "plain",
    "plugin": "",
    "password": "*******",
    "protocol_param": "",
    "obfsparam": "",
    "plugin_opts": "",
    "plugin_args": "",
    "remarks": "\\ud83c\\udded\\ud83c\\uddf0 ******",
    "group": "*******",
    "timeout": 10,
    "local_port": 1081,
    "local_address": "127.0.0.1",
    "fastopen": false,
    "obfs_param": ""
}
```

**Comment by ssrlive** [comment]
有没有直接试过编译好的[二进制发行包](https://github.com/ShadowsocksR-Live/shadowsocksr-native/releases/tag/0.5)?

**Comment by NyanChanMeow** [comment]
使用 Tag 0.5 Windows x64的二进制发行包在chacha20加密方式下出现 ERROR: Cannot generate key and IV

**Comment by ssrlive** [comment]
OK 知道了. 但目前没时间调试. 主要精力全部在 overTLS 分支上. 处理这些的日程会很靠后了.

**Comment by ssrlive** [comment]
刚刚测试过. 没有问题. 如下图. 我的配置文件内容是这样的:
```
{
    "server": "fuckcpcgfw.gov",
    "server_port": 24987,
    "password": "passas98632",
    "method": "chacha20",
    "protocol": "auth_aes128_sha1",
    "protocol_param": "",
    "obfs": "plain",
    "obfs_param": "",
    "local_address": "0.0.0.0",
    "local_port": 2080,
    "udp": true,
    "timeout": 300
}
```
你可以照葫芦画瓢试一下.
![image](https://user-images.githubusercontent.com/30760636/56551536-3260b880-65bb-11e9-8d51-f5207f9d9345.png)

**Comment by ssrlive** [comment]
如果还是报错, 请将[这一行(1176)](https://github.com/ShadowsocksR-Live/shadowsocksr-native/blob/master/src/encrypt.c#L1176) 移动到 [这里(1147)](https://github.com/ShadowsocksR-Live/shadowsocksr-native/blob/master/src/encrypt.c#L1147), 看是不是正常. 没用过 VS2017, 不确定编译器是否改变了生成代码的策略.
