### ISSUE TITLE
YouTube和Instagram无法上传视频

### ISSUE THREAD

**Issue by ReyLiang** [ShadowsocksR-Live/shadowsocksr-native#52]
### What version of shadowsocks-native are you using?
https://github.com/ShadowsocksR-Live/shadowsocksr-native/tree/2bd2deb8379f6b11595daba3e393a856d260fea9

### What operating system are you using?
IOS iShadowsocksR最新版

### What did you do?
全局模式下YouTube和Instagram无法上传视频.
ss和ssr节点都不可以,但是pc和android可以

### What did you expect to see?
是否可以查下原因?

**Comment by ssrlive** [comment]
感谢发现这个比较严重的问题。但目前我卡在 overtls 分支上，好长时间估计都无法分手处理这个。

**Comment by yeluoqiuzhi** [comment]
好的，谢谢，这真是个大问题

**Comment by yeluoqiuzhi** [comment]
虽然不能解决，告诉什么原因也行呢，谢谢

**Comment by TheWanderingCoel** [comment]
这个问题也可以在speedtest上传测速中复现,不知道什么问题

**Comment by ssrlive** [comment]
现在测试一下上传功能, 看有无问题?

**Comment by xiocode** [comment]
> 现在测试一下上传功能, 看有无问题?

刚刚使用Google Drive上传一个200M的视频同样出现上传失败，虽然有上行流量，但是进度一直为0
使用最新的master编译，系统 OSX 10.14.6

**Comment by ssrlive** [comment]
小文件呢? 比如 5 mb 以下的文件. 能成功上传吗? 请使用 ssr-client 测试, 不要使用 ssr-local.

**Comment by xiocode** [comment]
> 小文件呢? 比如 5 mb 以下的文件. 能成功上传吗? 请使用 ssr-client 测试, 不要使用 ssr-local.
> 我 30 m 小破移动网络连个 g drive 首页都加载不出来.
> 
> ![Screen Shot 2019-08-12 at 9 20 37 PM](https://user-images.githubusercontent.com/30760636/62867967-1e49ee00-bd47-11e9-9ee7-89f1bb12b20c.png)
> 
> ![Screen Shot 2019-08-12 at 9 23 21 PM](https://user-images.githubusercontent.com/30760636/62868196-ab8d4280-bd47-11e9-92de-9d4baea2071e.png)
> 
> 貌似小文件没问题.
> 不知 到 哪个体量 会出错.

恩，我是用的ssr-local，我试试ssr-client

**Comment by xiocode** [comment]
> 小文件呢? 比如 5 mb 以下的文件. 能成功上传吗? 请使用 ssr-client 测试, 不要使用 ssr-local.
> 我 30 m 小破移动网络连个 g drive 首页都加载不出来.
> 
> ![Screen Shot 2019-08-12 at 9 20 37 PM](https://user-images.githubusercontent.com/30760636/62867967-1e49ee00-bd47-11e9-9ee7-89f1bb12b20c.png)
> 
> ![Screen Shot 2019-08-12 at 9 23 21 PM](https://user-images.githubusercontent.com/30760636/62868196-ab8d4280-bd47-11e9-92de-9d4baea2071e.png)
> 
> 貌似小文件没问题.
> 不知 到 哪个体量 会出错.

用ssr-client也是一样的问题，然后我测试了100KB，1M，10M，50M，100M的文件
到10M没有什么问题，但是在50M的时候比较明显的就是上传速度不稳定，会断，然后上传时间大概是正常上传的5X以上时间，100M上传不了

**Comment by xiocode** [comment]
然后我开了Surge看了一下网络，能比较明显的看到上传是间歇性的有速度，不连续

**Comment by ssrlive** [comment]
你的服务器是哪个? 如果是 python 版的话, 也许没法解决. 如果是 ssr-n 版的, 我就可以跟踪一下原因.

**Comment by xiocode** [comment]
好吧，服务器端是python的
