### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by ittat** [ShadowsocksR-Live/shadowsocksr-native#54]
/home/bignco/ssr-n/depends/json-c/staticbuild/..
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal -I autoconf-archive/m4
autoreconf: configure.ac: tracing
autoreconf: configure.ac: not using Libtool
autoreconf: running: /usr/bin/autoconf
autoreconf: running: /usr/bin/autoheader
autoreconf: running: automake --add-missing --copy --no-force
Makefile.am:15: error: Libtool library used but 'LIBTOOL' is undefined
Makefile.am:15:   The usual way to define 'LIBTOOL' is to add 'LT_INIT'
Makefile.am:15:   to 'configure.ac' and run 'aclocal' and 'autoconf' again.
Makefile.am:15:   If 'LT_INIT' is in 'configure.ac', make sure
Makefile.am:15:   its definition is in aclocal's search path.
autoreconf: automake failed with exit status: 1
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make sets $(MAKE)... (cached) yes
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
Multi-threaded support disabled. Use --enable-threading to enable.
RDRAND Hardware RNG Hash Seed disabled. Use --enable-rdrand to enable
checking whether make supports nested variables... (cached) yes
checking for style of include used by make... GNU
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... gcc3
checking for gcc option to accept ISO C99... none needed
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking fcntl.h usability... yes
checking fcntl.h presence... yes
checking for fcntl.h... yes
checking limits.h usability... yes
checking limits.h presence... yes
checking for limits.h... yes
checking for strings.h... (cached) yes
checking syslog.h usability... yes
checking syslog.h presence... yes
checking for syslog.h... yes
checking for unistd.h... (cached) yes
checking sys/cdefs.h usability... yes
checking sys/cdefs.h presence... yes
checking for sys/cdefs.h... yes
checking sys/param.h usability... yes
checking sys/param.h presence... yes
checking for sys/param.h... yes
checking stdarg.h usability... yes
checking stdarg.h presence... yes
checking for stdarg.h... yes
checking locale.h usability... yes
checking locale.h presence... yes
checking for locale.h... yes
checking xlocale.h usability... yes
checking xlocale.h presence... yes
checking for xlocale.h... yes
checking endian.h usability... yes
checking endian.h presence... yes
checking for endian.h... yes
checking for inttypes.h... (cached) yes
checking for an ANSI C-conforming const... yes
checking for size_t... yes
checking for __thread support... yes
checking for vprintf... yes
checking for _doprnt... no
checking for working memcmp... yes
checking for realloc... yes
checking for strcasecmp... yes
checking for strdup... yes
checking for strerror... yes
checking for snprintf... yes
checking for vsnprintf... yes
checking for vasprintf... yes
checking for open... yes
checking for vsyslog... yes
checking for strncasecmp... yes
checking for setlocale... yes
checking whether INFINITY is declared... yes
checking whether nan is declared... yes
checking whether isnan is declared... yes
checking whether isinf is declared... yes
checking whether _isnan is declared... no
checking whether _finite is declared... no
checking for GCC atomic builtins... yes
checking for uselocale... yes
checking if .gnu.warning accepts long strings... no
/home/bignco/ssr-n/depends/json-c/staticbuild/../configure: line 5144: LT_INIT: command not found
checking for -Bsymbolic-functions linker flag... yes
checking whether C compiler accepts -Wall... yes
checking whether C compiler accepts -Werror... yes
checking whether C compiler accepts -Wcast-qual... yes
checking whether C compiler accepts -Wno-error=deprecated-declarations... yes
checking whether C compiler accepts -Wextra... yes
checking whether C compiler accepts -Wwrite-string... no
checking whether C compiler accepts -Wno-unused-parameter... yes
checking whether C compiler accepts -D_GNU_SOURCE... yes
checking for compatibility with _REENTRANT and toolchain headers... yes
checking whether C compiler accepts -D_REENTRANT... yes
checking size of int... 4
checking size of long... 8
checking size of long long... 8
checking size of size_t... 8
checking size of int64_t... 8
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: error: cannot find input file: `Makefile.in'
CMake Error at depends/json-c/staticbuild/CMakeLists.txt:47 (file):
  file COPY cannot find
  "/home/bignco/ssr-n/depends/json-c/staticbuild/../config.h".

CMake Error at depends/json-c/staticbuild/CMakeLists.txt:48 (file):
  file COPY cannot find
  "/home/bignco/ssr-n/depends/json-c/staticbuild/../json_config.h".

-- Configuring incomplete, errors occurred!
See also "/home/bignco/ssr-n/CMakeFiles/CMakeOutput.log".
See also "/home/bignco/ssr-n/CMakeFiles/CMakeError.log".

**Comment by ssrlive** [comment]
请使用 CentOS 7 或者 ubuntu 18.04 以上. 其它系统总有奇奇怪怪的问题.

**Comment by ittat** [comment]
今天尝试在mac 10.14下编译报同样错误

**Comment by ssrlive** [comment]
你应该用主要错误信息在Google上搜索而不是发issue。

**Comment by ssrlive** [comment]
```
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
brew install git cmake automake libtool
brew upgrade git cmake automake libtool
```
