### ISSUE TITLE
How to config Xcode project for macOS? What's the ideal config for macOS compilation?

### ISSUE THREAD

**Issue by zhangzhe192608** [ShadowsocksR-Live/shadowsocksr-native#55]
### What version of shadowsocks-native are you using?
`HEAD` of this repo.

### What operating system are you using?
macOS

### What did you do?
I was trying to compile `ssrLocal macOS` however there seems to be a lot of missing staff, including:
- Linked Frameworks and Libraries
  - I added the dependencies according to the iOS project except `libpcre` because Xcode said it is an iOS dependency
- Header search path
  - I added the header search paths according to the iOS project:
    `../libcork/include ../libipset/include ../depends/pcre ../depends/libuv/include ../depends/mbedtls/include ../depends/libsodium/src/libsodium/include ../depends/libsodium/ssrbuild/include ../depends/libsodium/src/libsodium/include/sodium`
- Preprocessor Macros
  - I also copied from the iOS project:
     `MODULE_LOCAL inet_XtoX_no_ntop USE_CRYPTO_MBEDTLS HAVE_CONFIG_H $(inherited)`

**However, I cannot compile `ssrLocal.xcodeproj` for both iOS and macOS. What should I do?**

### What did you expect to see?
The compilation passed without any errors.

### What did you see instead?

Actually the compilation passed. However, I am not sure whether is is a correct way to do so.

### What is your config in detail (with all sensitive info masked)?

No need to provide this.

**Comment by ssrlive** [comment]
Using ssrNative in macOS instead.

**Comment by ssrlive** [comment]
Sometimes in the future, ssrLocal will be removed.

**Comment by zhangzhe192608** [comment]
@ssrlive Thanks for your prompt reply!

When I was using `ssrNative`, there were several missing headers and I added then accordingly to the header search path:
- ../depends/mbedtls/include ../src 
- ../depends/http-parser/ 
- ../depends/uv-mbed/include/

After that, there are still several erros:

```
Error Group
:-1: Undefined symbol: _http_headers_destroy
:-1: Undefined symbol: _http_headers_get_field_val
:-1: Undefined symbol: _http_headers_get_status
:-1: Undefined symbol: _http_headers_parse
:-1: Undefined symbol: _websocket_build_frame
:-1: Undefined symbol: _websocket_generate_sec_websocket_accept
:-1: Undefined symbol: _websocket_generate_sec_websocket_key
:-1: Undefined symbol: _websocket_retrieve_payload
```

What should I do?

**Comment by ssrlive** [comment]
Add the .c files to the project.

**Comment by zhangzhe192608** [comment]
@ssrlive 

Sorry, what do you mean by `.c` files? I tried to add the missing files from `./src/*` but the error is still:

```
:-1: Undefined symbol: _http_headers_destroy
:-1: Undefined symbol: _http_headers_get_field_val
:-1: Undefined symbol: _http_headers_get_status
:-1: Undefined symbol: _http_headers_parse
:-1: Undefined symbol: _websocket_build_frame
:-1: Undefined symbol: _websocket_generate_sec_websocket_accept
:-1: Undefined symbol: _websocket_generate_sec_websocket_key
:-1: Undefined symbol: _websocket_retrieve_payload
```

**Comment by zhangzhe192608** [comment]
Hello @ssrlive, here is an update! The good news it that I can compile the project by adding the source files into the target's 'Compile Sources':

<img width="652" alt="image" src="https://user-images.githubusercontent.com/52370360/60395185-595edc00-9b62-11e9-8593-40d256ee5ea6.png">


Am I dong this right?

**Comment by ssrlive** [comment]
yes

**Comment by zhangzhe192608** [comment]
Thank you so much for your kind help, @ssrlive!

Best wishes to you!

I'm closing this issue and may open it again if I have any further questions.
