### ISSUE TITLE
[UDP] ssr-client.exe windows上无法正常使用ssr-local却可以?

### ISSUE THREAD

**Issue by shouhujishu** [ShadowsocksR-Live/shadowsocksr-native#58]
Please answer these questions before submitting your issue. Thanks!

### What version of shadowsocks-native are you using?
releases 0.5   X86

### What operating system are you using?
windows10

### What did you do?
TCP  UDP通讯测试

### What did you expect to see?
TCP UDP正常可使用

### What did you see instead?
同配置文件下
client TCP:       
ssr-client.exe:error: connect failed about _server_ "detectportal.firefox.com": connection refused
ssr-client.exe:error: connect failed about _server_ "accounts.firefox.com.cn": connection refused
ssr-client.exe:error: connect failed about _server_ "push.services.mozilla.com": connection refused
ssr-client.exe:error: connect failed about _server_ "addons.g-fox.cn": connection refused
ssr-client.exe:error: connect failed about _server_ "addons.g-fox.cn": connection refused
ssr-client.exe:error: connect failed about _server_ "tiles.services.mozilla.com": connection refused
ssr-client.exe:error: connect failed about _server_ "addons.g-fox.cn": connection refused
ssr-client.exe:error: connect failed about _server_ "tiles.services.mozilla.com": connection refused
ssr-client.exe:error: connect failed about _server_ "accounts.firefox.com.cn": connection refused
UDP:一直提示超时(或无任何反应)

ssr-local TCP:  正常 UDP:不支持无法测试

### What is your config in detail (with all sensitive info masked)?
{
    "server": "",
    "server_port": 10102,
    "password": "ExK7yXeCCCC",
    "method": "aes-256-cfb",
    "protocol": "origin",
    "protocol_param": "",
    "obfs": "plain",
    "obfs_param": "",
    "local_address": "0.0.0.0",
    "local_port": 1083,
    "udp": true,
    "timeout": 300
}

希望作者能给些帮助

**Comment by ssrlive** [comment]
在弄 tls 没空弄 udp

**Comment by ssrlive** [comment]
代码在哪里，任何平台都可以编辑编译，要不你弄弄？

**Comment by shouhujishu** [comment]
> 代码在哪里，任何平台都可以编辑编译，要不你弄弄？

已经下载代码编译出来的一样 在尝试找问题

**Comment by shouhujishu** [comment]
> 代码在那里，任何平台都可以编辑编译，要不你弄弄？

通过抓包发现 UDP通信时 客户端没有跟服务器端有任何数据交换 我应该从 UV_UDP_RECV 开始检查吗？希望得到些帮助谢谢

**Comment by ssrlive** [comment]
好吧，我说一下我在 udp 上的困境，如果还是保持原样坚持继续与服务器使用 udp
通讯，服务器的收发包例程将分不清到底是来自客户端还是目标网站的，因此，这样的情况造成混乱。
原 local 的做法是假设客户端同一时刻只有一个udp包进来，然后发到服务器，服务器也认为只有一个包可发走，发完就傻等，非常低效。
目前正从事 tls 开发，使用 websocket 协议，它是基于帧的通讯协议，这样完成以后，就可以通过这个tcp通道传输 udp
数据包，没有了前述的混乱低效了。

**Comment by shouhujishu** [comment]
> 好吧，说一下目前在udp上的困境，如果还是保持原样坚持继续与服务器使用udp通讯，服务器的收发包例程将分不清到底是来自客户端还是目标网站的，因此，这样的情况造成混乱。原地的做法是假设客户端同一时刻只有一个udp包进来，然后发到服务器，服务器也认为只有一个包可发走，发完就傻等，非常低效。目前正从事tls开发，使用websocket协议，它是基于帧的通讯协议，这样完成以后，就可以通过这个tcp通道传输udp数据包，没有了前述的混乱低效了。

不是通过端口号来区分的木

**Comment by ssrlive** [comment]
```
     * SOCKS5 UDP Request
     * +----+------+------+----------+----------+----------+
     * |RSV | FRAG | ATYP | DST.ADDR | DST.PORT |   DATA   |
     * +----+------+------+----------+----------+----------+
     * | 2  |  1   |  1   | Variable |    2     | Variable |
     * +----+------+------+----------+----------+----------+
     *
     * SOCKS5 UDP Response
     * +----+------+------+----------+----------+----------+
     * |RSV | FRAG | ATYP | DST.ADDR | DST.PORT |   DATA   |
     * +----+------+------+----------+----------+----------+
     * | 2  |  1   |  1   | Variable |    2     | Variable |
     * +----+------+------+----------+----------+----------+
```
服务端收到这么一个 upd 类型 request 包以后，判断不了它是来自外网，还是来自客户端。这就是困境。

**Comment by lpflhh** [comment]
> ```
>      * SOCKS5 UDP Request
>      * +----+------+------+----------+----------+----------+
>      * |RSV | FRAG | ATYP | DST.ADDR | DST.PORT |   DATA   |
>      * +----+------+------+----------+----------+----------+
>      * | 2  |  1   |  1   | Variable |    2     | Variable |
>      * +----+------+------+----------+----------+----------+
>      *
>      * SOCKS5 UDP Response
>      * +----+------+------+----------+----------+----------+
>      * |RSV | FRAG | ATYP | DST.ADDR | DST.PORT |   DATA   |
>      * +----+------+------+----------+----------+----------+
>      * | 2  |  1   |  1   | Variable |    2     | Variable |
>      * +----+------+------+----------+----------+----------+
> ```
> 
> 服务端收到这么一个 upd 类型 request 包以后，判断不了它是来自外网，还是来自客户端。这就是困境。
> 我们的场景是，用户App发送来的udp包的接收者（ssr客户端）和 最终发送者（ssr服务端）不是同一个进程，它们位于距离遥远的两台电脑上。
> 
> 这些包如果通过 tcp 传输到服务器上，这些问题就不存在了。相当于 接收者和最终发送者是同一个进程。
> 
> 这就是SSR系统与 普通 socks5 代理服务器的本质区别。

这一点请参考v2ray，貌似有现成的代码，同样是使用 websocket 协议，希望有帮助，加油！

**Comment by ssrlive** [comment]
不再修正，因为 SSRoT 已经实现了 UDP 代理。各位有时间请参与测试。
