### ISSUE TITLE
host is unreachable

### ISSUE THREAD

**Issue by AldarisX** [ShadowsocksR-Live/shadowsocksr-native#59]
Please answer these questions before submitting your issue. Thanks!

### What version of shadowsocks-native are you using?
master(7807696)，0.5

### What operating system are you using?
Centos7

### What did you do?
跑服务端(auth_chain_a)

### What did you expect to see?
访问google

### What did you see instead?
host is unreachable

### What is your config in detail (with all sensitive info masked)?
下面是两个配置文件，都用过，一个错误
{
    "server": "----",
    "server_port": 8443,
    "method": "none",
    "password": "----",
    "protocol": "auth_chain_a",
    "protocol_param": "",
    "obfs": "tls1.2_ticket_auth",
    "obfs_param": "",
    "udp": true,
    "timeout": 300
}

{
    "password": "----",
    "method": "none",
    "protocol": "auth_chain_a",
    "protocol_param": "",
    "obfs": "tls1.2_ticket_auth",
    "obfs_param": "",

    "udp": false,
    "timeout": 300,

    "server_settings": {
        "listen_address": "0.0.0.0",
        "listen_port": 8443
    },

    "client_settings": {
        "server": "----",
        "server_port": 8443,
        "listen_address": "127.0.0.1",
        "listen_port": 1080
    },

    "over_tls_settings": {
        "enable": false,
        "server_domain": "goodsitesample.com",
        "path": "/udg151df/",
        "root_cert_file": ""
    }
}

**Comment by ssrlive** [comment]
上面那个已经废弃. 它 只适用于 ssr-local, 而 ssr-local 不久之后将删除.

下面那个才接受支持.

**Comment by ssrlive** [comment]
用 auth_aes128_md5 吧. 其它那些都没保障.
