### ISSUE TITLE
Windows平台编译不过，大佬能否给些提示？

### ISSUE THREAD

**Issue by rockswang** [ShadowsocksR-Live/shadowsocksr-native#60]
装了Visual Studio 2019，打开.sln文件后按照提示升级了项目，构建时出了很多错误，目前看到最多的是libuv子项目找不到poll.h
试着装了个mingw，但是include文件夹里并没有poll.h，没咒念了……
以前搞java的，vs和windows编程实在是不熟，求哪位大佬给些提示，可有偿，谢谢！

**Comment by ssrlive** [comment]
我只用 vs 2010 . 抱歉帮不上忙.

**Comment by rockswang** [comment]
谢谢大佬，那我先下个vs 2010试试，主要是之前官网没找到

**Comment by ssrlive** [comment]
https://visualstudio.microsoft.com/vs/older-downloads/?rr=https%3A%2F%2Fwww.google.com%2F

**Comment by rockswang** [comment]
多谢多谢！不过这个我之前就试过了，显示：
Sorry, we couldn't find any downloads for you.
To continue, please join Visual Studio Dev Essentials or purchase a Visual Studio Subscription.

国内搜到的怕有木马，没办法才下了2019，刚才网盘找了一个2010，我先试试吧

**Comment by rockswang** [comment]
多谢提示，我又试了试，原来只要登录之后再免费订阅一下就可以了

**Comment by rockswang** [comment]
我的操作系统是win10 64位版，装了vs2010学习版，构建错误也是一样的：
fatal error C1083: 无法打开包括文件:“poll.h”: No such file or directory

**Comment by ssrlive** [comment]
搞完.

**Comment by rockswang** [comment]
不愧是大佬，解决了！感激不尽！
