### ISSUE TITLE
祝贺更新！SSRoT感觉高大上！喜大普奔！

### ISSUE THREAD

**Issue by rockswang** [ShadowsocksR-Live/shadowsocksr-native#62]
几个问题想跟大佬请教一下：
1. 为什么要基于websocket，是基于性能考虑吗？wss本身会不会产生什么特征？
2. 用自签名证书可以么？
3. 为何需要用随机串作为location? 在https里面，整个header部分都是加密的吧，gfw应该无法解析出url的path部分吧？

**Comment by ssrlive** [comment]
基于 websocket 是因为 反向代理的服务器 如 nginx 或者 caddy  Apache 等，对它有良好的支持。 标准的 https
通讯，不会有其它特征。

自签名证书 纯粹就是送人头给 GFW。

必须是随机串做 location ， 让 gfw 试不出 你的 location， 否则，你的内容如果没有另一重加密，你在 gfw
面前就是裸奔。另外，我的实现里，ws 的握手包里，携带有 s5 格式的目标地址，如果gfw 猜出了你的 location
，再发现了这个拖油瓶。立马猜出你在翻墙，干掉你是分分钟的事。

**Comment by rockswang** [comment]
感谢大佬解惑！

**Comment by ssrlive** [comment]
安装教程和一键脚本已写好. 欢迎 测试 使用.
https://github.com/ShadowsocksR-Live/shadowsocksr-native/wiki

**Comment by rockswang** [comment]
谢谢大佬！
今天按照文档试了下，结果freenom.com注册免费域名不成功，后来google了一下发现是普遍问题，建议大佬还是不要推荐这个了

**Comment by ssrlive** [comment]
哪个较易成功？

**Comment by rockswang** [comment]
啊？今天我折腾了很久也没成功啊，网页上说遇到技术问题，调官网提供的api试了下search.xml，如果传domaintype=FREE则返回NOT AVAILABLE，如果传PAID，倒是每次都能返回结果……

**Comment by rockswang** [comment]
网页直接注册，最后结果就是这个样子，我试了好几次都一样：
https://www.stylefanr.org/archives/1968

**Comment by ssrlive** [comment]
我注册 freenom 时, 一直翻着墙, 用 Google 账号登录. 个人信息填美国人, 当然全是假的. 然后 freenom 从未让我失望.

**Comment by ssrlive** [comment]
![image](https://user-images.githubusercontent.com/30760636/63158885-d24fbf80-c04c-11e9-8e1f-9b6aa5570dbd.png)

**Comment by ssrlive** [comment]
![image](https://user-images.githubusercontent.com/30760636/63159046-2eb2df00-c04d-11e9-97e4-5081771f201f.png)

**Comment by rockswang** [comment]
娘的，这样真可以，真是难为死我们这些没肉身翻过墙的穷逼土鳖了……

**Comment by ssrlive** [comment]
好! 我去加条注释.

**Comment by sdtptj** [comment]
大佬，我免费的是注册不起了，注册了一个一年0.99$的腊鸡域名！不过能用就好了，谢谢大佬！
其实我想问一下，手机怎么办，可以全局吗，几个人同时用可以吗？

**Comment by ssrlive** [comment]
手机上的客户端目前没有弄好, 有个变通的方法; 
在台式机上运行客户端, 注意配置文件里的设置
```
    "client_settings": {
        "server": "12.34.56.78",
        "server_port": 12475,
        "listen_address": "0.0.0.0",
        "listen_port": 1080
    },
```
监听地址是 `0.0.0.0` 表明你的手机可以用 连接 socks5 服务器的方式, 连上 SSRoT 客户端. 
目前 iOS 上有 Potatso lite 有这个功能. 安卓手机上不详.

希望你能明白我的意思. 翻得开心.

**Comment by sdtptj** [comment]
千言万语化作两字，感谢！！！

ssrlive <notifications@github.com> 于2019年9月22日周日 下午8:13写道：

**Comment by 960PRO** [comment]
谢谢这次的更新，您的SSRoT将会与SS、SSR一样出名。感谢您（另外两个值得感谢的是Clowwindy与Breakwa11{破娃酱}）。

**Comment by kakaxiaodain6** [comment]
大佬好！ 有2个问题需要请教。
1，后期是否会有docker版方便部署？
2，ssrot是否可以对接sspenal？
以上问题纯属小白提问，如有不妥，还望多多指教。感谢！🙏

**Comment by ssrlive** [comment]
sspanel 的开发者把我当仇人在防备，我倒想，人家不干。
docker 怎么玩的目前没搞明白。

**Comment by kakaxiaodain6** [comment]
> sspanel 的开发者把我当仇人在防备，我倒想，人家不干。
> docker 怎么玩的目前没搞明白。



> sspanel的开发者把我当仇人在防备，我倒想，人家不干。docker
> 怎么玩的目前没搞明白。

开源的sspanel v3魔改版是不是可以直接拿来搞了？
docker版建议大佬可以参考下ssr docker配置   
大佬加油，感觉您能搞定！
