### ISSUE TITLE
关于windows平台的ssr-client.exe

### ISSUE THREAD

**Issue by rockswang** [ShadowsocksR-Live/shadowsocksr-native#63]
又有问题要麻烦大佬了！

### What version of shadowsocks-native are you using?
release里的0.5 windows x64版

### What operating system are you using?
Windows10

### What did you do?
1. 海外服务器已经正常启动，用c#版客户端可以正常使用
2. 配置好config.json，双击ssr-client.exe启动，显示：
ssr-client.exe:info: ShadowsocksR native client

ssr-client.exe:info: remote server    161.**********:33330
ssr-client.exe:info: method           aes-128-ctr
ssr-client.exe:info: password         ja******************
ssr-client.exe:info: protocol         auth_aes128_md5
ssr-client.exe:info: obfs             http_simple
ssr-client.exe:info: udp relay        yes

ssr-client.exe:info: listening on     0.0.0.0:2080

### What did you see instead?
使用curl验证：
* C#版可以用curl -x 127.0.0.1:1080 正常访问任何海外站点
* ssr-client用-x无法连接
* ssr-client用--socks5可以正常打开部分站点，包括https://www.baidu.com, http://httpbin.org/get等，但google, facebook都不行，表现为连接超时

还测试了python版的local.py，完全连不上，目前只有C#版的客户端完全正常

**Comment by ssrlive** [comment]
curl -x socks5h://localhost:2080 http://www.google.com/

**Comment by rockswang** [comment]
这样果然可以，孤陋寡闻了，头一次见到这种写法，谢谢解惑！
