### ISSUE TITLE
Remote dns

### ISSUE THREAD

**Issue by changhe3** [ShadowsocksR-Live/shadowsocksr-native#65]
如何在配置文件中开启remote dns?

**Comment by ssrlive** [comment]
dns 解析其实全部在 服务端 进行的， 唯一需要 本地 dns 解析的就是连接你的 ssr 服务器，所以 ssr 服务器直接设置成 IP
会稍微快一点。

**Comment by changhe3** [comment]
我在同一个wifi下同一个节点用安卓就能正常使用，但在Ubuntu 19.04上尝试了很多客户端都不行

**Comment by ssrlive** [comment]
想来你服务器设置错误

**Comment by changhe3** [comment]
出现很多 connection failed about _server_ "www.google.com": host is unreachable

**Comment by ssrlive** [comment]
主机不可达。根本没有连上服务器

**Comment by changhe3** [comment]
这是买的梯子，我去问问他们的support吧

**Comment by changhe3** [comment]
然而 https://github.com/shadowsocksrr/shadowsocksr-libev 这个版本就可以连上

**Comment by ssrlive** [comment]
那就不知道了.
