### ISSUE TITLE
请教SSRoT在iOS上使用

### ISSUE THREAD

**Issue by tmaccs** [ShadowsocksR-Live/shadowsocksr-native#74]
Please answer these questions before submitting your issue. Thanks!

### What version of shadowsocks-native are you using?
SSRoT

### What operating system are you using?
Ubuntu 18 + iOS

请问这个SSRoT能像之前的那样在SSR客户端配置使用么？

**Comment by ssrlive** [comment]
真正实验阶段，目前只能刷推，其它的一概出错，努力找原因中……
