### ISSUE TITLE
问一下为什么windows上没有效果

### ISSUE THREAD

**Issue by ninjaduan** [ShadowsocksR-Live/shadowsocksr-native#76]
Please answer these questions before submitting your issue. Thanks!

### What version of shadowsocks-native are you using?
0.6

### What operating system are you using?
win10

### What did you do?
使用ssr-native-windows-x64里的ssr-client启用代理

### What did you expect to see?
访问google

### What did you see instead?
不能访问google

### What is your config in detail (with all sensitive info masked)?
全自动安装&手动安装都试过了
下面是全自动安装后的设置
```
{
    "password": "***********",
    "method": "chacha20",
    "protocol": "auth_aes128_md5",
    "protocol_param": "",
    "obfs": "tls1.2_ticket_auth",
    "obfs_param": "",

    "udp": false,
    "timeout": 300,

    "server_settings": {
        "listen_address": "0.0.0.0",
        "listen_port": 12528
    },

    "client_settings": {
        "server": "104.*.*.*",
        "server_port": 443,
        "listen_address": "0.0.0.0",
        "listen_port": 1080
    },

    "over_tls_settings": {
        "enable": true,
        "server_domain": "******.icu",
        "path": "/zxbvq5Q1qZRBGmGZFVcE/",
        "root_cert_file": ""
    }
}
```
服务器的web服务能正常使用，能够通过域名访问全自动安装后的默认网页，https开头。
但是win上用客户端，命令行能正常显示前面所有行，就是在listening on***那一行之前就自动退出了，也没有任何提示。
求问是哪里没有做对？

**Comment by ssrlive** [comment]
估计是哪个我没发现的bug. 让客户端直接崩溃了. 你照 这个教程 自己编译调试一下. 把崩溃结果发给我. 谢谢. 🙏.

https://palitechsociety.blogspot.com/2019/08/shadowsocksr-over-tls-ssrot-client.html

**Comment by ssrlive** [comment]
估计是 `"method": "chacha20",` 惹的祸. 你把它改成别的吧.

**Comment by ssrlive** [comment]
已修正。

**Comment by ninjaduan** [comment]
挖，好的大佬我试试
