### ISSUE TITLE
native和old工程的一些问题

### ISSUE THREAD

**Issue by smallb** [ShadowsocksR-Live/shadowsocksr-native#8]
native是不支持udp的么？

old下，udp转发只转发了第一个包，之后服务器回的包没有转发回来。。。

不知道是不是个案。

**Comment by ssrlive** [comment]
udp 包转发的工作没有完成. 要不你继续这个工作?

**Comment by smallb** [comment]
额。我先去看看old工程吧。能补上我就补上。。
