### ISSUE TITLE
Mac上chrome使用127.0.0.1：1080无效，改成局域网内windows机器的ip：1080有效

### ISSUE THREAD

**Issue by yilovezy** [ShadowsocksR-Live/shadowsocksr-native#80]
windows机器上运行ssr-client.exe后，chrome设置了127.0.0.1：1080代理后，可以上google。mac上运行ssr-client后，chrome设置了127.0.0.1：1080代理后，无法上google，chrome代理改为上面的windows ip后，可以上google。怎么回事？

**Comment by yilovezy** [comment]
弄过了，打开google的时候，控制台无输出，只有启动的时候有输出，和windows上启动的输出一样。感觉chrome没链接到mac1080端口

**Comment by yilovezy** [comment]
可以了，厉害了，怎么回事啊？

**Comment by ssrlive** [comment]
1080 端口已经被其他程序占用了.

**Comment by yilovezy** [comment]
占用的话，你程序还能启动起来监听？感觉应该报个错吧，启动的时候

**Comment by ssrlive** [comment]
应该是报错以后就退出了
