### ISSUE TITLE
一会就死了

### ISSUE THREAD

**Issue by wangwanggogo19xx** [ShadowsocksR-Live/shadowsocksr-native#82]
Please answer these questions before submitting your issue. Thanks!

### What version of shadowsocks-native are you using?

最新
### What operating system are you using?
aws  or google cloud

### What did you see instead?

一段时间后主进程就自己死掉了

10月 13 10:41:29 hongkong systemd[1]: ssr-native.service: main process exited, code=killed, status=6/ABRT
10月 13 10:41:29 hongkong ssr-native[20502]: ShadowsocksR Native is stopped
10月 13 10:41:29 hongkong systemd[1]: ssr-native.service: control process exited, code=exited status=1
10月 13 10:41:29 hongkong systemd[1]: Unit ssr-native.service entered failed state.

**Comment by ssrlive** [comment]
What is your config in detail (with all sensitive info masked)?

**Comment by wangwanggogo19xx** [comment]
i don't modify config file,i just run ssrn-install.sh.and my settings as as follows:
Your Server Port      :  8388 
Your Password         :  12345678 
Your Protocol         :  origin 
Your obfs             :  http_simple 
Your Encryption Method:  aes-256-cfb

**Comment by ssrlive** [comment]
今天调试，死了一次，然后就没有重现了。你的情况是，在访问什么网站时死的？

**Comment by wangwanggogo19xx** [comment]
google，YouTube之类的，之前是经常过了一会 进程就会死掉了

**Comment by ssrlive** [comment]
你现在取下代码，重新安装一次。看看还死不死？

**Comment by ssrlive** [comment]
配置不要改变。保持原样。

**Comment by ssrlive** [comment]
出现了。应该很好处理。感谢。
![image](https://user-images.githubusercontent.com/30760636/69329640-6d7bb500-0c8c-11ea-9343-d3674a77afd1.png)

**Comment by ssrlive** [comment]
找到了。
![image](https://user-images.githubusercontent.com/30760636/69329956-03174480-0c8d-11ea-99d8-5c2f3607c1af.png)

**Comment by ssrlive** [comment]
已修正。
