### ISSUE TITLE
Apache2 config?

### ISSUE THREAD

**Issue by markcs** [ShadowsocksR-Live/shadowsocksr-native#83]
Can you share a working configuration example for apach2 web server?

I followed the instructions [here](https://palitechsociety.blogspot.com/2019/08/shadowsocksr-over-tls-ssrot-server.html?m=1) but I can not get it to work correctly (I don't use nginx).  I only see the error 'junk in handshake', and I assume that is because my apach2 configuration is incorrect.

Thanks

**Comment by ssrlive** [comment]
I have no time to do the work. Maybe other people can do it.
