### ISSUE TITLE
网速问题：youtube视频只能240p还卡顿，，，

### ISSUE THREAD

**Issue by tiyo** [ShadowsocksR-Live/shadowsocksr-native#86]
aws的t3a.micro用上了，一切顺利，就视频比较痛苦
缓冲好像有点不可理喻，，，视频播放中，关掉safari，，，，还有声音。。。恐怖不恐怖？

**Comment by ssrlive** [comment]
亚马逊的 VPS 您就担待一点吧! 白嫖您该知足了. 可以试着开启 BBR 试试?
