### ISSUE TITLE
SSR-Client for Windows

### ISSUE THREAD

**Issue by GentleRV** [ShadowsocksR-Live/shadowsocksr-native#88]
After starting the dos version of SSR-CLIENT, after trying to display a page in Firefox I see junk in handshake in red characters.
De same configuration I tried with the Shadowsocks dotnet versions, which make the connection and works well.
Only thing I have with the dotnet versions is that I still receive advertisements.
The server is installed on Ubuntu 18.04 system

Before I used on the server 

Please answer these questions before submitting your issue. Thanks!

### What version of shadowsocks-native are you using?
Latest version

### What operating system are you using?
Windows 8.1

### What did you do?
Modified the .json config file
started the client in normal mode

**Comment by ssrlive** [comment]
What is your config in detail (with all sensitive info masked)?

**Comment by GentleRV** [comment]
{
    "password": "password",
    "method": "aes-256-cfb",
    "protocol": "auth_aes128_sha1",
    "protocol_param": "",
    "obfs": "tls1.2_ticket_auth",
    "obfs_param": "",

    "udp": false,
    "timeout": 300,

    "server_settings": {
        "listen_address": "0.0.0.0",
        "listen_port": 18159
    },

    "client_settings": {
        "server": "server ipadress",
        "server_port": 18159,
        "listen_address": "192.168.8.104",
        "listen_port": 1080
    },

    "over_tls_settings": {
        "enable": false,
        "server_domain": "goodsitesample.com",
        "path": "/yioewrkfds989832kjdsf/",
        "root_cert_file": ""
    }
}

Only password and server ipadress are left out,

Greetings,

Ronald

**Comment by ssrlive** [comment]
测试了半个小时。没发现问题。
![image](https://user-images.githubusercontent.com/30760636/69401172-4c1fd500-0d2f-11ea-9a38-808910de8f09.png)
