### ISSUE TITLE
高带宽使用时（如：测速）程序会崩溃并报错

### ISSUE THREAD

**Issue by jitdor** [ShadowsocksR-Live/shadowsocksr-native#89]
ssr-client: /home/ssrlive/Desktop/ssr-n/src/client/client.c:639: do_ssr_receipt_for_feedback: Assertion `error == ssr_ok' failed.
Aborted (core dumped)

**Comment by ssrlive** [comment]
我没条件复现. 你在 tunnel_cipher_client_decrypt 函数里的几个错误返回点打断点, 看看是啥原因?

**Comment by ssrlive** [comment]
测试 了 没有 崩溃。
请 写出 详细 的 测试 方法 和 过程。

![image](https://user-images.githubusercontent.com/30760636/69491372-278d3f80-0e8c-11ea-9492-d5c34faf8565.png)

**Comment by jitdor** [comment]
请问如何在tunnel_cipher_client_decrypt函数打断点？

我用的是GCP的机子，Ubuntu 18.04 LTS. ssr-local 与 ssr-client 都是从git源码编译的（下载Zip的0.7版本也用过了，结果一样），两个都会崩溃

SSR连线有使用协议参数，不知道是不是原因所在？

![ssr-n](https://user-images.githubusercontent.com/8012216/69491856-09e4c800-0ed6-11ea-9459-4eef5fd21eb9.png)

**Comment by ssrlive** [comment]
把配置去掉敏感信息后发到这里

**Comment by jitdor** [comment]
这是用在 ssr-local 的配置

{
"server": "xxxxx.com",
"server_port": 11036,
      "password": "xxxxxx",
"method": "aes-256-cfb",
"protocol": "auth_aes128_sha1",
"protocol_param": "46431:3O0JUb",
"obfs": "http_simple",
"obfs_param": "c0fab.update.microsoft.com",

"local_address": "0.0.0.0",
"local_port": 1081,

"udp": true,
"timeout": 300
}

ssr-client 的有 client_settings {}

**Comment by ssrlive** [comment]
是协议的实现有问题。你可换用 `auth_aes128_md5`。
````
 "protocol": "auth_aes128_sha1",
````

**Comment by jitdor** [comment]
不是我的服务器呢，只能暂时用Python的版本，比较占资源...

**Comment by ssrlive** [comment]
请告诉我服务端软件的源代码链接。或者服务供应商的名称。

**Comment by ssrlive** [comment]
请告诉我服务端软件的源代码链接。或者服务供应商的名称。我的测试是，无论用哪种客户端，都连不上，但去掉 46431:3O0JUb 中的冒号后，就可以了。因此得检查服务端的源码。

**Comment by jitdor** [comment]
机场“几鸡”(ji-r.pw)和“养鸡场”(yjc-b.xyz)都是用类似的协议参数，用户都不能更改的

**Comment by ssrlive** [comment]
将服务器设置成 `"protocol_param":"64#12345:breakwa11,233:breakwa11",` 。 将 客户端设置成 `"protocol_param": "12345:breakwa11",` 没发现 ssr-client 有什么异常。

**Comment by miffyrcee** [comment]
```
ssr-client 2019/12/06 16:35  info  ShadowsocksR native client

ssr-client 2019/12/06 16:35  info  remote server    cnbg*******************:843
ssr-client 2019/12/06 16:35  info  method           chacha20
ssr-client 2019/12/06 16:35  info  password         GS*******
ssr-client 2019/12/06 16:35  info  protocol         auth_aes128_md5
ssr-client 2019/12/06 16:35  info  obfs             http_simple
ssr-client 2019/12/06 16:35  info  obfs_param       xxxxxx.xxx.in
ssr-client 2019/12/06 16:35  info  udp relay        no

ssr-client 2019/12/06 16:35  info  listening on     127.0.0.1:8089

ssr-client 2019/12/06 16:35  info  ==== tunnel created     count   1 ====
ssr-client 2019/12/06 16:35  info  ==== tunnel created     count   2 ====
ssr-client 2019/12/06 16:35  info  ==== tunnel created     count   3 ====
ssr-client 2019/12/06 16:35  info  ==== tunnel created     count   4 ====
ssr-client 2019/12/06 16:35  info  ==== tunnel created     count   5 ====
ssr-client 2019/12/06 16:35  info  ==== tunnel created     count   6 ====
ssr-client 2019/12/06 16:35  info  ==== tunnel created     count   7 ====
ssr-client: /home/ssrlive/Desktop/ssr-n/src/client/client.c:639: do_ssr_receipt_for_feedback: Assertion `error == ssr_ok' failed.
[1]    6701 abort (core dumped)  ssr-client
```
大佬，我发现我先打开我那个bug视频链接，发现日志没怎么刷屏幕后，ctrl-c，然后再重新打开，就像上面这样再显示一段之后很快就出现这个问题，感觉这样可能容易出现这个问题。

**Comment by miffyrcee** [comment]
```
https://www.youtube.com/watch?v=fjrMkTREYlY&list=PL-HX3y3Jh1R8Qvj8icaUMlPyYDAgZ5PFl&index=89
```

**Comment by ssrlive** [comment]
还是没问题。
![image](https://user-images.githubusercontent.com/30760636/70323014-a9a33e00-1866-11ea-8299-7e2b3e909c83.png)

**Comment by estoniah** [comment]
ssr-client -c tokyo-cfg.json 
ssr-client 2020/03/12  6:13  info  ShadowsocksR native client

ssr-client 2020/03/12  6:13  info  remote server    202.**********:12475
ssr-client 2020/03/12  6:13  info  method           salsa20
ssr-client 2020/03/12  6:13  info  password         ss**************
ssr-client 2020/03/12  6:13  info  protocol         auth_chain_b
ssr-client 2020/03/12  6:13  info  obfs             tls1.2_ticket_auth
ssr-client 2020/03/12  6:13  info  udp relay        no

ssr-client 2020/03/12  6:13  info  listening on     192.168.124.12:1080

ssr-client 2020/03/12  6:13  info  ==== tunnel created     count   1 ====
ssr-client: /home/estonio/work/ssr-n/src/ssr_executive.c:454: tunnel_cipher_client_encrypt: Assertion `buf->capacity >= 2048' failed.

换了好几个设置，老出Assertion failed

**Comment by ssrlive** [comment]
写明访问啥网站时有会出现这情况

**Comment by estoniah** [comment]
任何网站都崩溃， 空机器新装ssr_client也崩溃，怎么办？
tunnel_cipher_client_encrypt: Assertion `buf->capacity >= 2048' failed.

**Comment by estoniah** [comment]
把 buffer_create的最小 capacity 改成 2048，下列A不会出现了，
A: tunnel_cipher_client_encrypt: Assertion `buf->capacity >= 2048' failed.

但是
ssr-client 2020/03/18 17:27  info  ==== tunnel created     count   1 ====
ssr-client: /home/estonio/work/ssr-n/src/client/client.c:680: do_ssr_receipt_for_feedback: Assertion `error == ssr_ok' failed.

兄弟帮帮忙，好长时间无法访问外网了。

**Comment by ssrlive** [comment]
我不知道你的情況為什麼這麼嚴重，好長時間我被別的事情拌住手腳無法分身。你還是使用SSRoT 吧。那個目前沒加密不會崩潰。

**Comment by ssrlive** [comment]
#117 已修正。
