### ISSUE TITLE
[REDIR] 透明代理 

### ISSUE THREAD

**Issue by denggj28** [ShadowsocksR-Live/shadowsocksr-native#90]
请问ssr-client支持透明代理吗？类似ss-redir的功能

**Comment by ssrlive** [comment]
目前沒精力做這個

**Comment by ssrlive** [comment]
redir 通常运行在 路由器（软路由）上用于透明代理，原因：
1. 对于 TCP 流量， 路由器在转发流量时会做NAT（内网 ip to -> 公网 ip），路由器可以劫持这部分流量转给 redir 作为输入,  而  redir 通过 SO_ORIGINAL_DST 获取流量的目的地址转发出去
2. UDP 流量稍有不同，不能通过（SO_ORIGINAL_DST 不支持UDP） 获取目的地址， 需要通过 recvmsg() 系统调用 解析 IP_RECVORIGDSTADDR 以获取目的地址转发

需要注意的是路由器劫持的流量均为**正常流量**包非 sock5（switchomega 转发）


其实
ssr-redir = ssr-local + redsocks

没了
