### ISSUE TITLE
[错误]  [CA] 获取 网站证书 失败 

### ISSUE THREAD

**Issue by jibanli** [ShadowsocksR-Live/shadowsocksr-native#92]
Please answer these questions before submitting your issue. Thanks!

### What version of shadowsocks-native are you using?

最新的
### What operating system are you using?
搬瓦工ubuntu18.04

### What did you do?

刚注册了一个域名，绑定搬瓦工IP了，也能ping通域名。但是用全自动安装的方法，出现了这个错误。求大佬帮忙
![ca错误](https://user-images.githubusercontent.com/39478794/69772899-3c3f3f80-11cc-11ea-9b6a-1080206d0167.png)

**Comment by ssrlive** [comment]
重做一次

**Comment by jibanli** [comment]
不行啊，还是一样的错误。。打开www.na.nalcw.info显示
![错误1](https://user-images.githubusercontent.com/39478794/69773773-ba044a80-11ce-11ea-8c2f-cf7e7f19d2a8.png)

**Comment by ssrlive** [comment]
解析域名时， 你得加上 www 和 无 www 解析都加上。

**Comment by ssrlive** [comment]
![image](https://user-images.githubusercontent.com/30760636/69774489-02bd0300-11d1-11ea-834c-9a738b167138.png)

**Comment by ssrlive** [comment]
仔细看了你的域名，貌似是二级域名，这个脚本可能对二级域名处理有问题。你最好使用顶级域名。反正免费的顶级域名随便注册，又没有成本。

**Comment by ssrlive** [comment]
错误已经明确地说了：
```
Name or service not known.
```
你就是忘了解析 www 了。

**Comment by jibanli** [comment]
> 错误信息已经说得很明确了：
> 
> ```
> Name or service not known.
> ```
> 
> 你就是忘了解析 www 了。
不是忘了，是不会操作。。。。

**Comment by jibanli** [comment]
按你说的现在没这个错误啦
