### ISSUE TITLE
ss怎么添加混淆，添加http和tls的混淆

### ISSUE THREAD

**Issue by aishuidedabai** [ShadowsocksR-Live/shadowsocksr-native#95]
Please answer these questions before submitting your issue. Thanks!

**Comment by ssrlive** [comment]
裸的 ss/ssr 在 gfw 面前毫无胜算。怎么混淆都没用。别在错误的方向上努力了。

**Comment by aishuidedabai** [comment]
我只是想知道怎么加，有一些其他功能需要用到，求指点

**Comment by ssrlive** [comment]
https://github.com/ShadowsocksR-Live/shadowsocksr-native/blob/master/src/obfs/auth.c#L160

**Comment by ssrlive** [comment]
https://github.com/ShadowsocksR-Live/shadowsocksr-native/blob/master/src/obfs/http_simple.c#L68

**Comment by aishuidedabai** [comment]
我没看懂这里应该怎么加，这就是普通的http_simple
