### ISSUE TITLE
python/systemd启动问题

### ISSUE THREAD

**Issue by miffyrcee** [ShadowsocksR-Live/shadowsocksr-native#97]
v0.7,linux fedora31,我将其当作了一个客户端。
使用python的subprocess.call('/usr/local/bin/ssr-client -c /etc/ssr-nativate/config.json'.split(' '))
或者使用subprocess.call('systemctl restart ssr-client.service'.split(' '))
都会莫名奇妙出现
![Screenshot from 2019-12-03 21-20-48](https://user-images.githubusercontent.com/43992258/70054614-d95a0800-1612-11ea-95ae-d04d6e3049b6.png)
配置无问题，手动systemctl restart正常
但是在使用过程中，网站显示该网页已经移动到别的位置，日志显示
![Screenshot from 2019-12-03 21-15-08](https://user-images.githubusercontent.com/43992258/70054764-1cb47680-1613-11ea-91d7-f77eeb5c64ee.png)
请问该如何解决啊？😢
每一次出现该问题都会在/var/lib/systemd/coredump/里有如下记录😢
![Screenshot from 2019-12-03 21-33-47](https://user-images.githubusercontent.com/43992258/70055556-b9c3df00-1614-11ea-8f6a-81f414d2871a.png)

**Comment by ssrlive** [comment]
What is your config in detail (with all sensitive info masked)?

**Comment by miffyrcee** [comment]
![Screenshot from 2019-12-03 21-55-30](https://user-images.githubusercontent.com/43992258/70057181-abc38d80-1617-11ea-9260-c44c91dfaf2c.png)
鸡厂配置，做个客户端用

**Comment by miffyrcee** [comment]
不好意思哈，那个python没写好，把启动写在with里面了。

**Comment by ssrlive** [comment]
把ip和端口拿掉，复制粘贴配置过来。

**Comment by miffyrcee** [comment]
```
{
    "password": "*********",
    "udp": "true",
    "timeout": 300,
    "client_settings": {
        "server": "*******.cc",
        "server_port": ***1,
        "listen_address": "127.0.0.1",
        "listen_port": 8089
    },
    "method": "rc4-md5",
    "obfs": "http_simple",
    "obfs_param": "*********.in",
    "protocol": "auth_aes128_md5",
    "protocol_param": ""
}
```
大佬，貌似当我去掉那些server_settings，tls之类的就没怎么发生这个情况了。

**Comment by ssrlive** [comment]
不可能，客户端根本没通过那些参数。

**Comment by miffyrcee** [comment]
额，大佬，我改回去又试了下，发现确实还是没发生这个问题了，😫，谢谢大佬，我还是继续用着试试吧。
