### ISSUE TITLE
只是翻个墙而已，没必要政治化

### ISSUE THREAD

**Issue by john990** [ShadowsocksR-Live/shadowsocksr-native#98]
有墙的同时也保护了国内的互联网行业，希望你的WiKi不要那么愤青。

**Comment by ssrlive** [comment]
那你继续当一头快乐的猪去吧！

**Comment by john990** [comment]
呵呵

**Comment by adaaaaaa** [comment]
> 那你继续当一头快乐的猪去吧！

作者是恨国党吗？？🤪

**Comment by ssrlive** [comment]
`被剥夺了基本 通讯自由 以至于上个破网都是犯罪`, 你 @adaaaaaa 觉得你很俏皮? 你认为你不是 吴花燕？

**Comment by adaaaaaa** [comment]
> 上个破网都是犯罪

没有犯罪啊，只要你不是提供机场给大家用就不是。。。建议你看看美国人“火锅大王”解释，中国为什么建墙，当然，我在他之前已经知道了为什么。。。

**Comment by adaaaaaa** [comment]
> 自由

看来你是认同了西方的民主自由，普世价值了哈？🤪

**Comment by ssrlive** [comment]
能把自己的不堪处境看成仙境，也就你了。滚吧！

**Comment by ssrlive** [comment]
![image](https://user-images.githubusercontent.com/30760636/73589158-88c93300-450d-11ea-8b46-7305d9125e28.png)

**Comment by ssrlive** [comment]
![image](https://user-images.githubusercontent.com/30760636/73589223-671c7b80-450e-11ea-9cba-2dd071ae9d0b.png)

**Comment by ssrlive** [comment]
每一个傻逼都认为自己是灾难深重的芸芸众生中的唯一幸运儿,所有的暴政、灾难都会仁慈地放过自己.因此 不关心政治是它们苟且偷生的堂皇借口. 这种傻逼你还活着干嘛?赶紧死了为地球节省点资源吧! 上面发 呵呵 的, 当 社会主义铁拳 公平地无差别地砸向你头上时要像条汉子别哀嚎.

**Comment by tec1987** [comment]
中国现有问题哪一个跟政治毫不相干？？？
政治问题一定要政治解决，否则墙永远不会倒。。。

**Comment by tec1987** [comment]
@john990 如果你是BAT的员工，那么恭喜你被保护了。如果你是湖北人，那么祝你“被保护”的平平安安。

@ssrlive 建议作者也不要过于激动，骂人是解决不了问题的。。。
对于有些长期被洗脑，患有类斯德哥尔摩综合征的人，需要一定的耐心
