### ISSUE TITLE
CMakeLists.txt: change install from absolute path to relative path

### ISSUE THREAD

**Issue by Vonfry** [ShadowsocksR-Live/shadowsocksr-native#99]
Please answer these questions before submitting your issue. Thanks!

### What version of shadowsocks-native are you using?
HEAD

### What operating system are you using?
NixOS

### What did you do?
write a nix expression to build it on nixos

### What did you expect to see?
build success

### What did you see instead?
error when installing.

The reason is in the CMakeLists.txt, e.g. https://github.com/ShadowsocksR-Live/shadowsocksr-native/blob/master/src/CMakeLists.txt#L241-L245. It codes `install` with absolute path, which make `CMAKE_INSTALL_PREFIX` not working. I suggest change it to a relative path, make the install phase more compatible.

**Comment by ssrlive** [comment]
We just want to keep things simple. Our users are ordinary people, not all programmers. So don't want to add complexity.

**Comment by Vonfry** [comment]
Right, just advice.  I can make a patch for myself to let it run.

**Comment by ssrlive** [comment]
well, you can commit a PR, and add a cmake parameter in the same time in install.sh file.
